- docs/about/Authors.rst
- docs/changelog.txt
- plugins/autodump.cpp
`autodump` now conditionally removes an item's dump flag and sets forbid flag IFF the item is successfully dumped. Otherwise, the item's original flags are kept intact. This avoids impacting any tasks associated with the item.
> [issue-2888] Don't change dump and forbid flags on failed autodump

- docs/changelog.txt
- plugins/seedwatch.cpp
Fixes #2884
this allows stored targets to be loaded and applied to their proper seed types
> properly store the id of seed targets in persisted state

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
Allow providing a custom callback for `edit.on_change` in the same way we do for `edit.on_char`. I had a need to get the final value of the edit widget after a change, and `on_char` wasn't able to reliably give me what I needed (can't concat `c` and `text` without taking the cursor position into account).
> Add edit_on_change to FilteredList

- docs/changelog.txt
- plugins/showmood.cpp
Fixes #2610
now prints out the item quantity as well as the "total dimensions" for bars and cloth. other item types have unchanged output
> [showmood] show more understandable units for bars and cloths

- docs/changelog.txt
- plugins/autochop.cpp
- plugins/lua/autochop.lua
Fixes #2887
looking through the code, I'm actually not quite sure how the burrow was found during validation in the cpp but not found when getting its name in the lua. I added a check in the Lua to catch this case regardless.
> generate names for nameless burrows; check for nil

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/modules/Gui.cpp
Mostly helpful for my own automation in my custom lua scripts.
Tested it with barracks, meeting areas, and pastures.
> Add getSelectedCivZone to dfhack.gui

- docs/changelog.txt
- library/lua/gui.lua
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
because if you're in mining mode, clicking on a tool in the DFHack hotspot menu *still* causes the mining mode cursor to start selecting an area
> prevent mouse clicks from bleeding through when a window is dismissed

- docs/changelog.txt
- library/modules/Buildings.cpp
Changed the StockpileIterator::operator++ to checks blocks based on <= 16 rather than <16. Previously the iterator was not returning items at stockpile tiles at the block boundary. Identified as part of combine.lua changes.
> Not all stockpile items being returned for getStockpileContents.

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
Attempt at adding Tab/TabBar as widgets, with some slight modifications to allow customization where users may want to do so, and first pass at some docs to go along with it.
If/once this looks alright I can do a followup either here or in another PR to switch control-panel.lua over to use these.
If it looks like I had an aneurysm with spelling anywhere I just wanna throw it out there in advance.. I have covid and fully blame that 😛
> Add Tab/TabBar to widgets

- docs/changelog.txt
- plugins/confirm.cpp
When I updated `confirm` I made it so `df::global::gps->force_full_display_count = 1;` was running every frame ><.
This fixes that by adding a `dirty` field to `confirmation_base`. It  defaults to `false`, gets set to `true` during `set_state`, and if `true` we will `df::global::gps->force_full_display_count = 1` at the end of `render()` and set it back to `false`.
I am unable to actually replicate the fps issues on my machine, but this seems like the culprit. Playtested with a breakpoint to confirm it is only executed after a state change. Playtested without the breakpoint and confirmed that the dialogs are still getting cleaned up properly.
While I was at it I moved some other variables into the only branch that uses them, that were getting initialized every frame unnecessarily.
> Fix confirm performance

- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
Labels show the hover colour when on_click is set, HotkeyLabels should also do the same when they are clickable.
In my opinion, this makes it a lot easier to click, as someone who's not very good at clicking.
And as a usability suggestion, feel free to disagree and reject this PR!
https://user-images.githubusercontent.com/5893/218945682-c5d0dfdc-9655-4b80-951b-910be1f36630.mp4
> Usability: Show mouse hover on all clickable Labels/Lists

- depends/md5/md5.cpp
- library/Core.cpp
two change:
* remove use of `register` in `md5.cpp`
* remove use of `using namespace std` in `Core.cpp` (which causes an ambiguous name resolution error between `byte` and `std::byte`). while there are other ways to resolve this, `using namespace std` is a code smell anyway, so eliminating it is the best option
> clean up code for C++20 readiness

- docs/changelog.txt
- library/modules/Materials.cpp
previously we were only checking the melting point, but some fire-unsafe materials (like logs) have no melting point, and the check was giving a false negative. this change calls a material unsafe if any of the relevant properties are in the danger zone.
> [isSuitableMaterial] detect lack of fire and magma safety for vulnerable materials with high melting points

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
thinnest border line and no DFHack signature on the bottom, for interior accent areas.
> Add standard interior frame to gui.lua

- docs/changelog.txt
- library/modules/Gui.cpp
- library/modules/Screen.cpp
this allows you to "masquerade" as a vanilla context if you so desire. For example, the `buildingplan` ZScreen-based dialogs indicate that they are still part of the building placement context by declaring a focus string of "dwarfmode/Building/Placement/dfhack/lua/buildingplan/itemselection"
> [Gui] don't prefix focus strings that are already properly marked

- docs/changelog.txt
- library/modules/Screen.cpp
so you can, for example, clear the vanilla selection highlight if you want to draw your own
> allow clearing of map interface layer tiles

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
as a follow-on to #2837
checking this in early in the dev cycle for this release so we have time to discover if it causes any issues with current dialogs.
> make FilteredList searching case insensitive by default

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/buildingplan/itemfilter.cpp
- plugins/buildingplan/itemfilter.h
- plugins/lua/buildingplan.lua
- plugins/lua/overlay.lua
#2883 
Fixes #2418
Implements:
- prevent planned buildings from being resumed (note this only prevents unsuspending from the building sheet panel, not the tasks screen)
- orders buckets by "pickiness"
- only choose reachable items for jobs
- IN_PLAY vector scanned last so more specific vectors (which are more likely to get hits) are scanned first
> [buildingplan] next steps

- plugins/lua/buildingplan.lua
so they can be multi-built like all other buildings (the vanilla ui was handling the build and then exiting out of the build menu)
Fixes #2984
> build zero-item buildings with buildingplan

- plugins/overlay.cpp
overlays can prevent clicks from being handled by DF. likewise, vanilla modal popups can prevent clicks from getting handled by DFHack. to prevent a softlock, overlay will skip sending input to the overlay widgets when a modal dialog is visible
Fixes #2985
> don't softlock the game on modal popups

- CMakeLists.txt
- package/windows/CMakeLists.txt
- package/windows/launchdf.c
required for the steam distribution, which needs an exe to launch when the player runs the DFHack "game" from the steam client. we can't just point it at Dwarf Fortress.exe since the launch exe must be part of the DFHack install package
win32 code provided by ab9rf
> add launchdf binary so steam has an exe to launch

- plugins/lua/buildingplan/planneroverlay.lua
Fixes #3000
- attaches correct number of mechanisms for pressure plates according to their configuration
- dynamically shows required number of mechanisms as the config changes
- copies config to planned building so it doesn't get lost
> [buildingplan] fix handling of pressure plates

- plugins/stockpiles/OrganicMatLookup.cpp
- plugins/stockpiles/OrganicMatLookup.h
- plugins/stockpiles/StockpileSerializer.cpp
- plugins/stockpiles/StockpileSerializer.h
- plugins/stockpiles/StockpileUtils.h
- plugins/stockpiles/stockpiles.cpp
Moves `stockpiles` to the core logging system, cleans up code
Fixes #2977
> cleanup stockpiles plugin and don't bork on empty type vectors

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/plannedbuilding.cpp
- plugins/lua/buildingplan/planneroverlay.lua
since it's just not working right.
it appears to be matching the heat safety of the *item* rather than of the *material*, leading it to ignore items with materials that *would* be heat safe once they are built into buildings.
> [buildingplan] comment out heat safety feature

- plugins/lua/buildingplan/pens.lua
- plugins/lua/buildingplan/planneroverlay.lua
iteration on #3022, based on designs by @TaxiService 
unhovered:
hovered:
> [buildingplan] better minimize widget for the planner panel

- docs/plugins/reveal.rst
- plugins/reveal.cpp
makes it more user friendly and reduces chance of mishap by placing the cursor in an unforgiving location (like in a closed cavity)
Fixes #2962
> [reveal] anchor revflood at a unit's position

- data/init/dfhack.keybindings.init
- data/init/dfhack.tools.init
- docs/about/Removed.rst
Should not be merged until after https://github.com/DFHack/scripts/pull/643
Creates an `alias` for `gui/dig` -> `gui/design` to preserve existing custom user hotkeys.
> Add default keybinding an alias for gui/design

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/itemfilter.cpp
- plugins/buildingplan/itemfilter.h
member field was passed by value instead of reference, causing the deserialized state to just be lost to the aether instead of remembered in the ItemFilter
Fixes #3044 
Fixes #3065
> [buildingplan] actually record the deserialized material mask val

- data/init/dfhack.tools.init
- docs/about/Removed.rst
- docs/changelog.txt
- library/Core.cpp
- library/include/Core.h
adds alias for `autounsuspend` -> `suspendmanager` and adds alias resolving capability to the `enable` and `disable` commands
Fixes #2955 
Fixes #2979
> turn down autounsuspend gracefully

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/lua/buildingplan/planneroverlay.lua
up and down stairs were using their own (empty) filters. all stairs are configured as a single "type" in the UI.
also change existing tile shape detection to take carved stairs into account
Fixes #3066
> [buildingplan] normalize stairs so they all use the same filter

- docs/Core.rst
- docs/changelog.txt
- docs/guides/modding-guide.rst
- library/Core.cpp
- library/include/Core.h
- library/lua/helpdb.lua
- plugins/lua/overlay.lua
scripts in downloaded mods are now automatically added to the DFHack script path. DFHack recognizes two directories in a mod's folder: `scripts_modinstalled/` and `scripts_modactive/`. `scripts_modinstalled/` folders will always be added to the script path, regardless of whether the mod is active in a world. `scripts_modactive/` folders will only be added to the script path when the mod is active in the current loaded world.
Fixes #2667
side note: if a mod adds a script in its `scripts_modactive` folder, and that script attaches itself to `dfhack.onStateChange`, then the script must remove its handler when a world is unloaded or else risk being called in a world where the mod is not active.
docs: 
Script directories in installed mods are automatically added to the script path
according to …
> support scripts in mods

- docs/changelog.txt
- plugins/tailor.cpp
I significantly restructured the assignment algorithm to eliminate the overproduction issues in #3093
#3103 is addressed by excluding units that don't have the caste-level EQUIPS flag
closes #3093
closes #3103
> tailor: fix #3093, #3103

- docs/changelog.txt
- docs/plugins/buildingplan.rst
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/lua/buildingplan.lua
if `suspendmanager` is running, then planned buildings will be left suspended when their items are all attached. `suspendmanager` will unsuspsend them for construction when it is safe to do so.
Fixes #3052
> [buildingplan] suspendmanager integration

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- fix bug in Label where it was sending itself to a callback (because it was calling with `:` instead of `.`)
- fix bug in CycleHotkeyLabel where it was interpreting an option value as a pen -- no more rainbow weapon selection in buildingplan : (
- add ability to CycleHotkeyLabel to have dynamic option labels and pens
> [widgets] fix and extend Labels/CycleHotkeyLabels

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/defaultitemfilters.cpp
- plugins/buildingplan/defaultitemfilters.h
- plugins/lua/buildingplan/itemselection.lua
- plugins/lua/buildingplan/planneroverlay.lua
- additional choice for item selection: use last material
- if a material has been selected before and there is enough of that material available to fulfill the build requirements, select it and don't even open the item selection dialog
- if there are not enough of the last selected material available, pre-select as much as there is and open the dialog to get the remaining choices
Fixes #3042
> [buildingplan] implement automaterial selection

- docs/changelog.txt
- package/windows/launchdf.c
this version launches dwarf fortress via the steam client instead of launching it directly
the existing one doesn't set up the steam app context which means access  to DF's steam workshop is broken. launching through the steam client avoids this issue.
> update steam launcher

- docs/changelog.txt
- library/modules/Items.cpp
this seems to fix the issue in which some quality levels were displayed with incorrect characters in some DFHack windows, namely:
`@` instead of `☼`
`=` instead of `≡`
`<>` instead of `«»`
> fix masterwork/exceptional/decorated symbols

- docs/changelog.txt
- plugins/lua/hotkeys.lua
adjustment needed for new double-wide scrollbars
Fixes #3146
> [hotkeys] adjust text margin in popup menu for wide scrollbar

- library/modules/Items.cpp
following a suggestion by Quietust https://github.com/DFHack/dfhack/pull/3137#issuecomment-1493439012
this removes those consts introduced in #3137 
...in theory we could add `'\xAE'` and `'\xAF'` at the end of `quality_table[]`, and then say like:
```tmp = 'quality_table[6]' + tmp + 'quality_table[7]';``` or something... but uggghhhh 🙄
> clean up Items.cpp quality symbols definitions

- docs/Core.rst
- docs/changelog.txt
- docs/guides/modding-guide.rst
- library/Core.cpp
- library/LuaApi.cpp
- library/lua/script-manager.lua
and update docs and modding guide. Also fix a behavior discrepancy for `dfhack.filesystem.listdir_recursive` where the list of files couldn't be accessed if you specified a recursive depth less than the full depth of the tree.
Fixes #3141
Fixes #3113
> read mods from all mod dirs and only use most recent versions

- package/windows/launchdf.c
if it's native windows, launches by finding Steam in the registry and running Steam.exe
if it's wine, launches by discovering `steam` in the path and running the native client that way
if the chosen path above fails, launches the `Dwarf Fortress.exe` file in the current dir
> allow launching DF to work under wine

- docs/changelog.txt
- plugins/prospector.cpp
toady shifted displayed z levels by 100 for v50
closes #3187
> add raw/cooked z level output to prospector

- docs/changelog.txt
- library/CMakeLists.txt
- library/Core.cpp
- library/include/modules/DFSteam.h
- library/modules/DFSteam.cpp
- Finds and loads Steam lib
- initializes Steam lib (since we need it before DF initializes it itself)
- discovers the SteamDeck detection function
- calls it just before we process dfhack.init
- if we're on steam deck, hide the console window
I'm not entirely happy with having to initialize the steam lib. it's now being initialized twice, which might leak memory, but it doesn't appear to cause any real problems.
This is something we might be able to avoid once we move to the dfhooks api, since we'll be initialized later in the loading process.
Fixes #3182
> hide terminal console when running on steam deck

- docs/Installing.rst
- docs/changelog.txt
This removes the sections for other platforms. I'll include a link to this commit in an issue so we can find it and retrieve some of the text when it comes time to support linux and osx again.
Fixes #3208 
Edit: direct link to rendered page from this PR: https://dfhack--3209.org.readthedocs.build/en/3209/docs/Installing.html#installing
> update Installing docs for Steam

- docs/changelog.txt
- plugins/lua/stockpiles.lua
- plugins/stockpiles/StockpileSerializer.cpp
it turns out that the builtin number of gems isn't constant across worlds. 
Fixes #3204
> [stockpiles] fix index out of bounds error when reading gems

- library/Core.cpp
avoid reading `cur_savegame.save_dir` during state change events outside of a loaded world
> don't read cur_savegame.save_dir when invalid

- docs/Tags.rst
- docs/changelog.txt
- library/lua/dfhack.lua
- library/lua/helpdb.lua
- plugins/hotkeys.cpp
- plugins/lua/hotkeys.lua
Fixes #3206
also removes "unavailable" tools from `ls` and `tags` output unless they are specifically requested
> infrastructure for hiding armok tools

- docs/changelog.txt
- library/Core.cpp
- library/DFHackVersion.cpp
- library/include/DFHackVersion.h
- library/modules/Gui.cpp
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
replaces the `title-version` plugin
I changed the formatting a little to make it more compact:
Fixes #3290 
edit: After feedback from @TaxiService, I moved the version string to the top, next to the DFHack logo:
Also, prevented both the logo and the version string from appearing on any title screen subscreens to avoid conflicting with vanilla widgets
> add DFHack title version overlay

- docs/changelog.txt
- plugins/autoclothing.cpp
This is a fix of least effort. I did not investigate whether the messages are an indicator of a deeper problem.
@ab9rf could you verify that this fixes the lag on the fort where you saw the problem?
Fixes #3259
> [autoclothing] demote chatty WARN messages to DEBUG

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/buildingplan_cycle.cpp
before we only checked when doing the cycle, so if an inaccessible item were manually selected, we'd never be able to build
Fixes #3318
> [buildingplan] check items for accessibility for dialogs

- docs/changelog.txt
- plugins/lua/overlay.lua
- plugins/overlay.cpp
Fixes #3335
issue was that we weren't passing the viewscreen through to the `dfhack.gui.getFocusStrings()` function so it was using the top viewscreen instead of the one we were interposing
> [hotkeys] fix logo disappearing when hovered on title screen

- docs/changelog.txt
- library/Console-windows.cpp
- library/Core.cpp
This PR prevents the DFHack console from coming up momentarily, even if it is configured to be hidden on startup. This was causing fullscreen DF to go into hiding on startup.
This PR also removes the check for Steam Deck, since it is now redundant.
> fix fullscreen DF minimizing on startup

- CMakeLists.txt
`find_package(Python)`'s default behavior is to attempt to use any `python3.x` executables it finds before `python3`. This is problematic when using tools such as pyenv, where `python3.x` executables may be present in a user's PATH but not be functional.
Setting the `Python_FIND_UNVERSIONED_NAMES` hint to `FIRST` causes `python3` to be attempted first, if it exists.
Note that this option was introduced in CMake 3.20: https://cmake.org/cmake/help/latest/module/FindPython.html#hints
> CMake: fix find_package(Python) when inactive pyenv Python installations are present

- docs/Core.rst
- docs/changelog.txt
- library/Core.cpp
- library/Hooks.cpp
- library/include/Core.h
As requested by at least two different streamers.
This PR recognizes `--disable-dfhack` on the DF commandline and stubs out all our hooks if the flag is detected.
df::globals initialization moves to the `dfhooks_init` call in the main thread to support reading the commandline.
if the DF version is not matched in symbols.xml, the error response is exactly the same as it was before.
in order to keep the logic from changing too much, I also moved stderr/stdout redirection to the new main thread init function. this means DFHack will still have a *little* effect on the game when it is disabled, but I think this is acceptable (though always open for discussion).
Fixes #3198
> support disabling DFHack with --disable-dfhack

- .github/workflows/clean-cache.yml
trying to ensure our caches associated with release builds (I'm looking at you, Steam SDK) don't get prematurely deleted if we have a lot of PR activity
taken almost verbatim from https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
> add github action to clean up PR caches after merge

- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
Standardizing tab selection seems like a good idea. This had been enforced only through code review, but now we have proper defaults. This pairs with DFHack/scripts#622 where the only users of TabBar migrate to the widgets library version. Both users previously also used Ctrl-T as the "next tab" key.
> give widgets.TabBar default hotkeys

- .github/workflows/build.yml
- .github/workflows/steam.yml
- package/windows/CMakeLists.txt
repo secrets can't be accessed from PRs, so no building launchdf.exe in PRs. We can set it up for the steam deploy action, though, where it is truly needed
> retrieve steam SDK from a private repo

- docs/changelog.txt
- plugins/autodump.cpp
note that autodump has an interior check for the cursor when it is actually required, so the player still gets an appropriate error message when the keyboard cursor is needed but not available.
Fixes #3362
> [autodump] remove cursor guard so autodump destroy can work

- docs/changelog.txt
- plugins/remotefortressreader/remotefortressreader.cpp
the `DF2UTF` encoding function was being applied inconsistently. I added it to the places it seemed to be missing.
Fixes #3304
> [RemoteFortressReader] encode transmitted names in utf-8

- library/Core.cpp
- library/include/modules/DFSteam.h
- library/modules/DFSteam.cpp
- package/windows/launchdf.cpp
Except on wine, where `launchdf` can't find the DF process.
Fixes #3333
If the player launches DFHack from the Steam client (windows):
1. launchdf.exe runs
2. launchdf launches Dwarf Fortress (via steam if possible) finds the launched process, and waits for it to exit
3. Dwarf Fortress runs and loads DFHack
4. DFHack recognizes launchdf is already running and doesn't launch it again
5. Player plays DF and eventually exits
6. launchdf exits
If the player launches DF from the Steam client (windows):
1. Dwarf Fortress runs and loads DFHack
2. DFHack recognizes that it was loaded through Steam, and runs launchdf
3. launchdf reloads itself via steam since it wasn't started from the steam client
4. launchdf finds the running Dwarf Fortress process and waits for it to exit
5. Player plays DF and …
> launch DFHack through steam if DF is run from steam

- docs/changelog.txt
- library/lua/json.lua
just act like the file didn't exist (unless strict is set)
Fixes bug brought up on the Steam forums: https://steamcommunity.com/app/2346660/discussions/0/3827540383542758371/
> don't throw if json is unreadable

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
because otherwise it's a pain in the butt to focus another `gui/gm-editor` window without accidentally clicking on (and therefore editing/changing) one of the displayed fields.
> scroll mouse wheel to focus window under cursor

- library/modules/Buildings.cpp
now there *are* no zones in ACTIVITY_ZONES. they're still in ANY_ZONE, though, so we use that instead.
> adjust findCivzonesAt to v50 semantics

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/dfhack.lua
`ensure_key` is handy, but when you have a long chain of keys to dereference, its usage can be unwieldy. `ensure_keys` can take an arbitrary number of keys, similar to the `safe_index` function.
> add ensure_keys utility function

- plugins/faststart.cpp
Just until DF is race-condition-free. prevents crashes for experimental branch users (since `faststart` is on by default)
> [SDL2] temporarily disable faststart

- docs/changelog.txt
- plugins/dig-now.cpp
> [dig-now] clear item occupancy flags for channeled tiles

- docs/changelog.txt
- plugins/remotefortressreader/item_reader.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
Seen on saves shared on Blind discord: Some engraving and statues don't have any image description at all, leading to a null pointer exception when trying to access it in RemoteFortressReader. I was not able to recreate such situation myself, but in game they just don't have any image name or description.
In memory, they show as `null` in various locations. I only located access to these description in RFR, but let me know if there would be other places that could be impacted.
> RemoteFortressReader: Fix a null pointer access on image descriptions

- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/overlay.cpp
This only gets the first character in order to keep the logic simple, but I have yet to find a case where there is more than one character in the buffer (maybe with a system IME?).
If we have to loop, then we have to make multiple calls to `feed`/`onInput`, *without* duplicating mouse clicks or other forms of input. That would get hairy. Let's hope the single character approach is sufficient.
There are no other plugins that currently interpose feed, but if we add any more/add any more back, we need to make sure to add in the `Screen:add_text_keys()` wrapper.
Fixes #3433
Fixes #3471
> [sdl2] ensure we get all string input

- library/modules/Screen.cpp
prints "?" instead of "Question"
prints "U" instead of "Shift + u"
in short; it makes the hotkey hints on our UIs readable again
Before:
After:
> [sdl2] prefer symbols to descriptions for hotkey names

- docs/changelog.txt
- plugins/buildingplan/itemfilter.cpp
artifacts no longer have the artifact quality rating. we need to check for the flag explicitly.
> [buildingplan] don't select artifacts as masterful quality

- data/orders/smelting.json
- docs/changelog.txt
each order takes multiple boulders of cassiterite. increase limits so when all orders are active, cassiterite stores are not depleted
> [orders] increase tin ore count requirements in library orders

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/overlay.cpp
that don't match actual SDL string input. this prevents, say `a` from appearing after you type `A` and release shift before you release the "a" key
Fixes #3525
> filter out spurious STRING keybindings

- library/include/Core.h
this resolve an error that arises when compiling with msvc 1936 which was previously ignored due a combination of a bug in the compiler and not being on C++20 compliance (which is stricter in this area than previous standards)
> fix an ambiguity in def'n of operator==

- docs/Core.rst
- docs/builtins/keybinding.rst
- docs/changelog.txt
- library/Core.cpp
- library/include/Core.h
- library/lua/dfhack.lua
This PR tracks whether a keybinding has been matched and suppresses SDL events related to that key so DF doesn't react to them (or pass them through as text events)
This prevents such inconveniences as:
- Hitting Ctrl-Shift-A to bring up `gui/quickcmd` and having the "Add new command" hotkey immediately trigger because DF generates a `CUSTOM_SHIFT_A` event
- Having hotkeys get added as text in a DF or DFHack text field if one happens to be focused when a DFHack keybinding is pressed
However, it introduces a risk of preventing vanilla keyboard shortcuts from working if a DFHack keybinding is active in the same context. We could just document "don't do this", but solving some players' frustrations may introduce frustrations for others
> suppress SDL events if a DFHack keybinding is matched

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/logistics.cpp
- don't autotrain domestic animals brought by invaders (they'll get attacked by friendly creatures as soon as you let them out of their cage)
- don't bring trade goods to depot if the only caravans present are tribute caravans
> [logistics] fix logic for autotrain and autotrade

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- plugins/lua/zone.lua
to make overlay buttons that don't have a DFHack frame around them more visible
> TextButton widget class

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/lua/dig.lua
- plugins/pathable.cpp
> [dig] add warm/damp highlight overlay for ascii mode

- library/modules/DFSDL.cpp
this avoids tab characters being translated to "?" when converted to cp437
#3523
> convert tabs to spaces when getting clipboard text

- .github/workflows/build.yml
- .github/workflows/steam.yml
- CMakeLists.txt
- package/linux/dfhack
This PR adds a linux build and deploy step to our steam pipeline
it also adds a Linux package build action for PRs to complement the existing MSVC package build action.
question: do we care which gcc version we use to build the distribution packages? the ubuntu image has gcc-11 by default, but we can install and use a different version if we want to. our test actions use gcc-10 and gcc-12.
> deploy linux build to steam

- library/Core.cpp
- library/LuaTools.cpp
- library/lua/argparse.lua
- library/lua/gui.lua
- library/modules/Textures.cpp
Useful for initial research. Can be tested with `DFHACK_NO_GLOBALS=1`
> Fix startup crashes when global addresses are missing

- library/modules/Textures.cpp
In a ASCII-only configuration, I was seeing `textures.raws.size() == 164` and `texpos_end == 164`. This resulted in reading one item past the end of the vector.
This may not be occurring in configurations with graphics enabled, or Windows/WINE may be more permissive.
> Fix off-by-one error in Textures::cleanup()

- library/include/PluginManager.h
Without being declared with `extern "C"`, `plugin_globals` is mangled, with a `cxx11` suffix.
We can't add `extern "C"` to the `DFhackDataExport` macro because GCC does not allow initializing any `extern` variables inline, including `extern "C"`.
> Fix mangling of `plugin_globals` with GCC's C++11 ABI

- ci/check-rpc.py
- plugins/proto/isoworldremote.proto
- plugins/proto/rename.proto
Two fixes here to fix the errors seen in https://github.com/DFHack/dfhack/actions/runs/5758538496/job/15611318369?pr=3622:
* `.proto`s in plugin subdirectories weren't being scanned for docs (broke in #3184 when our tests weren't running), which caused:
```
Missing documentation for plugin proto files: RemoteFortressReader
Add the following lines:
// Plugin: RemoteFortressReader
// RPC GetMaterialList : EmptyMessage -> MaterialList
// RPC GetGrowthList : EmptyMessage -> MaterialList
....
```
Fixed by adding another glob pattern.
* devel/dump-rpc doesn't (and can't) dump RPCs for plugins that aren't loaded, which was causing the check script to fail with:
```
Incorrect documentation for plugin proto files: isoworldremote
The following methods are documented, but the plugin does not provide …
```
> Make check-rpc pass

- CMakeLists.txt
right now we have a bad section ref in our structures changelog. the warnings are being printed to the build output, but the build check workflows are *passing*. This change should surface the failure in our build action checks.
> treat doc warnings as errors

- docs/changelog.txt
- library/LuaWrapper.cpp
This can include DFHack::Error::VTableMissing exceptions if the vtable of a member field is unknown.
Fixes #3627
> df.new(): catch errors thrown by allocate()

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- library/CMakeLists.txt
in prep for a new cross-platform check-type-sizes workflow
> allow the reusable workflows to build xml-dump-type-sizes

- library/DataIdentity.cpp
- library/include/DataIdentity.h
needed because we've discovered that some viewscreens have members that are `std::future`s
> DataIdentity support for `std::future<void>`

- plugins/devel/check-structures-sanity/dispatch.cpp
Also switch to C++20's `string::ends_with()` - need to verify this compiles with MSVC
> check-structures-sanity: also skip temp_save vectors

- docs/changelog.txt
- plugins/lua/hotkeys.lua
since it covers up important vanilla UI elements
> [hotkeys] don't display dfhack logo in legends mode

- docs/changelog.txt
- library/lua/script-manager.lua
setting the script env to nil is not enough; need to completely reload the script
Fixes #3618
> ensure active mod scripts are properly reloaded

- docs/changelog.txt
- plugins/remotefortressreader/proto/RemoteFortressReader.proto
- plugins/remotefortressreader/remotefortressreader.cpp
The current behavior of GetBlockList in the RemoteFortressReader
Protobuf RPC API is to only return blocks that have changed since
the last fetch. This causes problems when the RPC client (i.e. a
world renderer) wants to restart, as it can no longer fetch the
full world state.
This patch adds a `force_reload` option to BlockRequest, defaulting
to `false` (the current behavior). When passed, it returns all
requested blocks regardless of whether they have changed or not.
Tested against the `develop` and `v0.47.05` branches.
Using the `dfhack-remote` JS RPC client:
> Add option to force-fetch world blocks in RemoteFortressReader

- docs/changelog.txt
- library/lua/gui/widgets.lua
feedback was that the red-yellow blocks were confusing
this changes the banner to use red square brackets
Examples:
Prev look for reference:
> [BannerPanel] use square brackets instead of color blocks

- CMakeLists.txt
release notes don't show any changes relevant to our use case and a clean test build with 17.7.0 passed the smoke test
> allow msvc 17.7.0 (1937) for builds

- library/LuaTypes.cpp
- test/structures/find.lua
- test/structures/globals.lua
Also added a test. Probably minor enough to skip the changelog.
> Fix crash in df.global:_field() when global address is unknown

- data/init/dfhack.keybindings.init
- docs/changelog.txt
- library/Core.cpp
- library/modules/Screen.cpp
don't suppress SDL key events when modifier keys are used. this allows hotkeys to be successfully processed even if a keybinding "steals" it. plain text keys that match a hotkey are still suppressed (controllable via a DFHack preference setting)
also:
- fix keybinding scope of `spotclean` to just be `dwarfmode`
- don't synthesize text entry events when Ctrl- or Alt- is held down
> Refine keyboard input handing

- library/include/DataDefs.h
> Add struct_field_info_extra::original_name field for globals

- docs/dev/Lua API.rst
- library/LuaTypes.cpp
- library/LuaWrapper.cpp
- test/structures/struct_fields.lua
> Expose struct_field_info to Lua

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/github-release.yml
- .github/workflows/steam-deploy.yml
- .github/workflows/test.yml
upload-artifact and download-artifact are very slow (O(minutes)) for artifacts with many small files. This is likely to be resolved when the v4 release of the artifact actions comes out (see https://github.com/actions/toolkit/tree/main/packages/artifact), but for now we need an interim solution that doesn't waste our time.
This PR compresses our artifacts with `tar` before upload and decompresses them as necessary when they are used by other workflow actions. This speeds the builds up by several minutes each (generally going from ~150s to ~3s).
One side effect of this PR is that the "release" packages are now tar.bzip2 files wrapped in .zip files. This makes them less useful as a method for players to get the latest dev release. We could add logic to the package.yml file (and lower-level …
> archive artifacts before upload

- docs/changelog.txt
- plugins/tailor.cpp
clothing items may have an invalid maker race; this should not happen but it does so we have to deal with it
fixes #3685
> `tailor`: remove crash

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Screen.h
- library/lua/gui.lua
- library/modules/Gui.cpp
- library/modules/Screen.cpp
this appears to be an oversight from when we introduced those API methods
> pass getAnyStockpile and getAnyCivZone through ZScreens

- docs/guides/quickfort-user-guide.rst
in support of ongoing `gui/quantum` work
> update quickfort user guide for new take_from semantics

- docs/changelog.txt
- plugins/seedwatch.cpp
> seedwatch: ignore tree seeds

- docs/about/Authors.rst
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/LuaTools.h
- library/include/modules/DFSDL.h
- library/include/modules/Textures.h
- library/modules/DFSDL.cpp
- library/modules/Textures.cpp
This PR add ability to generate and delete textures dynamicaly.
New methods:
- **createTile**
Create single texture with w/h in pixels from given pixels array. Register it in `texture.raws` and return `TexposHandle`.
```cpp
TexposHandle Textures::createTile(std::vector<uint32_t>& pixels, int tile_px_w, int tile_px_h)
```
```lua
dfhack.textures.createTile(pixels: integer[], tile_px_w: integer, tile_px_h: integer)
```
- **createTileset**
Create one texture with texture w/h in pixels from given pixels array. Slice it on array of tiles wih given w/h in pixels, register those tiles in `texture.raws` and return array of `TexposHandle`.
```cpp
std::vector<TexposHandle> Textures::createTileset(std::vector<uint32_t>& pixels, int texture_px_w,
int texture_px_h, int tile_px_w, int tile_px_h)
``` …
> create and delete textures

- CMakeLists.txt
-g is already in the flags, we just end up adding it a second time
> remove unneeded modification of CMAKE_CXX_FLAGS_RELWITHDEBINFO

- library/modules/Job.cpp
- test/modules/job.lua
GCC appears to be optimizing the call to `cancel_job()` to use the stub in *DFHack's* job_handler vtable, which is a no-op. Lua was unaffected because it invokes vmethods through method pointers (without knowing the target instance at compile time), so use a similar approach here for now.
As mentioned by @ab9rf on Discord, we should pursue an alternative like asking Bay12 to expose the relevant code through a global `std::function` instead of a vmethod.
> Hack to force GCC to invoke cancel_job() through DF's vtable

- library/lua/gui.lua
- library/modules/Textures.cpp
and clean up unused function parameters in the gui Lua module
> [Textures] instrument textures module

- plugins/tailor.cpp
so dwarf and item names and item descriptions are printed correctly
probably only an issue on Linux since DF2CONSOLE is a noop on Windows
> [tailor] fix status output character encoding

- plugins/lua/sort.lua
- plugins/lua/zone.lua
add filters for
- units in other squads
- appointed officials
- nobility
also
- add same spacebar semantics as `gui/launcher` so double space can pause/unpause the game
- fix migrant wave sorting so it goes by active vector index instead of unit id
- split out leadership skills into separate sorts (you want teachers in different situations from when you want military tacticians)
> [sort] implement suggestions from squad assignment screen feedback

- plugins/lua/hotkeys.lua
so the textures don't visibly flicker
revert this once textures are flicker free
#3709
> [hotkeys] hide the DFHack logo while loading a game

- build/build-win64-from-linux.sh
it wasn't causing any errors, but it was also clearly leftover from a previous commandline
> unclutter build command

- docs/changelog.txt
- plugins/lua/autobutcher.lua
> [autobutcher] fix handling of ticks parameter

- docs/changelog.txt
- library/lua/gui/dialogs.lua
> [dialogs.MessageBox] fix spacing around text when a scrollbar is involved

- docs/changelog.txt
- library/include/modules/Job.h
- library/modules/Job.cpp
- library/modules/Materials.cpp
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/buildingplan/plannedbuilding.cpp
- plugins/lua/buildingplan/planneroverlay.lua
It turns out the problem was *not* with item heat safety not being transferable to building heat safety. That was never true. The problem was that our job item flag matcher matches the logic of the vanilla matcher, and many item types, including screw pump components, are not checked for heat safety. therefore, no enormous corkscrews would ever match the filter if the heat safety filter was on.
I didn't want to change the function that mirrors vanilla logic, so I added heat safety detection in buildingplan logic itself.
Fixes #3692
> [buildingplan] fix and reinstate heat safety filter

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
the reinstated the heat safety filter unintentionally covered the dimensions readout widget, which had moved to the same screen space in the time that the heat safety filter was hidden.
this PR moves the dimension readout into the upper panel where there is free space
> [buildingplan] move the dimensions readout out from under the heat safety filter

- docs/changelog.txt
- plugins/seedwatch.cpp
reported on Bay 12 forums: http://www.bay12forums.com/smf/index.php?topic=164123.msg8499609#msg8499609
seedwatch crashes when reading config data with invalid seed ids. the very first v50 seedwatch plugin did not record the seed id properly, and unlucky players who happened to use that version to save their game run into this crash.
> [seedwatch] fix crash on bad seed ids in configs

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/argparse.lua
Implementing a boolean parser function for `argparse`
Accepts a "truthy" value like "yes" , "no",  "true", etc. and converts it to a lua boolean value. Throws an appropriate error should the value not be accepted.
Was discussing this on discord and thought it might be simple but useful addition to `argparse.`
(still needs docs update and likely further improvements)
> Add `boolean` function for argparse

- docs/changelog.txt
- docs/plugins/dig.rst
- library/include/modules/Maps.h
- plugins/lua/dig.lua
- plugins/pathable.cpp
graphics: 
new ascii highlights:
> [dig] add ASCII-mode highlight for smoothing and carving designations

- docs/changelog.txt
- library/modules/Gui.cpp
so the mod manager overlay doesn't continue to get displayed even after the progress bar has come up and the world is being generated
> [Gui] differentiate the new region loading screen in the focus string

- plugins/pathable.cpp
vanilla handles blinking for fortifications, engraving, and carving tracks when the jobs for those tasks are staffed. let vanilla do its thing when it's doing a thing. we'll just blink when vanilla doesn't
> [pathable] let vanilla blinking take over when possible

- .github/workflows/build-linux.yml
now that the windows and linux structures are aligned again
don't merge this, of course, until the previous statement is true.
> revert the temporary linux structures override

- library/Core.cpp
- library/include/modules/DFSDL.h
- library/modules/DFSDL.cpp
This allows the message to be displayed consistently in a dialog on all platforms.
> Use SDL_ShowSimpleMessageBox in Core::fatal()

- plugins/remotefortressreader/remotefortressreader.cpp
Fixed a potential build issue on some platforms on C++20 where `<cmath>` was getting shadow-included and causing a naming conflict with `lerp` due to the existence of `std::lerp` (#3795). Solution: `using namespace std;` was removed, and all instances of using `std` elements (in this case, `vector`, `map` and `string`) were changed to have the `std::` prefix (`std::vector`, `std::map`, `std::string`). As we are no longer using `std` namespace, the compiler can unambiguously know which `lerp` function we are referring to.
> Fix lerp() name conflict on Windows

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/dig.cpp
The current behaviour of `digtype` designates all tiles on the map of the same type, regardless of visibility. The player might not want to have the locations of all the veins revealed to them, so designating visible veins of that type as "auto-dig" is probably more desirable and useful behaviour for players. I also took the liberty of adding a new option `+z` to this command which is analogous to the existing `-z` option but to only dig layers above. (Hence, the player can combine the two to only dig at the same z-level as the cursor).
Note that for designations other than the default we can't set them to autodig, it simply does not work. So the dig_auto flag is only set if the designation is default.
> Adjusted behaviour of "digtype" to only designate non-hidden squares, and designate them as auto-dig

- docs/changelog.txt
- plugins/autolabor/autolabor.cpp
make sure autolabor resets the work detail bypass flag whenever autolabor is unloaded for _any_ reason
i tested `disable autolabor`, `unload autolabor`, and unloading a fort with autolabor enabled; in all cases the work detail bypass flag was cleared as desired
closes #3812
> autolabor: fix #3812

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaTools.cpp
- library/lua/gui.lua
- library/lua/gui/dialogs.lua
- library/lua/gui/widgets.lua
- library/modules/Screen.cpp
- plugins/lua/buildingplan/inspectoroverlay.lua
- plugins/lua/buildingplan/itemselection.lua
- plugins/lua/buildingplan/planneroverlay.lua
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
- plugins/lua/sort.lua
- plugins/lua/zone.lua
- test/library/gui/widgets.EditField.lua
- test/library/gui/widgets.Scrollbar.lua
- test/library/gui/widgets.lua
we had the meanings backwards for _MOUSE_L vs _MOUSE_L_DOWN (and similarly for right and middle buttons).
now that the semantics are aligned with DF behavior, we can usefully share mouse state with vanilla widgets, which is important for the upcoming `startdwarf` overlay, which adds a draggable scrollbar to a vanilla viewscreen.
> align mouse button semantics to DF

- .github/workflows/test.yml
- ci/download-df.sh
- ci/run-tests.py
- ci/test.lua
- test/plugins/orders.lua
significant changes:
- tests on linux are enabled
- fortress mode tests are enabled
- test harness code is changed to wait for a number of ms instead of a number of frames
- tests don't start until DF initial prep is complete
- crashing tests are marked as failed and skipped instead of retried
> enable fortress mode tests in CI

- docs/changelog.txt
- plugins/lua/hotkeys.lua
other options (first one is existing style):
> [hotkeys] make the ascii DFHack logo easier to read

- ci/test.lua
- docs/dev/Lua API.rst
- library/include/modules/Screen.h
- library/lua/gui.lua
- library/lua/gui/dialogs.lua
- library/modules/Screen.cpp
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
- plugins/overlay.cpp
Thank you @lethosor for [bringing this up](https://github.com/DFHack/dfhack/commit/cd12e41fd7aa7d7a52c9e9cab97d89273bef0764#r128858036). so much hackery could be removed.
> centralize management of mouse state

- plugins/strangemood.cpp
`wait_timer` is not really there; what we have labeled as `wait_timer` is actually padding so there is no need to do this and as this references a field that doesn't exist having the reference is blocking updating the structures definition for `job`
> remove refrence to unused field

- docs/changelog.txt
- docs/plugins/logistics.rst
- docs/plugins/stockpiles.rst
- plugins/logistics.cpp
- plugins/lua/logistics.lua
- plugins/lua/stockpiles.lua
- add persisted config elements per stockpile\
- add CLI support
- add GUI elements for setting option from `stockpiles` overlay
- add button to stockpiles overlay for showing help
> [logistics] support optionally melting masterworks

- library/lua/gui/widgets.lua
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/creatures.lua
adds a simple search widget to the unit list pages under the vanilla Info panel
The search field keeps separate search strings for each panel, and keeps the state as long as the info panel is open. If the player closes the info panel, then widget state is cleared.
> search overlay for CREATURES info panels

- docs/changelog.txt
- docs/plugins/orders.rst
- plugins/lua/orders.lua
- plugins/orders.cpp
it is not useful to reset orders that do not have item conditions
also rearrange the overlay buttons a little to be more compact
> [orders] only recheck orders that have conditions

- docs/changelog.txt
- plugins/lua/zone.lua
don't display our button if the building is part of a dungeon
> [zone] dungeon cages/restraints aren't assignable

- docs/changelog.txt
- plugins/lua/dwarfvet.lua
Fixes https://github.com/DFHack/dfhack/issues/3876
also removes reference to non-existent `wait_timer` field
tested on real injured animals. jobs look good, hospital visit was successful.
> [dwarfvet] properly initialize job id when linking into world

- docs/plugins/sort.rst
- plugins/lua/sort/locationselector.lua
by default, already-established temples and guildhalls are filtered out of the list
> [sort] add filter for established location types

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
since the items may have changed
Fixes https://github.com/DFHack/dfhack/issues/3539
> [buildingplan] refresh the overlay state when toggling minimize

- library/lua/gui/buildings.lua
- library/lua/gui/dialogs.lua
- library/lua/gui/materials.lua
that is, don't let clicks and keys propagate to parent screens
ref: https://github.com/DFHack/dfhack/pull/3841
> ensure modal dialogs behave like modal dialogs

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
just like we display how many you'd need to make if you don't have enough
Fixes https://github.com/DFHack/dfhack/issues/3903
> [buildingplan] display how many items are available on the planner panel

- docs/changelog.txt
- plugins/lua/stockpiles.lua
I missed assigning the `visible` condition property when I added these in the last version
> [stockpiles] hide help and configure buttons when panel is minimized

- docs/changelog.txt
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
- plugins/lua/sort/slab.lua
- plugins/lua/sort/sortoverlay.lua
- plugins/lua/sort/unitselector.lua
so all pages have the same search capabilities
also make sure the stress faces are reloaded properly when reinitializing the sort overlays while doing development
> [sort] unify unit search key logic

- docs/changelog.txt
- docs/plugins/prospector.rst
- plugins/prospector.cpp
needed only light modification to adjust to cross-region embarks
> [prospect] reinstate embark screen estimates

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/modules/Gui.cpp
take advantage of the tile highlight mechanism that vanilla uses when zooming to a unit/item
> [Gui::revealInDwarfmodeMap] optionally highlight the zoom target tile

- docs/changelog.txt
- library/modules/Items.cpp
> adjust price of vermin swarms

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
it wasn't obvious whether you needed to modify the "top" or the "bottom" stair config when building a single level of stairs. now a separate, more clearly labeled option appears when there is only one level of stairs to build
also moved the options to the left so they don't overwrite the dimensions label
> [buildingplan] improve interface for single-tile stairs

- docs/changelog.txt
- library/modules/Units.cpp
as was originally intended. At the time, I didn't realize that TranslateName did the English translation by default
> return untranslated name as the readable name

- docs/changelog.txt
- plugins/lua/sort.lua
on the squad assignment screen, make effectiveness and potential ratings use the same scale so effectiveness is always less than or equal to potential for a unit and so you can tell when units are approaching their maximum potential
the potential formulas now use the same weights and standard deviations (for coloring) as the corresponding effectiveness ratings. Legendary+5 skill is used for "skill" values in the "potential" formula.
@Halifay
> [sort] squad panel: normalize effectiveness and potential rating scales

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/modules/Gui.cpp
this is needed for the new `gui/design` dimensions tooltip overlay, which needs to display near the cursor even when the cursor is in the blank buffer around the outside of the playable map area.
> [Gui] allow getMousePos to return out of bounds coordinates

- plugins/devel/check-structures-sanity/check-structures-sanity.h
- plugins/devel/check-structures-sanity/dispatch.cpp
- plugins/devel/check-structures-sanity/main.cpp
and adjust bool check accordingly
> check-structures-sanity: Allow running without MALLOC_PERTURB_

- docs/changelog.txt
- library/modules/Gui.cpp
When building type is trap, add the trap type to the focus string:
> Add trap type to focus string

- docs/changelog.txt
- plugins/lua/buildingplan/filterselection.lua
Changed buildingplan filterselection hotkey for reseting the filter to ctrl-x (from shift-x which conflicted with increasing the minimum quality). Fixes #3978
> Fix #3978 buildingplan filter editor hotkey conflict

- docs/dev/Lua API.rst
- library/LuaTypes.cpp
Looks like `ref.field(name)` was not documented properly.
```cpp
static int meta_struct_field_reference(lua_State *state)
{
if (lua_gettop(state) != 2)
luaL_error(state, "Usage: object._field(name)");
```
Both the struct and container versions require `self` (in Lua terms). Running either with the provided syntax results in an error prompting `Usage: object._field(index)` which is also incorrect.
> Fix incorrect object:_field() usage docs

- docs/changelog.txt
- plugins/lua/buildingplan/filterselection.lua
- plugins/lua/buildingplan/planneroverlay.lua
Due to ctrl-x conflicting with field entry clearing.
> Adjusted `buildingplan` filter reset hotkey to ctrl-d 'delete'

- docs/changelog.txt
- plugins/tailor.cpp
this simplifies the ordering logic by checking available stock _after_ deciding if a item is needed, rather than _before_
the old logic was failing to check for available replacement stock in some cases, resulting in overordering
should close #4038
> tailor: reshuffled logic

- docs/changelog.txt
- plugins/lua/buildingplan/mechanisms.lua
Fixes https://github.com/DFHack/dfhack/issues/4037
sort by heat safety so mechanisms of the least appropriate heat safety are used first, saving the magma-safe mechanisms for when they are needed
filter out unreachable mechanisms
item_id -1 => item_id or -1
that is, we wanted to default to -1, not subtract 1 from the item_id
> [buildingplan] choose mechanism improvements

- library/RemoteServer.cpp
> RemoteServer: reset fail counter after success

- library/RemoteServer.cpp
Also makes sure the socket is blocking to avoid EWOULDBLOCK errors.
Fix #4040, not sure if it fixes #3498 though. I'm still not sure what was the bug.
> Improve Accept error handling in RemoteServer

- docs/changelog.txt
- plugins/lua/sort/info.lua
i.e. don't access deleted memory and crash
Fixes https://github.com/DFHack/dfhack/issues/4062
> [sort] handle case where jobs are manually removed from the tasks screen

- library/DataIdentity.cpp
- library/include/DataIdentity.h
I plan to merge this expediently to unbreak the build, but post-merge review would be welcome
> add identity for variant

- library/DataIdentity.cpp
- library/include/DataIdentity.h
this is arguably a better approach for the change in #4090
> data identity changes for stl-variant in 50.12

- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
- plugins/lua/autobutcher.lua
- remove ticks config (this does not benefit the user and clutters the API)
- document "now" command (was already implemented, but not documented)
- run cycle on autowatch enable (so new races appear immediately)
- remove references to unavailable tools in docs
just small things found while prepping for https://github.com/DFHack/dfhack/issues/4004
> [autobutcher] small edits

- docs/changelog.txt
- docs/guides/modding-guide.rst
Fixes https://github.com/DFHack/dfhack/issues/3839
> [modding-guide] add example for blueprint-only mods

- data/init/dfhack.keybindings.init
- docs/changelog.txt
> add keybinding for gui/mass-remove

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/MiscUtils.cpp
- library/include/MiscUtils.h
Add new functions to `MiscUtils.h`.
`random_index` and `vector_get_random` are for getting a random entry from a vector. Common use case  is to fill up a temp vector with possible results (e.g., raws matching conditions) then need to choose one at random.
`capitalize_string_words` and `grab_token_string_pos` are from `g_src/basics.cpp` and have been tidied up to return strings (instead of modifying the existing string in the case of `capitalize_string_words`.)
Moved `random_int` up in `MiscUtils.h` so I could use it in `random_index`. (Trying to implement `random_index` in `MiscUtils.cpp` is a nightmare of cryptic errors related to `#include` that I've given up on.)
> New MiscUtils.h functions: random_index, vector_get_random, capitalize_string_words, grab_token_string_pos

- docs/plugins/fastdwarf.rst
- plugins/fastdwarf.cpp
persist state with fort
add "status" command for printing state, API otherwise unchanged, despite the odd numeric syntax
behavior change: don't teleport if no job or if the destination is in a different pathability group or is on a hidden tile
Fixes: https://github.com/DFHack/dfhack/issues/4141
Fixes: https://github.com/DFHack/dfhack/issues/3998
Fixes: https://github.com/DFHack/dfhack/issues/2660
Fixes: https://github.com/DFHack/dfhack/issues/2623
> [fastdwarf] persist state and refine tele logic

- docs/changelog.txt
- library/lua/gui/dwarfmode.lua
it was just missing. this meant that shift scroll was not being passed through to the map when `pass_movement_keys` was set to true
> include fast z movement as a map movement key

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- plugins/lua/buildingplan/filterselection.lua
- plugins/lua/buildingplan/inspectoroverlay.lua
- plugins/lua/buildingplan/itemselection.lua
- plugins/lua/buildingplan/pens.lua
- plugins/lua/buildingplan/planneroverlay.lua
Productionizes the prototype in https://github.com/DFHack/dfhack/pull/3435
Fixes: https://github.com/DFHack/dfhack/issues/3257
> Add and use Divider widget

- docs/changelog.txt
- library/lua/gui.lua
- plugins/lua/buildingplan/filterselection.lua
- plugins/lua/buildingplan/inspectoroverlay.lua
- plugins/lua/buildingplan/itemselection.lua
- plugins/lua/buildingplan/pens.lua
- plugins/lua/buildingplan/planneroverlay.lua
by 'divider' i mean one of these horizontal or vertical lines that visually "divide" a frame.
Previously, these were rendered using a custom function within each script that used a divider.
This PR modifies the way a Panel is rendered, so that to achieve the same effect, you can just make a 1-width or 1-height Panel to get a vertical or horizontal divider respectively.
- `make_frame` - now assigns a name to every tile in a border spritesheet, so we can access T pieces etc.
- `paint_frame` - a Frame with height/width equal to 1 will now render appropriate T-pieces at its extremities, and an horizontal/vertical bar between them. 
It will also draw a cross-piece if both height and width are equal to 1.
(Additionally, logic has been added that disables the `signature_pen` whenever a Panel's …
> UI: "divider" rendering rework

- library/Core.cpp
primary change: load persistence data before doing anything else that might read that persistence data
> lightly clean up event triggering code

- docs/changelog.txt
- plugins/lua/zone.lua
if you remove a zone that has a location attached to it, the backref in the location to the zone is not cleaned up. don't count those dangling refs when determining if the location is still in use.
> [zone] don't count dangling references when retiring zones

- docs/changelog.txt
- plugins/buildingplan/plannedbuilding.cpp
this has been irking me forever. the fix was stupid simple.
PlannedBuilding state was subtly different depending on whether the state was created in this game session or loaded from disk. The difference was that one had a non-empty "specials" list, but the length of the string in that list was 0, so it was never obvious from the debug output what was going on. The fix is to not add a special entry if the input string is 0 length.
Fixes: https://github.com/DFHack/dfhack/issues/4188
> [buildingplan] fix planned buildings getting bumped to the front of the line on load

- docs/changelog.txt
- library/modules/Constructions.cpp
fixes `gui/mass-remove` designating tops of walls for deconstruction
> don't designate pseudo constructions for removal

- docs/changelog.txt
- plugins/lua/sort/info.lua
- plugins/lua/sort/sortoverlay.lua
prevents a potential crash when DF refreshes the underlying lists and we're still referencing old, deleted data
Fixes: https://github.com/DFHack/dfhack/issues/4218
> [sort] reset state whenever we leave the local info context

- docs/changelog.txt
- plugins/autonestbox.cpp
I'd noticed this in-game before, but the logic error became obvious when I was refactoring the training code
> [autonestbox] don't assign egg layers that might revert to wild

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
so forks still build against DFHack/dfhack/develop instead of their own (likely out of date and tagless) fork of develop
followup to https://github.com/DFHack/dfhack/pull/4232
> use a blank, default ref when pushing to non DFHack repos

- docs/changelog.txt
- plugins/dig-now.cpp
Fixes #4213 by looking for ramps for every designation type and adding the missing diagonal case to clean_ramp() and clean_ramps().
> Make `dig-now` remove ramps for all dig modes.

- library/LuaApi.cpp
- library/Process-darwin.cpp
- library/Process-linux.cpp
- library/Process-windows.cpp
- library/VersionInfoFactory.cpp
- library/include/MemAccess.h
required to load vtables found only in g_src on Linux
Pairs well with https://github.com/DFHack/scripts/pull/965 and https://github.com/DFHack/df-structures/pull/715
> load vtables with library base offsets

- docs/changelog.txt
- docs/plugins/tweak.rst
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/flask-contents.h
Makes flasks, vials, and waterskins display the name of their contents, just like other containers do (e.g. barrels, bins, and cages).
> Add "flask-contents" tweak

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
so widgets don't have to override `render` to control visibility ad hoc
> [overlay] respect active and visible widget attributes

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Units.cpp
fixes issues with warn-stranded and others complaining about units that aren't on the map
> [Units] only include active citizens

- plugins/lua/overlay.lua
To use:
when you're ready to begin measurement, run:
`:lua require('plugins.overlay').reset_timers()`
then just let the overlay run. to get the measurements, run:
`:lua require('plugins.overlay').print_timers()`
> [overlay] add perf timers

- docs/changelog.txt
- plugins/autoclothing.cpp
Noticed `autoclothing` was not staying enabled for my fort after saving, quitting, and then reloading. Used tailor.cpp as a reference for the fix.
Tested fix and appears to work.
> Fix Enabled Behavior autoclothing

- docs/changelog.txt
- library/lua/gui.lua
- library/lua/gui/widgets.lua
still works for top-level widgets, of course
> fix getMouseFramePos() for nested widgets

- docs/changelog.txt
- plugins/strangemood.cpp
* Properly recognizes `CUT_STONE` and `CARVE_STONE` as moodable skills
* Moves the Mason's boosted mood chance to the Stone Carver
* Fell/Macabre moods are now selected based on longterm stress instead of current stress
Additionally, some minor structure changes should be made to `df.skills.xml` (which I'm currently not equipped to do myself):
* The professions `STONECUTTER` and `STONE_CARVER` are, indeed, moodable (so the "UNKNOWN" markers can be removed)
* The professions `TAVERN_KEEPER`, `CRIMINAL`, `PEDDLER`, `PROPHET`, `PILGRIM`, `MONK`, and `MESSENGER` are also moodable
> Update strangemood plugin to match 50.11

- docs/changelog.txt
- library/modules/Gui.cpp
so the viewport doesn't just revert back to the previous location immediately after zoom
> [Gui::revealInDwarfmodeMap] unfollow on zoom

- docs/Tags.rst
make the really long ones shorter so they can fit in the new `gui/launcher` UI
> revise tag descriptions

- docs/changelog.txt
- plugins/lua/buildingplan.lua
- plugins/suspendmanager.cpp
Make `buildingplan` properly detect `suspendmanager` and run `suspendmanager` also on initiated jobs. Fixes a regression of the C++ port.
> [suspendmanager] fix buildingplan integration

- docs/changelog.txt
- library/modules/Gui.cpp
fixes hotkey contexts getting mismatched. the first call to matchFocusStrings was against the DF viewscreen, and that was getting cached. later lookups against the top viewscreen (a DFHack window) was reading the DF viewscreen results.
Fixes https://github.com/DFHack/dfhack/issues/4325
> cache focus strings **per viewscreen**

- library/lua/gui/widgets.lua
Use v50.12's `SELECT_ALL` keybinding instead of non-existent `CUSTOM_SHIFT_ENTER`.
> Fix List widget on_submit2

- .github/workflows/package.yml
- .github/workflows/steam-deploy.yml
players can still download them from the readthedocs site
> don't distribute HTML docs

- library/modules/Gui.cpp
viewing items will append an `/Items` suffix on the focus string. viewing linked buildings will append a `/LinkedBuildings` on the focus string
In service of https://github.com/DFHack/scripts/pull/1016
> [Gui] distinguish between linked building view and item view

- docs/changelog.txt
- plugins/autochop.cpp
mushroom trees don't follow the conventions of surface trees. our algorithm worked for surface trees, but severely underestimated the log yield for cavern trees.
now fixed.
> [autochop] correct chop estimate for mushroom trees

- docs/changelog.txt
- library/modules/Gui.cpp
so it doesn't end up as dwarfmode/Default
this stops the `gui/notify` overlay from showing up in arena mode
> [Gui] give non-fortress modes a focus string

- docs/changelog.txt
- plugins/logistics.cpp
unless the stockpile actually accepts those item types
> [logistics] ignore unassociated empty containers on stockpiles

- docs/changelog.txt
- library/lua/gui/widgets.lua
now that we have a shift-enter keybinding, this can work again
> [widgets.EditField] use new Shift-Enter keybinding name for 50.12

- docs/changelog.txt
- docs/plugins/orders.rst
- library/modules/Gui.cpp
- plugins/lua/orders.lua
restores pre-v50 configurability for the labor restrictions in the workshop profile
Fixes: https://github.com/DFHack/dfhack/issues/3449
> [orders] Add labor restrictions overlay for workshops

- docs/changelog.txt
- library/modules/Items.cpp
from testing (see: https://discord.com/channels/793331351645323264/807444467140788254/1218139324818784257 ) items are *not* blindly multiplied both by buy and sell agreements like we previously thought. It receives a maximum of one multiplier.
> [Items] fix trade price when item is in both buy and sell agreements

- docs/changelog.txt
- library/lua/gui.lua
was differentiated when the window was *not* resizable instead of when it *was* resizable
> [gui] fix "resize handle" in ascii mode

- docs/changelog.txt
- library/modules/Gui.cpp
this is a hot spot for performance, and streamlining the string comparisons is important. all library code sends in case-correct strings. 3rd party code *may* need to adjust.
> [Gui] make focus string matching case sensitive

- docs/dev/Lua API.rst
`get_vector` was missing from the struct/class documentation
> Add missing get_vector documentation

- plugins/remotefortressreader/remotefortressreader.cpp
This ends up shadowing a newer function in `<cmath>` that causes compilation errors.
> rename 'lerp' to 'Lerp' in remotefortressreader

- CMakeLists.txt
Since we package this in nixpkgs, we have to resort to horrible hacks to work around the SDL2 downloading. Make this optional and default it to TRUE.
Terrible hack in question: https://github.com/NixOS/nixpkgs/pull/300402/files#diff-0a30597e60bd9d269bd93fdb389f1c898075bf70a4d89fff1a02cb33c570d941R173
Tested:
`cmake -DDOWNLOAD_SDL2=FALSE ..`
`cmake ..`
> Add DOWNLOAD_SDL2 CMake variable (and default to true)

- plugins/lua/buildingplan/unlink_mechanisms.lua
Fix an issue in #4389 where the `Free` button can overlap a DF UI icon if a scrollbar is present. Button is now shifted horizontally based on presence of scrollbar.
> unlink_mechanisms.lua fix button position based on scrollbar

- docs/changelog.txt
- docs/dev/Lua API.rst
Looks like another silently missing function that is exposed to Lua.
> Document enum type next_item function

- CMakeLists.txt
Since systems like nixpkgs change the search path of Dwarf Fortress, we should be able to use the same SDL2 instead of resorting to horrible hacks to work around the file downloading or using mismatched library versions between Dwarf Fortress and dfhack.
> Add USE_SYSTEM_SDL2 CMake option, defaulting to OFF

- library/lua/dfhack.lua
The aim of this PR is to add as much typing to the Lua files as possible, which can then be leveraged in dfhack-lua-annotations directly without needing to manually copy them over.
Right now I covered only the easiest functions to type and only the core dfhack.lua module, but will try to cover more as we get there.
Note these types sometimes rely on annotations that only exist in dfhack-lua-annotations (namely `coord` and `coord_path`) but this has no real impact even if the library is not loaded.
> Add type annotations to Lua library files

- library/lua/class.lua
- library/lua/dfhack.lua
Removes the unnecessary (imo) function declaration in dfhack.lua in favour of an alias and gives the class methods types.
> Use defclass/mkinstance types in dfhack.lua

- library/lua/dfhack.lua
Next round of annotations added to the core dfhack.lua file. Raised questions:
- I'm currently leaning towards abundant usage of `@nodiscard` which will warn users when a function has a return but they have not consumed it. Just something to keep in mind.
- with_finalize and with_onerror use variable arguments when the function they alias/call have known arguments, could be typed better.
- I think we should probably use aliases instead of new functions for the defclass overloads I tried to address this in #4445
> More dfhack.lua annotations

- docs/changelog.txt
- plugins/suspendmanager.cpp
When there is an item on top of a construction that the dwarves can't move, `suspendmanager` would always try to unsuspend it, only for the dwarves to suspend it again. This lead to a cancellation spam and quite a waste of time of dwarves trying to build the same thing again and again.
This change detects items that cannot be moved away, and register it as an "external suspension", so that `suspendmanager` will neither suspend nor unsuspend it while it's in this situation, with a message explaining on the suspended construction.
If an actual deadlock is there, it is not fixed, it will wait suspended for a user action. However, it makes some situations like building a floor on top of its scattered construction material much more efficient, where constructions are unsuspended as soon as …
> [suspendmanager] don't unsuspend constructions blocked by an item

- .github/workflows/package.yml
in prep for automated symbol.xml generation
> make windows/linux builds optional

- docs/changelog.txt
- plugins/suspendmanager.cpp
`suspendmanager` now consider wall being built below. Before, it would sometimes consider that a construction is not at risk of blocking another, since it is not walkable. This would lead it allowing some construction even if they are blocking another, since at the time of the construction the other is unreachable.
It now looks below to consider tiles that are "potentially walkable", to keep access to constructions, even if they are not yet reachable.
Fixes #3600 
Fixes #4466
> suspendmanager: take in account wall plans on the tile below

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- .github/workflows/generate-symbols.yml
- .github/workflows/lint.yml
- .github/workflows/package.yml
- .github/workflows/test.yml
replaces the semi-automated code that isn't flexible enough for the upcoming symbol generation automated workflows
> make target repos in github workflows configurable

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/lua/buildingplan/itemselection.lua
affects all dialogs where item descriptions are shown, such as the trade screens and the output of `item`
@vallode new API alert!
> centralize logic for getting an item description

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/DFSDL.h
- library/modules/DFSDL.cpp
Add dfhack.internal.setClipboardTextCp437Multiline for copying multiline text to the system clipboard
Fixes: https://github.com/DFHack/dfhack/issues/3987
> add multiline clipboard API

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/createitem.cpp
This changes the function signature to return a list of created items via the first parameter and a boolean "success" code. It also moves the "unit" parameter to the beginning and adds "growth_print" to the end (which is required for PLANT_GROWTH items).
Should fix #2063
> Make Items::createItem handle multiple output

- docs/changelog.txt
- plugins/blueprint.cpp
Fixes https://github.com/DFHack/dfhack/issues/4517
> [blueprint] properly distinguish adjacent non-rectangular stockpiles

- docs/guides/quickfort-user-guide.rst
Fixes: https://github.com/DFHack/dfhack/issues/4102
> [quickfort] document in-blueprint comment syntax

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/dig.cpp
- plugins/lua/dig.lua
- refresh count of tiles that will be modified by "mark all designated tiles on this z-level for warm/damp dig" when the z-level changes
- don't affect already-revealed tiles when marking z-level for warm/damp dig
- warm/damp/aquifer status will now be shown when in smoothing/engraving modes
> [dig] warm/damp fixups

- docs/Core.rst
- docs/changelog.txt
- library/modules/DFSteam.cpp
- package/launchdf.cpp
adds `--nowait` option to make the coprocess exit immediately after detecting DF and `--nosteam-dfhack` option for disabling the coprocess entirely.
Fixes https://github.com/DFHack/dfhack/issues/4461
> commandline options for controlling launchdf behavior

- docs/changelog.txt
- plugins/suspendmanager.cpp
In situation like this:
or this:
one tile was left unsuspendended because the dead end suspension routine was stopping at the last one when finding out that there was no exit, but it was not suspending it, leaving one unsuspended tile, which is especially confusing when combined with the "not constructible but accessible" nature of ramp tops. This PR suspend the last tile.
fixes #4558
> suspendmanager: fully suspend unbuildable dead-ends

- library/lua/3rdparty/alt_getopt.lua
Previously the variable was undeclared, but this is dead code anyway I believe the function is unused throughout DFHack.
> Fix optargs typo in get_opts

- library/lua/dfhack.lua
This PR fixes an issue where any file with `_ENV` declared (modules) would lose the majority of typing capabilities by assigning the `_G` type to the return of `mkmodule`. This is not strictly accurate in terms of typing, but it is a significant win for ease of use when developing DFHack modules.
Setting `DEFAULT_NIL` to any prevents warnings from appearing when using it in place of things like tables. I didn't have a better idea for how to type it.
> Fix _ENV typing for mkmodule

- docs/changelog.txt
- plugins/suspendmanager.cpp
#4566 introduced a regression where suspendmanager would suspend single tile stairs with no access around.
This happens because the logic that tries to suspend the whole section when a construction is enclosed was blindly suspending the last checked tile with no exit. This being part of the "dead-end" exploration loop, non-blocking construction where usually filtered out by the previous iteration. But in the case of a single tile situation, it actually never checked that is was a blocking construction before suspending it.
Fixes #4580 
@myk002 I'm making the fix first to ensure it's in for the next release, but that's right, this whole thing is complex enough that it needs non-regression tests, I'll try to get some tests in too in a further PR
> Suspendmanager: fix over-suspending single tile

- docs/dev/Lua API.rst
This PR aims to add missing information about the enum `attrs` field.
Closes #1802
> Add attrs and _attr_entry_type documentation

- docs/changelog.txt
- library/modules/Gui.cpp
useful when examining digging/carving jobs
> allow getAnyJob to return the job under the cursor

- docs/changelog.txt
- docs/plugins/changevein.rst
- plugins/changevein.cpp
Fixes #4519
changevein will now convert any connected veins in the same tile and neighboring tiles.
> Make changevein affect connected veins

- docs/plugins/createitem.rst
- library/modules/Gui.cpp
- library/modules/Units.cpp
- plugins/createitem.cpp
- plugins/dig-now.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/sort.cpp
among other things fixes, the report from Steam where createitem wasn't selecting the adventurer by default (even though the docs say you have to select a unit before use)
Fixes: https://github.com/DFHack/dfhack/issues/4603
> use new lookup for adventurer

- docs/changelog.txt
- library/modules/Gui.cpp
- dwarfmode/CustomStockpile -> dwarfmode/Stockpile/Some/Customize
- dwarfmode/StockpileTools -> dwarfmode/Stockpile/Some/Containers
- dwarfmode/StockpileLink -> dwarfmode/Stockpile/Some/Links
Just a stockpile selected on the map is now dwarfmode/Stockpile/Some/Default
> [Gui] make stockpile focus strings correspond better to UI state

- plugins/suspendmanager.cpp
fixes #4609 
I don't think this needs a changelog entry, because it fixes a partial fix that hasn't been released yet.
> [suspendmanager] fix suspension of dead ends without exit

- library/lua/gui/widgets.lua
Fixes #4621 
Allows for passing in values such as:
```
pens={
{{fg=COLOR_YELLOW, bg=COLOR_LIGHTRED},{fg=COLOR_BLUE, bg=COLOR_DARKGRAY}},
{{fg=COLOR_BLACK, bg=COLOR_LIGHTRED},{fg=COLOR_BLACK, bg=COLOR_LIGHTRED}},
},
```
```
pens={
{{fg=COLOR_YELLOW, bg=COLOR_LIGHTRED},{fg=COLOR_BLUE, bg=COLOR_DARKGRAY}},
{fg=COLOR_BLACK, bg=COLOR_LIGHTRED},
},
```
```
pens={fg=COLOR_BLACK, bg=COLOR_LIGHTRED},
```
> Fix makeButtonLabelText pen tables

- .github/workflows/test-suite.yml
- .github/workflows/test.yml
allowing for quicker turnaround when a test is going to fail
this change splits our "matrix" into separate jobs that can depend on just the dependencies they care about. "matrix" is in quotes since we don't actually use it as a matrix, just a list of collections of parameters.
it's been an annoyance for so long that we have to wait for the Windows build to run the Linux tests. I wonder why I didn't have this idea until now...
> allow linux tests to run as soon as linux build is ready

- docs/changelog.txt
- library/modules/Gui.cpp
Fixed some announcement code that wasn't reverse-iterating vectors to index 0. Better to use index-based for loops instead of iterators for this (as erasing from vectors using the proper `std::reverse_iterator` is a pain.)
> Gui.cpp: Fix skipping index 0 for announcement code

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
convenience method mainly intended for use from Lua, since calling the native DF vmethod from Lua is difficult and nonobvious
> add `Buildings::getName`

- ci/test.lua
- docs/changelog.txt
- docs/dev/Lua API.rst
- library/Core.cpp
- library/lua/dfhack.lua
- library/lua/helpdb.lua
- plugins/lua/hotkeys.lua
also add a helpful helpdb api to facilitate the detection
as reported in [Discord](https://discord.com/channels/793331351645323264/807444467140788254/1246846660106256454)
> prevent armok keybindings from being recognized in mortal mode

- docs/changelog.txt
- plugins/dig.cpp
prevents phantom dig designations from being left behind
Fixes: https://github.com/DFHack/dfhack/issues/4639
> [dig] only propagate autodig to tiles that vanilla doesn't

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/dialogs.lua
like the `gui/confirm` prompt and file deletion confirmations
in preparation for deleting blueprints from the `gui/quickfort` blueprint list
> [dialogs] extend yesno dialog so it can be used for more kinds of confirmations

- docs/Core.rst
- docs/dev/Lua API.rst
- library/Core.cpp
- library/LuaApi.cpp
- library/include/Core.h
- library/lua/dfhack.lua
- library/lua/helpdb.lua
- plugins/lua/hotkeys.lua
fixes poor execution of https://github.com/DFHack/dfhack/pull/4664
> move filtering of armok keybindings into cpp

- library/Core.cpp
- library/LuaTools.cpp
Followup to feedback in #4674.
I verified that `dfhack.internal.setArmokTools()` and `dfhack.setMortalMode()` can still be called from the `lua` interpreter without deadlocking. I haven't seen meaningful changes occur from calling them, though, so my testing may not be exhaustive.
> Fix thread-safety issues around armok mode logic

- library/DataIdentity.cpp
- library/include/DataIdentity.h
this makes identity traits for these two specializations available in plugins
with this change, the `stl_vector_identity` template will be visible to plugins, but the identity objects _themselves_ will not (except for `vector<int32_t>` and `vector<int16_t>`) so any attempt to actually use a `vector` other than one of these two types or of a pointer type (which is covered elsewhere by the `vector<T*>` specialization which is exported) will result in linkage errors
this is mainly intended to enable merging #4632 without #4591, since i don't think i want to pursue #4591 at this time
> `vector<int32_t>` and `vector<int16_t>`

- conf.py
discovered when a PR branch name ended in `.rst`
> [docs] don't scan .git dirs for rst files

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
opens the door for `spawnunit`, `modtools/create-unit`, and other potential future tools, like `force siege`
> expose unit creation DF endpoint to C++ and Lua

- library/include/modules/Maps.h
- library/modules/Maps.cpp
- plugins/autochop.cpp
- plugins/getplants.cpp
- plugins/plant.cpp
- plugins/prospector.cpp
Implement an iterator that operates on all `df::coord`s within a cuboid box. Iterates in the direction of x/y/z provided (rather than always min to max.) By default iterates per z-level, but has an option to iterate in the z direction first.
Closes #4596
Cuboid class for defining a cuboid of tiles. Can test if a coord is inside itself. Can be expanded to contain a given coord. Has a method to call the above iterator using the defined cuboid.
Closes #4595
Also update plugins to use `plant_type` enum attrs, since we're removing the `cuboid` struct from `plugins/plant.cpp` in this PR anyway.
> Implement df::coord iterator and cuboid class 

- library/DataDefs.cpp
- library/DataIdentity.cpp
- library/LuaTools.cpp
- library/LuaTypes.cpp
- library/LuaWrapper.cpp
- library/VTableInterpose.cpp
- library/include/DataDefs.h
- library/include/DataFuncs.h
- library/include/DataIdentity.h
- library/include/LuaTools.h
- library/include/LuaWrapper.h
- library/include/PluginStatics.h
- library/include/VTableInterpose.h
- plugins/devel/check-structures-sanity/check-structures-sanity.h
- plugins/devel/check-structures-sanity/dispatch.cpp
- plugins/devel/check-structures-sanity/types.cpp
- plugins/devel/check-structures-sanity/validate.cpp
This PR marks all of the core data identity classes as `const` to reflect that these types are effectively immutable. 
As noted elsewhere, `compound_identity` has a small degree of technical mutability due to lazy initialization, and `virtual_identity` has mutability due to its dual purpose for implementing vtable interposes; these are both accommodated by marking the related class members as `mutable`. This results in some `const_cast`s, in the `compound_identity` and `struct_identity` constructors, and in a couple of places in code related to virtual identities. There are also several `const_cast`s associated with storing type identity pointers into Lua metatables and lightuserdata objects, which are downcasts into `void*` and thus have to be `const_cast`ed to maintain correctness. Some …
> constify identities

- library/include/DataDefs.h
- library/include/DataIdentity.h
that were causing warnings/errors on gcc 13.2
ref: https://github.com/DFHack/dfhack/pull/4702
> add a few missing const specifiers

- library/DataDefs.cpp
based on a string search of "dfhack_"
Fixes: https://github.com/DFHack/dfhack/issues/4101
> don't warn about dfhack classes not being in symbols.xml

- docs/changelog.txt
- library/modules/Items.cpp
it's not like other flags, which are "can match"
Fixes: https://github.com/DFHack/dfhack/issues/4731
> [Items::isSuitableMaterial] thread flags must match exactly

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/plugins/tiletypes.rst
- plugins/tiletypes.cpp
Fixes autocorrect leaving ramp tops after erasing ramps.
Renames `surroundings` to `autocorrect`.
> Fix ramp autocorrect and rename surroundings to autocorrect

- plugins/tiletypes.cpp
Sets the temperature of modified tiles to 10015 if below that temperature and using the `subterranean` flag.
Decided not to put it in the `postWrite` functions because that would imply an extra loop through all tiles when using `paintArea`
> Tiletypes fix subterranean temperature

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/dfhack.lua
- library/lua/gui/widgets.lua
- test/library/string.lua
to better serve use cases like `gui/journal`: https://github.com/DFHack/scripts/pull/1208
defaults to a behavior that won't change wrapping for current WrappedText widgets
> [lua] preserve spaces when wrapping text

- library/Core.cpp
- library/DataDefs.cpp
- library/LuaApi.cpp
- library/include/Core.h
- library/modules/World.cpp
> track unpaused FPS for more accurate FPS measurements

- plugins/tweak/tweaks/adamantine-cloth-wear.h
Instead of using `MaterialInfo`, just check that it's an INORGANIC material and do the lookup manually.
Also fix the "broken" threshold at the end - turns out the game does `>=`, not `>`.
> Optimize adamantine-cloth-wear tweak

- docs/changelog.txt
- plugins/changelayer.cpp
Depending on embark location, it sometimes changed the wrong layers and resulted in nothing appearing to change at all.
> Fix changelayer plugin, do geology lookup properly

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
useful for `open-legends` where we *don't* want the ZScreen to immediately capture keyboard focus
> allow ZScreens to start unfocused

- docs/plugins/add-spatter.rst
- docs/plugins/cleaners.rst
why is the plugin named cleaners?
> [docs] don't expand clean to cleaners

- docs/about/Authors.rst
- library/lua/gui.lua
Add support for `_MOUSE_L_DOWN`, `_MOUSE_R_DOWN`, `_MOUSE_M_DOWN` and `_MOUSE_M` to `simulateInput` function.
Withot it, it is impossible to test some of gui scripts (e.g. journal) in integration way, as only `_MOUSE_L` and `_MOUSE_R` inputs are working with `gui.simulateInput` right now.
The same table (`MOUSE_KEYS`) is also used on `ZScreen:onInput`. I am not sure if this can affect it negatively somehow.
> Add simulate support for mouse middle btn and "*DOWN" mouse btn events

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/plugins/autodump.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- library/modules/MapCache.cpp
- plugins/autoclothing.cpp
- plugins/autodump.cpp
- plugins/createitem.cpp
- plugins/dig-now.cpp
Remove `MapCache` dependency for `Items` module.
Moved a bunch of code out of a switch statement in `createitem.cpp` into separate utility fns for readability.
Made improvements to `autodump.cpp` so it's in line with `gui/autodump`. (Convert to projectile, cancel any active job.)
Tidied up `autoclothing.cpp` a bit, made sure to initialize variables in a struct.
Made `dfhack.items.moveToInventory` args `use_mode` and `body_part` optional.
> Remove MapCache dependency for Items module

- docs/plugins/autobutcher.rst
- docs/plugins/autodump.rst
- docs/plugins/blueprint.rst
- docs/plugins/createitem.rst
- docs/plugins/stockpiles.rst
- docs/plugins/suspendmanager.rst
Make sure there are links to `gui/` Lua scripts in plugin docs.
> Improve docs by linking to GUI versions of tools

- docs/changelog.txt
- library/VTableInterpose.cpp
avoid inserting `NULL` into `interpose_list` by not using `operator[]` (which totally will do this)
see also #4794, #4830, #4702
> adjust `interpose_list` semantics

- library/modules/Buildings.cpp
as per discord discussion: https://discord.com/channels/793331351645323264/807444515194798090/1268297002676912190
Fixes: https://github.com/DFHack/dfhack/issues/4826
> [Buildings] clean up deconstruct

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
move filter creation out of the item scan
(no open issue, see [discussion on discord](https://discord.com/channels/793331351645323264/807444467140788254/1271131794539937928))
> `buildingplan`: performance improvement

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
so widgets can have stronger guarantees about the context for their `visible` and `active` attribute functions
> [overlay] check focus strings before evaluating widget properties

- library/modules/Gui.cpp
- plugins/lua/buildingplan/mechanisms.lua
fixes workshop skill restrictions widget being shown when stockpile links are being chosen
> fix focus string when choosing stockpile links for a workshop

- docs/about/History.rst
While trying out local builds, I noticed that some pre-v50 entries kept showing up the built NEWS files. It looks like they are coming from the scripts and library/xml changelogs (I made a couple other PRs to trim those changelogs down to just v50, too).
But, it looks like the entries from those changelogs are not present in the newly migrated v0.47/v0.44 History (#4856).
This is a draft PR since I'm not sure what the proper procedure is for History.rst, but this commit seemed like I reasonable approach.
This PR re-builds the v0.47/v0.44 entries from (a pre-migration, locally-built) docs/changelogs/news-dev.rst. The format looks close to the older entries, but there are definite differences from the originally migrated v0.47/v0.44 History (besides the entries from the scripts and …
> use consolidated changelog for pre-v50 History

- docs/about/History.rst
- docs/changelog.txt
- docs/dev/Contributing.rst
- docs/dev/Documentation.rst
- docs/dev/Lua API.rst
- docs/dev/overlay-dev-guide.rst
- docs/guides/quickfort-user-guide.rst
- docs/plugins/autoclothing.rst
- docs/plugins/buildingplan.rst
- docs/plugins/burrow.rst
- docs/plugins/fastdwarf.rst
- docs/plugins/orders.rst
- docs/plugins/regrass.rst
- docs/plugins/reveal.rst
- docs/plugins/sort.rst
- docs/plugins/tailor.rst
- docs/plugins/zone.rst
The "literal block" change (first commit) fixes a warning (and related HTML formatting issue) that I was getting in my local docs builds.
The other commit is the last chunk of my spelling fixes. All these spelling changes aren't super important, but they didn't seem completely valueless, so I have submitted them all.
This was a bit of a "side quest" that kicked off when I wanted to build and spell check a doc update for a not-yet-submitted code change.
> docs minor reST fixup and spelling fixes

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
Note: This is a draft PR due to the second commit probably being unnecessary (and lacking docs).
simulateInput is documented as accepting (among other kinds of values) the same
table that is provided to onInput. However, simulateInput seems to mishandle the
`_STRING` field of such tables.
The Git history looks like it shows that simulateInput has had this behavior
since 2012 August (its origin?):
* 38a07a4ca584e2cccc2c2814c35266ba33d692c8 for `_STRING` given to doInput, and
* 601a3a7927d50500b3dbdd2d20c5d7740a5484a1 for simulateInput.
This sure seems like a bug, but its age gives me doubts.
I didn't find any (open or closed) issues on GitHub that looked like they were
related to this, either.
The first commit in this PR changes simulateInput to ignore `_STRING` of any table
arguments it …
> simulateInput mishandles _STRING

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/createitem.cpp
instead of requiring the caller to figure it out on their own.
I did some basic tests with oak leaves (to make sure they got the correct colors based on the time of year), but further tests would be welcome.
Conveniently, none of the Lua scripts had to be touched (because they weren't specifying growth print information in the first place).
> Items::createItem - auto-select growth prints

- library/modules/Gui.cpp
corrected reverse-engineering of this function
the previous version would wrap a single period, comma, question mark. or exclamation mark in the wrong place in certain cases
this version is more faithful to the actual code in DF
h/t to @vizv for bringing this up on discord
> correct implementation of `Gui::MTB_set_width`

- docs/plugins/preserve-rooms.rst
- plugins/lua/preserve-rooms.lua
- plugins/preserve-rooms.cpp
and there is no current office holder to assign to the zone
ref: https://github.com/DFHack/dfhack/issues/4881
> [preserve-rooms] evict owner and suspend zone when assigned to a role

- docs/changelog.txt
- plugins/strangemood.cpp
Remains and bones were being given a quantity of 1, but in-game those use the same 1-3 quantity as other item types.
Turns out they were always this way, and I've been misreading that spot in the disassembly for the past 10 years.
> strangemood - fix macabre mood items

- docs/changelog.txt
- docs/plugins/regrass.rst
- library/include/modules/Maps.h
- library/modules/Maps.cpp
- plugins/regrass.cpp
Fixed an issue where `cuboid::clampMap` would include map edge tiles for cuboids completely outside of map. Function now returns `cuboid` instead of `bool` to allow for method chaining. Call `cuboid::isValid()` on the result to determine success (e.g., `bool success = some_cuboid.clampMap().isValid();`).
`cuboid::clamp` and `cuboid::clampNew` will now always return invalid cuboids for invalid input, instead of putting the responsibility on the caller.
Updated `regrass` plugin to use `cuboid` class. Improved debug logging. Allowed muddy feature stone (i.e., slade) to be converted to grass, since this can occur in vanilla. Made `--force` no longer imply `--new`, since someone didn't want random grass in their muddy cavern level.
> Update regrass plugin; DFHack::cuboid fixes

- library/include/modules/Persistence.h
- library/modules/Persistence.cpp
since it causes plugins that call the function to become un-unloadable
ref: https://github.com/DFHack/dfhack/issues/4301
> don't expose function with a local static variable

- docs/changelog.txt
- library/modules/Units.cpp
fixes transcription error introduced in #4810
> clear unit bit when teleporting a unit that is not prone

- plugins/lua/preserve-rooms.lua
Fixes: https://github.com/DFHack/dfhack/issues/4925
> [preserve-rooms] don't intercept string input when player is editing name

- docs/changelog.txt
- plugins/preserve-rooms.cpp
as reported on Reddit: https://www.reddit.com/r/dwarffortress/comments/1flzlln/comment/lobdaph/?utm_source=share&utm_medium=web2x&context=3
> [preserve-rooms] don't reserve a room for expelled units

- docs/changelog.txt
- docs/plugins/preserve-rooms.rst
- plugins/preserve-rooms.cpp
this fixes old reservations kept from before we excluded expelled units as a side effect, reservations for prisoners are no longer kept
> [preserve-rooms] don't keep reservations for units not in armies

- docs/changelog.txt
- library/lua/gui.lua
- library/lua/gui/widgets/containers/panel.lua
when clicking in the inset area of resizable windows
this PR fixes the issue and also fixes the trigger. Mouse clicks over the window area are now guaranteed not to bleed thorugh. Also, the window was not handling those clicks in the first place because the inset area was not marked as draggable when the window was also resizable due to how the defaults were calculated. Now the inset area is draggable by default.
> [ZScreen, Panel] prevent mouse clicks from bleeding through

- docs/changelog.txt
- library/Core.cpp
- library/VersionInfoFactory.cpp
- library/include/VersionInfo.h
- library/include/VersionInfoFactory.h
now reports which versions are supported:
> [Core] make version mismatch error message more informative

- plugins/blueprint.cpp
Fix unintentional copies of iter variables. Check `start.isValid()` instead of `start.x`.
Added a message when no files are created instead of `Generated blueprint file(s):` followed by nothing.
> Small blueprint.cpp changes

- docs/changelog.txt
- plugins/lua/buildingplan/itemselection.lua
- add option to sort by value
- reorder sorting options to match ordering of colums
- adjust width of existing columns
> Add distance and value info to buildingplan item selection list #4312

- docs/dev/Lua API.rst
- library/LuaWrapper.cpp
so Lua can tell them apart from other structures
> [Lua] add _union=true field to union types

- docs/changelog.txt
- plugins/logistics.cpp
bad_flags was probably copied from another plugin that *did* need to ignore rotten items. `logistics` should not filter those out, though.
Reported on [Steam](https://steamcommunity.com/app/2346660/discussions/0/4844275132580268851/)
> [logistics] don't ignore rotten items

- docs/changelog.txt
- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
to allow for custom config to be fully set first
Fixes: https://github.com/DFHack/dfhack/issues/4986
> [autobutcher] don't run cycle on first fort tick

- docs/changelog.txt
- library/include/modules/Units.h
- library/modules/Units.cpp
> add `Units::setAutomaticProfessions`

- docs/changelog.txt
- plugins/nestboxes.cpp
- plugins/timestream.cpp
testing shows that it is the properties of the egg that matter, not the properties of the mother
this also brings the behavior of `nestboxes` in line with the fertile egg indicator tweak. before this PR, eggs marked "fertile" could be unforbidden by `nestboxes`, collected, and eaten. This was confusing to players.
@Birkow FYI -- logic might need updating in https://github.com/DFHack/dfhack/pull/4947
> [nestboxes, timestream] fix handling of eggs

- library/lua/gui/widgets/list.lua
`Panel.DOUBLE_CLICK_MS` was [moved here](https://github.com/DFHack/dfhack/commit/52ed5162fa1f212d18d73a3ad50723db759efbfb)
It looks like this reference in `List` got missed causing errors like `hack\lua\gui\widgets\list.lua:344: attempt to compare number with nil`. Switched it to use `common.DOUBLE_CLICK_MS`
> Fix DOUBLE_CLICK_MS reference

- library/LuaApi.cpp
- library/include/modules/Graphic.h
this significantly reduces the number of compilation units that depend on `DFSDL.h`
this allows us to include more content into `DFSDL.h` without as much compile-time loading; `Graphic.h` is included by `Core.h` which is included by many many things, but only a handful of compilation units include `DFSDL.h` directly
the only module that needed to be adjusted was `LuaApi.cpp`
> remove `DFSDL.h` dependency from `Graphic.h`

- docs/changelog.txt
- plugins/timestream.cpp
thank you to Snowfious for helping us track this one down
> [timestream] fix heap smash in birthday tracking

- library/include/DataDefs.h
- library/include/DataFuncs.h
- library/include/modules/DFSDL.h
- library/modules/Constructions.cpp
Add some shadowed dependencies as future-proofing
Also, remove some crud left over to mitigate long-dead bugs in MSVC
This came up during exploratory investigations of using C++20 modules. We probably won't be doing _that_ until CMake support for modules is much better than it is now, but it was worth looking at.
> some header cleanups

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets/tab_bar.lua
- test/library/gui/widgets.TabBar.lua
- Modify `TabBar` to allow tabs to be scrolled instead of wrapping by setting `wrap=false` in the `TabBar` attributes. `wrap` defaults to true so any existing instances of `TabBar` should be unaffected (tested with launcher and control-panel and they're looking good).
- Add tests for Tab/TabBar
I made a little [demo script](https://gist.github.com/robob27/1edf22efff8bedd0956987390612d4a3) with a scrolling TabBar alongside a wrapping one with a resizable window so the behavior can be easily tested (requires this branch). Testers should try changing `autoarrange_subviews` in the script and ensure it doesn't break things, play around with the options, and double check that existing consumers of this widget like launcher and control-panel doesn't get messed up in some way that I missed.
Some …
> Scrolling `TabBar`

- docs/Core.rst
- docs/changelog.txt
- library/Core.cpp
at startup, check selected DF global objects to ensure that the size reported in the DF global table matches what df-structures says, and refuse to start if they don't
the check is bypassed if the `--skip-size-check` command line option is added to the DF command line
> Add a basic size safety check to DFHack startup 

- library/Core.cpp
structures might not have the correct size of the global table; this avoids running off the end if it is wrong
> sizecheck: add safety check

- test/core.lua
CI expected to fail for this PR, but will be corrected with https://github.com/DFHack/df-structures/pull/811
> add regression test for size of global_table

- library/Core.cpp
Reverts DFHack/dfhack#5040 because of mysterious hang
see: https://discord.com/channels/793331351645323264/793331351645323267/1312143185748820009
> Revert "REGRESSION: Fix console command completion help"

- CMakeLists.txt
- build/build-win64-from-linux.sh
- docs/changelog.txt
- docs/dev/compile/Compile.rst
pulls the updated build-env image
> update the build env label

- library/Core.cpp
The code has been updated to properly account for potential items on the lua stack.
> Reenable console completion help

- plugins/timestream.cpp
can't call `plugin_enable` after world unload because it will fail the sanity check
> [timestream] properly unregister listeners on world unload

- docs/changelog.txt
- plugins/fix-occupancy.cpp
this handles the case where a building has been moved (or created) on a tile, but the tile occupancy flags don't know about it
> [fix-occupancy] fix occupancy when a building exists but the tile doesn't know

- depends/lua/include/dfhack_llimits.h
Previously, calling a Lua C API function that throws an error (e.g. with any of the `lua_error()` family of functions, which use `luaD_throw()` internally) in a function that also uses our own `StackUnwinder` would deadlock, because:
- `luaD_throw()` calls `lua_lock()` but apparently expects something else to call `lua_unlock()`
- `~StackUnwinder()` calls `lua_settop()` to rewind the stack, which internally also calls `lua_lock()` and `lua_unlock()`. This is called before the mutex can be unlocked.
This was the root cause of the issue behind #5040, #5055, #5056 - `GetVector()` was called with an invalid index (only when invoked from `gui/launcher`, because this changed the data on the Lua stack) and threw an exception, which caused the `~StackUnwinder()` destructor to run while the Lua …
> Lua: switch to recursive mutex in lua_lock()

- plugins/luasocket.cpp
The Errno is set on the `CPassiveSocket` when `->Accept()` returns null. This corrects the behavior where it would try to call a function on the nullptr.
> Fix possible crash in luasockets

- plugins/infinite-sky.cpp
Core is now suspended before running any lua functions.
Identity structure now properly includes an end marker.
Tested on Linux and Windows, the command appears to be functioning as it should.
> Fix crashing bugs in infinite-sky

- library/Core.cpp
to reduce danger of deadlocking
will be reverted and properly fixed in #5075
ref: #5056
> temporarily neuter implementation of try_autocomplete

- depends/lua/include/dfhack_llimits.h
Initialize attributes before use. I believe this is the source of UB on Linux, which results in stochastic hangs. It is easily reproducable when launching from steam on my system.
> #5061 fix: add missing pthread_mutexattr_init()

- docs/changelog.txt
- plugins/orders.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5084
ref: https://steamcommunity.com/app/2346660/discussions/0/4634863254940732046/
> [orders] sort workshop-tied orders first

- library/modules/Units.cpp
This only handles night creatures (the hostile one in the save this patch fixes) and opposed to lifers (necromancers? I don't recall.) 
May want this to apply to them all. It is possible for a demon to visit as a merchant.
I don't see anything obvious where this change will cause unwanted side effects in any of the callers of this function.
> isDanger(): don't mark visitors hostile

- library/Core.cpp
- library/Hooks.cpp
- library/modules/DFSDL.cpp
- library/modules/DFSteam.cpp
output results of core size check test
don't attempt to load libs from other OSs
> startup output cleanup

- CMakeLists.txt
This change enables MSVC diagnostic C5038, which is equivalent to the diagnostic gcc generates when `-Werror=reorder` is violated
> enable C5038 for MSVC

- docs/changelog.txt
- plugins/preserve-rooms.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5104
> [preserve-rooms] fix handling of incoming and offloaded units

- docs/changelog.txt
- plugins/preserve-tombs.cpp
also pretty up some output messages
Fixes: https://github.com/DFHack/dfhack/issues/5105
> [preserve-tombs] re-register handler when re-enabling on load

- .gitignore
- depends/CMakeLists.txt
we pinned the previous version for gcc 4.8 compat. that is no longer necessary.
> update to googletest 1.15.2

- library/Core.cpp
- library/PluginManager.cpp
- library/include/Core.h
this is an attempted step to improve semantics around core suspenders. this does not actually resolve #5074 but it is intended as a step toward doing so
> adjustments to core suspender

- library/Hooks.cpp
- library/include/Hooks.h
FYI: @dhthwy 
Note that DF doesn't actually call this hook yet, and won't until at least 50.16/51.01-beta27
Until then, you can probably synthesize this call by tapping into `dfhooks_sdl_event` and rate limiting with a timer
> add entry point for dfhooks_sdl_loop

- library/Core.cpp
- library/PluginManager.cpp
- library/include/Core.h
The main thing this PR does is add some code to monitor for attempts to acquire a `CoreSuspender` from the DF render thread, which is impermissible and will lead to deadlock. It currently only uses an `assert` for this (which means it's only operational in a debug build).
It also removes some dead code related to threading and fixes a couple of semantic errors:
* `Core::Shutdown` attempts to unlock the main core lock, but cannot do so because it always runs on the render thread while the main core lock is held by the simulation thread. This is replaced by an atomic flag `shutdown` which `Core::Shutdown` sets and which `Core::Update` checks.
* Plugin unloading would attempt to acquire a `CoreSuspender` to save plugin site and world data. Plugin unload during shutdown cannot acquire a …
> thread safety checks

- library/lua/repeat-util.lua
`isScheduled()` and `listScheduled()`
> add a query API to repeat-util

- docs/changelog.txt
- plugins/lua/zone.lua
Fixes: https://github.com/DFHack/dfhack/issues/5103
> [zone] allow pets to be unassigned from cages/restraints

- library/Process-darwin.cpp
- library/Process-linux.cpp
- library/Process-windows.cpp
Rearrange all three `Process-*.cpp` files so that the contents are in parallel as much as possible
remove `using namespace std` code smell
reorganize header includes
change minimum supported windows version to 6.0 (Vista)
> reorganize/tidy `Process-*.cpp` source units

- library/include/modules/World.h
- library/modules/Persistence.cpp
- library/modules/World.cpp
Adds:
- World name: Corinth (Corinth)
- DF save version when world was generated
- DF save version when world was last saved
- Current DF save version
> add save version info to dfhack-status.dat

- docs/dev/Documentation.rst
- docs/sphinx_extensions/dfhack/changelog.py
ref: https://github.com/DFHack/stonesense/issues/117
> include stonesense changelog in generated unified changelog

- library/CMakeLists.txt
- library/MiscUtils.cpp
- library/Process-darwin.cpp
- library/Process-linux.cpp
- library/Process-windows.cpp
This set of changes adds support for symbol demangling via `cxx_demangle` on Windows and uses the improved symbol demangling in reading classnames from RTTI entries on all current targets.
Known problems:
- Wine environments fail on some advanced STL features.
When running a modified `devel/scan-vtables` for Windows under wine, a number of symbols fail demangling, all of which can be filtered out by excluding those belonging to std/Concurency. This can be automatically performed by checking if the end of the mangled name is `std@@` or `Concurrency@@`.
I have not discovered any further issues, but practical testing is likely a requirement.
Thank you to @ab9rf and @lethosor for their help with understanding particular issues that arose.
> Improved Symbol Demangling

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
Add versions that take `df::coord`s instead of x/y/z.
> Add pos argument versions for Unit "InBox" fns

- plugins/cursecheck.cpp
current code (with a vector being constructed inline in a for loop initializer) produces the following error (for me, at least; seems to pass fine in CI)
```sh
FAILED: plugins/CMakeFiles/cursecheck.dir/cursecheck.cpp.o 
/usr/bin/ccache /usr/lib/ccache/bin/g++ -DDFHACK64 -DHAVE_CUCHAR -DLINUX_BUILD -DLUA_BUILD_AS_DLL -DPROTOBUF_USE_DLLS -D_LINUX -Dcursecheck_EXPORTS -I/home/myk/src/dfhack/depends/SDL2/SDL2-2.26.2/include -I/home/myk/src/dfhack/depends/protobuf -I/home/myk/src/dfhack/depends/lua/include -I/home/myk/src/dfhack/depends/md5 -I/home/myk/src/dfhack/depends/tinyxml -I/home/myk/src/dfhack/depends/lodepng -I/home/myk/src/dfhack/depends/clsocket/src -I/home/myk/src/dfhack/depends/xlsxio/include -I/home/myk/src/dfhack/library/include -I/home/myk/src/dfhack/library/proto …
```
> [cursecheck] fix build for gcc-13.3.1

- library/MiscUtils.cpp
Some versions of the Windows SDK (pre-8.1 are known) include a version of DbgHelp.h that trigger a warning upon compilation. To maintain compatability with these versions of the SDK, the warning is suppressed.
Fixes #5147
> Fix build on older versions of WinSDK

- plugins/lua/zone.lua
was matching focus against incorrect viewscreen
> [zone] hide retire zone overlay when another vs is in the foreground

- docs/changelog.txt
- library/modules/Units.cpp
when acting on a df::unit and there is no impersonated identity
> [Units] return original unit name instead of hf name

- library/CMakeLists.txt
- library/Core.cpp
- library/LuaTools.cpp
- library/PluginManager.cpp
- library/RemoteTools.cpp
- library/include/Core.h
- library/include/CoreDefs.h
- library/include/LuaTools.h
- library/include/RemoteClient.h
- library/modules/Screen.cpp
- plugins/devel/check-structures-sanity/main.cpp
- plugins/dig-now.cpp
- plugins/overlay.cpp
- plugins/remotefortressreader/item_reader.cpp
This moves the global Lua state from a static global in LuaTools.h to a member variable of the singleton `Core`. A public accessor, `getLuaState`, is added to `Core` to provide access. This accessor includes an assertion which guarantees that only threads that hold the core mutex attempt to acquire the core lua state. Passing `true` to `getLuaState` will bypass the assertion; this should only be used in code that is guaranteed to acquire a `CoreSuspender` before trying to use the acquired Lua state.
> Refactor core Lua state and add thread safety assertions

- .readthedocs.yml
our readthedocs pdf build is failing with `pdflatex: Command for 'pdflatex' gave return code 1`
example: https://app.readthedocs.org/projects/dfhack/builds/26702685/
it may be that our docs have grown too large. the failures started with the recent updates to stonesense, but that may be coincidental
this PR will remove the pdf format from the build until we can figure out how to fix it
FWIW, the PDF build produces a PDF when I run it locally. However the process *does* exit with a non-zero error code.
> remove pdf from offline formats list

- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
I'm not sure where these came from. the runner hasn't changed, and no errors are seen in my local builds
> fix mysterious new errors in CI

- .readthedocs.yml
- docs/plugins/stonesense.rst
This corrects a syntax issue in a rst file that was breaking the pdf build. The pdf build is also reenabled.
> Reenable pdf documentation

- build/build-win64-from-linux.sh
e.g. when building just xml-dump-type-sizes
> [cross build] don't fail if some output dirs don't exist

- docs/changelog.txt
- plugins/suspendmanager.cpp
This eliminates the `"External reason"` descriptions in suspendmanager, adding cases for when a jobsite is submerged and when a job is being planned/managed by buildingplan.
> Additional Suspendmanager Reason Descriptions

- docs/changelog.txt
- plugins/stockpiles/StockpileSerializer.cpp
when the setting is not contained in the import file
Thanks, @NicksWorld
> [stockpiles] don't use uninitialized value for use_links_only

- library/include/DataFuncs.h
this should allow a function (or method) with call-by-reference parameters to be wrapped and exported to lua. the wrapper will translate an equivalent pointer type to the reference type (and throw if the pointer is null)
> support call-by-reference in wrapped functions

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/Types.h
- library/include/modules/Translation.h
- library/modules/Translation.cpp
- plugins/strangemood.cpp
Also available from Lua as "dfhack.generateName(...)"
Fixes: #5166
> add Translation::GenerateName()

- library/Core.cpp
- library/LuaTools.cpp
- library/RemoteTools.cpp
- library/include/Core.h
- Fix unintended assert when interrupting Lua
- Protect the remote server from try_autocomplete deadlock when attempting to run `kill-lua` but misspelling it
- disable ConditionalCoreSuspender on Linux (until we can figure out why it's misbehaving)
Discord discussion: https://discord.com/channels/793331351645323264/807444515194798090/1327095546804047995
> Mitigations for deadlock behavior on Linux

- docs/changelog.txt
- plugins/dig-now.cpp
I don't think there is any reason these tiles should be ignored. Looking at the history, I think I just didn't fully understand the tile types when I first wrote the plugin.
> [dig-now] consider pool and river tiles as diggable

- library/Core.cpp
- library/include/Core.h
`dec_tool_count` was being called on already unlocked CoreSuspenders, causing the tool count to go negative. As the core only resumes when the tool count is 0, a deadlock occured. By returning early if the underlying lock isn't held, this issue is avoided.
> Prevent deadlocks when unlocking a CoreSuspender

- library/Core.cpp
and return a proper error code
> [Core] output proper error messages when plugin operations fail

- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
this obsolete type is a leftover from DFHack's out of process days, vastly out of date and useless today... except in stonesense, which now has it locally (as `Stonesense_Building`)
> remove obsolete `t_building`

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Persistence.h
- library/modules/Persistence.cpp
This code is supposed to note down what the millisecond time is on save or load and be able to return the difference from that time and now to give to `notifications.lua`
> Add the API code to know when the last save was.

- docs/plugins/stonesense.rst
I'm decoupling the path change from other changes in #5187 so that PR can just address docs for new features
> adapt to new location of stonesense keybinds file

- plugins/infinite-sky.cpp
- plugins/timestream.cpp
it will already be disabled and it results in spurious error messages in non-fort modes
> [infinite-sky, timestream] don't explicitly disable on load

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
for eventual use by `gui/manipulator` (or anybody else)
> expose Units::setAutomaticProfessions to Lua

- library/lua/gui/widgets/edit_field.lua
- library/lua/gui/widgets/text_area.lua
- library/lua/gui/widgets/text_area/text_area_content.lua
Before `EditField` focus has been grabbed by `TextArea` children component.
Now `EditField` grab the focus by itself and properly manage it during session.
> Make EditField grab focus instead of proxying it to children

- library/lua/gui/widgets/edit_field.lua
- library/lua/gui/widgets/text_area.lua
- test/library/gui/widgets.TextArea.lua
Fix `EditField` long lines cursor behaviour described in this issue:
> The scenario requires a couple of commands in gui/launcher history: (e.g.)
:lua print'jh 0123456789 0123456789 0123456789 jl'(the "long" entry)
extend the string (or shrink the window) as necessary so that it is longer
than the gui/launcher command line is wide
gui/gm-unit (the "short" entry)
> Then,
Alt-s to focus the search field,
type jj to find the long entry,
Ctrl-u to clear the search field,
type unit to find the short entry,
Esc to go back to the command line field.
> The command line EditField looks like it is empty with just a cursor. The short entry is
there, but it is "scrolled" out of view to the left. Moving the cursor to the
left will start to reveal the short entry.
> Fix Edit Field long lines changing text cursor behaviour

- docs/changelog.txt
- plugins/changevein.cpp
This adds a check for when the original and target material are the same, providing an error message if attempted.
The algorithm for finding neighboring vein tiles relies upon the original and target materials being different, otherwise it leads to infinite recursion which inevitably ends in a crash.
Fixes #5231
> Disallow changing a vein into itself

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Military.h
- library/modules/Military.cpp
Originally intended to be used in a now-cancelled Lua script feature, but figured it may be useful for those dabbling in military matters.
> Add function to remove unit from squad

- docs/plugins/spectate.rst
- plugins/lua/spectate.lua
- plugins/spectate.cpp
also change the API to only have one overlay instead of two
we don't have a good way to control the order that overlays render in, and these overlays have a specific dependency
> [spectate] implement unit history scanning and auto-disengage features

- library/lua/custom-raw-tokens.lua
- library/lua/dfhack/workshops.lua
- library/lua/gui/materials.lua
- plugins/lua/sort.lua
- plugins/lua/stockflow.lua
- plugins/rendermax/rendermax.lua
ref: https://github.com/DFHack/df-structures/pull/824
> finish updating modules for the Great Reorg

- docs/changelog.txt
- docs/plugins/stockpiles.rst
- plugins/stockpiles/OrganicMatLookup.cpp
- plugins/stockpiles/OrganicMatLookup.h
- plugins/stockpiles/StockpileSerializer.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5248
Also fixes a crash introduced with the new NONE enum value. We were using the enum range to index an array, and NONE is -1
> [stockpiles] add property filters for brewable, millable, and processable

- docs/about/Authors.rst
- docs/dev/Lua API.rst
- library/modules/Military.cpp
Minor and virtually cosmetic change for consistency's sake.
> `Military::removeFromSquad`: Add missing history event when unassigning officer

- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
This reverts changes requiring the `df::building*` argument not to be null, as it is expected to skip checking using a building's extents when given a nullptr.
Various lua scripts were making use of this method, supplying a nullptr, causing errors such as the one reported [here](https://discord.com/channels/793331351645323264/1017471248567124049/1339056215379935365), which could be triggered by using buildingplan to designate constructions.
> Fix regression in checkFreeTiles

- docs/changelog.txt
- library/Console-windows.cpp
Fix logic that can hang if the reported console window width is less than the prompt width
> Fix win console hang

- docs/plugins/spectate.rst
- plugins/lua/spectate.lua
Implement the unit banners and mouse tooltips optionally showing unit stress/happiness, name, and current job; optionally as a "banner" following units, or as a mouse tooltip.
This is an evolution of the work in https://github.com/DFHack/scripts/pull/1365, which will be reduced to just the config UI.
> spectate.lua: implement unit banners and mouse tooltips

- docs/changelog.txt
- library/modules/Units.cpp
hot fix while we decide on #4959
> [Units] exclude inactive units from inBox functions

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
Fixes: https://github.com/DFHack/dfhack/issues/5078
> [overlay] add API for querying whether an overlay is enabled

- docs/plugins/spectate.rst
- plugins/lua/spectate.lua
- plugins/spectate.cpp
otherwise the UI can fight with the player
> [spectate] get rid of auto-disengage option and make it always on

- plugins/lua/spectate.lua
This reduces the overall level of messiness in that method.
> spectate.lua: refactor `set_setting()`

- library/Core.cpp
- library/Process-linux.cpp
- library/Process-windows.cpp
- library/include/MemAccess.h
This adds code to flush cache after applying a hotpatch. While it's unlikely that a patched location will be in cache at the time we apply a patch, it is better to be safe than sorry
Also fixed the spelling error in `setPermissions` while I was here
No changelog; this is a fix to existing functionality to avoid a potential future bug instead of fixing a known existing one
> flush cache after mempatch

- plugins/lua/spectate.lua
Assigning `writer` back after using its methods isn't necessary.
> spectate.lua: minor simplification of `render_unit_banners()`

- docs/changelog.txt
- plugins/lua/overlay.lua
Fixes: https://github.com/DFHack/dfhack/issues/5291
> [overlay] reset draw context between rendering widgets

- data/orders/basic.json
- docs/changelog.txt
- docs/plugins/orders.rst
> [orders] remove MakeCheese job from basic orders list

- docs/plugins/spectate.rst
- plugins/lua/spectate.lua
Also, add a `toggle <setting>` command line for boolean settings. This allows keybindings for `spectate toggle tooltip-follow`.
> spectate.lua: add "hold-to-show" option (f.e. `ctrl`)

- library/modules/Military.cpp
Fixes `Units::makeSquad` which broke in the Great Reorg
> fix make squad from the great reorg

- data/init/dfhack.keybindings.init
ref: https://github.com/DFHack/scripts/pull/1402
> add toggle-kbd-cursor keybindings for adv mode

- docs/dev/github-workflows.rst
- docs/dev/index.rst
- docs/dev/release-process.rst
once this is merged, turn down https://github.com/DFHack/dfhack/wiki/Release-checklist and point that page to these pages
Fixes: https://github.com/DFHack/dfhack/issues/5249
> document github workflows and release process

- docs/changelog.txt
- plugins/lua/suspendmanager.lua
Fixes: https://github.com/DFHack/dfhack/issues/3560
though it can be improved further by not letting it draw on static UI elements, like the top and bottom of the screen, the minimap, or the squads panel (when it is open)
> [suspendmanager] don't show suspend overlay when other ui panels are up

- ci/test.lua
- docs/changelog.txt
- docs/dev/Lua API.rst
- library/Core.cpp
- library/LuaApi.cpp
- library/LuaTools.cpp
- library/PlugLoad.cpp
- library/PluginManager.cpp
- library/Process-linux.cpp
- library/Process-windows.cpp
- library/Types.cpp
- library/include/Console.h
- library/include/Core.h
- library/include/DataDefs.h
- library/include/DataFuncs.h
- library/include/MemAccess.h
- library/include/PluginManager.h
- library/include/Types.h
- library/include/modules/Filesystem.h
- library/lua/dfhack.lua
- library/modules/Filesystem.cpp
- library/modules/Persistence.cpp
- plugins/orders.cpp
- test/core.lua
Recode most uses of `std::string` to represent a path name to use `std::filesystem::path` instead. Replace most of old crunchy filesystem module with `std::filesystem` equivalents
Some modules have also cleaned to address `using filesystem std` and/or missing or unnecessary `#include`s
The `atime`, `ctime`, and `filetype` methods of the `Filesystem` module have been removed because they're POSIX-specific, not supported by `std::filesystem`, and unused in DFHack
> use `std::filesystem::path` for filesystem operations

- library/LuaApi.cpp
dfhack assumes that scripts are in a namespace in which directories are separated by slashes, and also that pathnames will be slash-separated
this enforces that when the transition is made from a `std::filesystem::path` to dfhack's internal script name space, the native preferred path separator (whatever it is) is replaced with slashes if it isn't already
followup to #5356
> deal with directory separators cleanly

- library/LuaApi.cpp
- library/include/modules/Filesystem.h
- plugins/orders.cpp
added `Filesystem::as_string` to provide namespace recanonicalization and change use in LuaApi to use this exported API
use `as_string` in `orders`
further revision of #5360
> more path/string normalization

- data/init/dfhack.keybindings.init
- docs/changelog.txt
Fixes: https://github.com/DFHack/dfhack/issues/5346
> add hotkey for gui/journal in adv mode

- docs/changelog.txt
- plugins/lua/sort/diplomacy.lua
adapt to structure changes (pref.active is now pref.flags.visible)
Fixes: https://github.com/DFHack/dfhack/issues/5350
> [sort] fix barony overlay

- docs/changelog.txt
- plugins/stockpiles/StockpileSerializer.cpp
was not correctly handling enums that did not start at 0, leading to errors in furniture stockpiles
Fixes: https://github.com/DFHack/dfhack/issues/5275
> [stockpiles] fix conversion of enum token to value

- docs/changelog.txt
- plugins/dig-now.cpp
Fix detection of materials and support generating ice boulders from ice walls
Fixes: https://github.com/DFHack/dfhack/issues/5364
Fixes: https://github.com/DFHack/dfhack/issues/3286
> [dig-now]: fix material and shape detection for generated boulders/rough gems

- docs/changelog.txt
- plugins/lua/spectate.lua
Fixes: https://github.com/DFHack/dfhack/issues/5379
> [spectate] don't show hover tooltip for hidden creatures

- docs/changelog.txt
- library/include/BitArray.h
- library/include/MiscUtils.h
- library/modules/Units.cpp
otherwise they will be teleported back to their next projectile targeted tile on the next tick
Includes an extension of the DFLinkedList API (was missing operator->) and a refactoring of linked_list_remove so it can take a predicate
Fixes: https://github.com/DFHack/dfhack/issues/5381
> [Units::teleport] remove projectile data when teleporting

- docs/changelog.txt
- library/Core.cpp
This fixes an issue where c++ plugins do not properly unload when the "unload" command is run in the dfhack in game command interface.
library/Core.cpp:L803: Added reload bool to catch whether the reload command was given in Core::runCommand
library/Core.cpp:L831: Added reload to else if statement to short circuit the PluginManager::reload statement so that it only runs if reload was run as a command to Core::runCommand.
docs/changelog.txt: Added description of change.
> Fix to plugins automatically reloading after unload command.

- library/include/DataDefs.h
- library/include/LuaTools.h
- plugins/debug.cpp
this commit changes several templates to have more precisely constrained match patterns to yield more clear compilation errors when a mistake is made
certain `Lua::Push` overloads have been made either more or less general; a side effect is that more "string-like" objects (notably, `std::string_view`) will be converted to lua strings on push
a chunk of ancient dead code bracketed by `#if 0` was removed
a declaration for the undefined and unused `Lua::Core::Init` was removed
it also replaces several uses of `enable_if` with `if constexpr` or templates constrained by appropriate types, to make that code more readable
some other minor cleanups, mostly around namespaces blocks,, are also included
> code modernization

- docs/changelog.txt
- library/Core.cpp
ref: https://github.com/DFHack/dfhack/pull/5199#discussion_r2040736613
> also unbreak unload -a

- docs/changelog.txt
- library/modules/Buildings.cpp
the stockpile iterator will crash if a `map_block` contains an item pointer to an item that is not on the master item list. this should never happen if DF was working correctly, but DF often does not work correctly
related discord discussion: https://discord.com/channels/329272032778780672/1049402643342168114/1360977656820273322
> add safety check to stockpile iterator

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/include/modules/Units.h
- library/modules/Buildings.cpp
- library/modules/Units.cpp
- plugins/preserve-rooms.cpp
- plugins/preserve-tombs.cpp
- ``Units`` module: added ``get_cached_unit_by_global_id`` to emulate how DF handles unit vector index caching (used in civzones and in general references)
- ``Buildings`` module: add ``getOwner`` (using the ``Units::get_cached_unit_by_global_id`` mechanic) to reflect changes in 51.11
- ``Buildings::setOwner``: updated for changes in 51.11
also changes to plug-ins for 51.11
> updates for 51.11

- docs/changelog.txt
- plugins/preserve-rooms.cpp
this avoids a crash when a civzone is assigned to an invalid unit id. this should never happen, but...
> `preserve-rooms`: validate assigned unit id before using

- docs/changelog.txt
- plugins/preserve-tombs.cpp
another change required by the change in civzone unit assignment semantics in DF 51.11
> don't crash on a tomb owned by a unit that doesn't exist

- docs/changelog.txt
- plugins/getplants.cpp
`getplants` was crashing while handling plants that have growths that do not drop seeds when processed
this code has been broken for at  least two years, but apparently nobody wrote a mod that triggered it until now
> resolve `getplants` crash

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/script-manager.lua
Supersedes https://github.com/DFHack/dfhack/pull/5395
> [script-manager] add more mod utility functions

- docs/changelog.txt
- library/modules/Items.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5427
> [Items::detachItem] change order of operations to avoid a use after free

- docs/changelog.txt
- library/modules/Items.cpp
* Display correct quality level for items with "non-displayed" improvements
* Add ALL item designations here (and remove "XXwearXX" from other spot)
* Obey SHOW_IMP_QUALITY setting
Fixes #5404
Replaces PR #5406 (which was merging from the wrong branch)
> Fix Items::getDescription

- docs/about/Authors.rst
- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/lua/script-manager.lua
Steam mods with lua scripts in the "scripts_modactive" directory of a mod were not being properly reloaded after the initial load. That is, the script-manager purges these scripts from `dfhack.internal.scripts` before reloading them (more specifically to register their onStateChange). This purge wasn't being done since the file path wasn't being recognized on windows, thus dfhack mods weren't being loaded in games from resumed saves (if DF wasn't shut down before then). This change simply adds the correct windows file path as a key to access the script. It may be better to standardize all OS's paths used as keys in `dfhack.internal.scripts` but it isn't clear to me the locations where all these files are being added, so this is the simple solution.
> Fix for mods not being properly reloaded on Windows from saved game

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
so we can be more selective about how names are displayed in various UIs
> [Units] make english name in readable names optional

- docs/changelog.txt
- plugins/preserve-rooms.cpp
DF now routinely has zones assigned to non-existent units
ref: https://github.com/DFHack/dfhack/issues/5417
more work needs to be done to call that issue fixed, though.
> [preserve-rooms] downgrade warning to debug

- plugins/blueprint.cpp
- plugins/preserve-rooms.cpp
can't handle disjoint zones or overlapping non-rectangular zones yet disjoint zone support coming in a follow-up PR
need to think about overlapping non-rectangular zones more, though
Fixes: https://github.com/DFHack/dfhack/issues/4994
builds on: https://github.com/DFHack/dfhack/pull/5222
> [blueprint] record zone information in blueprints

- docs/changelog.txt
- docs/plugins/spectate.rst
- plugins/lua/spectate.lua
- plugins/spectate.cpp
Closes: https://github.com/DFHack/dfhack/issues/5305
> Add prefer nicknamed to spectate

- docs/changelog.txt
- library/include/LuaTools.h
some (most, actually) `get` methods return a pointer to a `const` instance of a subclass of `type_identity`  which isn't convertible to a pointer of non-`const` `type_identity`. adding `const` fixes this. a pointer to non-`const` is always convertible to a pointer of `const` of the same type or of a compatible type
fixes #5450
the reason why the pointer to vector glossed as a boolean is that pointers have an implicit conversion to `bool`, and so when the type inference for the template failed, it fell back to the next best overload, which was the one for `bool`
> adjust `df_object` constraint

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/dig.cpp
- plugins/lua/dig.lua
Fixes: https://github.com/DFHack/dfhack/issues/5455
> [dig] show priorities for digging designations in ascii overlay

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/createitem.cpp
and update the "createitem" plugin to specify it instead of creating a bunch of individual items in a loop.
Fixes #5481.
> Add "count" parameter to Items::createItem

- library/RemoteTools.cpp
- library/modules/Units.cpp
- plugins/cursecheck.cpp
- plugins/lua/sort.lua
resolves an alignment issue in `unitst`
coordinate change in structures required - see DFHack/df-structures#838
coordinate changes in scripts will also be required
> remove fake `curse` compound in `unitst`

- docs/changelog.txt
- docs/plugins/tweak.rst
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/animaltrap-reuse.h
Makes it so animal traps generate "Release Small Creature" jobs instead of "Destroy Building" jobs, so a dwarf will transfer the caught vermin into an empty stockpiled trap and leave the built trap ready to be automatically filled with new bait (similar to how standard Cage Traps work).
The only downside is that if you don't have any empty animal traps in your stockpiles, you will get an endless stream of "Release Small Creature" job cancellations, but the exact same thing happens if you unassign a vermin from a built **cage** so it's probably fine (and you can still schedule the animal trap for deconstruction).
In order to make the "Release Small Creature" job work correctly, the caught vermin needs to be simultaneously added to both the building inventory and the animal trap itself, but …
> Add "animaltrap-reuse" tweak

- docs/changelog.txt
- docs/plugins/strangemood.rst
- plugins/strangemood.cpp
> Add `--id` to `strangemood`

- docs/changelog.txt
- docs/plugins/autoclothing.rst
- plugins/autoclothing.cpp
These changes aim to handle #5366. Updated documentation to alert users of new `clear` option that will allow them to unset a previously set order. This probably could have been a little cleaner if I added the clear at the end however I think putting it as the first parameter makes it read quite well. Compiled and tested on windows. Please let me know if there is anything I need ti change/do!
> Add clear option to autoclothing that will unset a previosly set order

- docs/changelog.txt
- library/modules/Gui.cpp
Only has `Loading` and `Mods` focus strings since there is no clear way (for me at least) to deduce the profile selection screen. That said, since there are only 3 modes for now anything can just use the base `new_arena` viewscreen path.
> Add arena mode focus strings for widgets

- library/Core.cpp
- library/modules/Persistence.cpp
for 52.xx compatibility when in appdata mode
(no changelog, already covered by the changelog from #5514)
> use consistent base and install path determination

- library/lua/script-manager.lua
One last use of a `<path>` as a `<string>`
> script-manager.lua One last use of a <path> as a <string>

- docs/changelog.txt
- plugins/lua/preserve-rooms.lua
this doesn't really resolve #5538 but it does mitigate it from a hang to potential misoperation
> cheap mitigation of #5538

- docs/changelog.txt
- library/modules/Job.cpp
add fields added to `job` in the dye update
If this PR makes an externally-visible change in behavior or API, please add an appropriate line to `docs/changelog.txt`.
> fix `Job::getName`

- docs/changelog.txt
- library/modules/Military.cpp
aside from the link removal stuff at the end, which might still be slightly different
Amends #5526
> Update removeFromSquad to match in-game logic

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Job.h
- library/include/modules/Units.h
- library/modules/Job.cpp
- library/modules/Units.cpp
I finally got around to following up on [this discussion](https://discord.com/channels/793331351645323264/873659717174587403/1289305706314596352) concerning `unitst::have_unbailable_sp_activities`
The motivation for this is that we now have several tools that create jobs and immediately assign them to dwarves (`idle-crafting`, `autocheese`, `immortal-cravings`). This has led to a bunch of code duplication and cross-importing between those tools. I would like to clean this up a bit by putting some of the frequently used functionality on a more solid footing and moving it into the C++ libraries.
@ab9rf It would be nice if you could take a look at `unbailableSocialActivity` and see if it needs any corrections or extensions for our purposes.
> helper functions for creating and assigning jobs

- plugins/tailor.cpp
add missing binding for second config persistence item 
improve logging
(no changelog needed, covered by prior entry)
> tailor: fixes from testing

- plugins/tailor.cpp
Reduces chattiness of logging, and make the second config persistence item actually work.
(subsumed under prior changelog)
> tailor: logging tweaks, configuration

- docs/changelog.txt
- plugins/lua/zone.lua
Reverts DFHack/dfhack#5578 - merged prematurely
> Revert "Prevent assignment of trader-owned small pets (items, not units) to pits, ponds, and cages."

- docs/changelog.txt
- plugins/lua/zone.lua
This is a mitigation for #5580 "DFhack assign function on Pen/Pastures not working".  There is further discussion in that issue.
Based on the stacktrace, the issue was apparently caused by an animal with a corrupt link to a pasture zone or to a pit/pond zone.
The animal apparently had a general reference of type `BUILDING_CIVZONE_ASSIGNED` which had a `building_id` field pointing to a building that either did not exist or was not a civzone.
This patch tests for those conditions.  When detected, the animal is assigned a status of `NONE`, which causes the animal to be entirely hidden from the assign-to-pasture and assign-to-cage interfaces.
The changes made by this patch are minimal; they load and run; they mitigate the two ways I found to trigger the issue; but they **are not …
> zone overlay -- tolerate corrupt animal-to-pasture links

- docs/changelog.txt
- docs/dev/Lua API.rst
People who search the Internet for "Dwarf Fortress Lua" almost invariably end up at our documentation site, which likely leads to unnecessary confusion. This adds a redbox notice to try to direct these people to what they're looking for.
> add link to DF wiki for DF Lua API

- library/LuaTools.cpp
- library/LuaWrapper.cpp
- library/include/DataDefs.h
- library/include/LuaTools.h
- library/include/LuaWrapper.h
this is basically catching some cases missed in #4702; in addition, these changes are necessary to allow for the type identities defined by codegen to be `const`
> add missing `const` qualifiers
