- library/modules/MapCache.cpp
Fixes #404 - Missing static variable definition crashes DFHack compiled in debug mode
> Define a static variable to fix debug mode crash.

- scripts/full-heal.lua
The Script "full-heal" only worked when passed unit id in command line. I fixed it so that it works again when selecting a unit in the GUI.
The Error was that args.unit contained nil without a id as parameter, so while the or shortcut would have worked unit.find didn't return nil but aborted instead.
Checking for a nil value beforehand fixes this so I added the check!
> Fixed error with passing nil to unit.find

- scripts/exportlegends.lua
Correct list index error which skipped export of detailed map.  Allow region-maps-only export to start from detailed maps viewscreen.  More informative error message.  Closes #445.
Also found a fixed a typo; the `info` option called the maps function instead of info export.
> Fix "exportlegends maps"

- NEWS
- plugins/trackstop.cpp
Thanks to Ramblurr for pointing this out.
> Trackstop bugfix: No longer prevents cancelling building removal.

- package/darwin/dfhack
- package/linux/dfhack
This appears to be the cause of recent problems with PRINT_MODE:TEXT on Linux.
> Revert "Log output of "dfhack" script to dfhack.log"

- NEWS
- scripts/digfort.rb
Checking file type and existence before we start avoids a few issues,
and prevents (highly) misleading feedback of "done" regardless of action
taken.  Closes #453
> Add file checks to digfort

- library/modules/Filesystem.cpp
Not sure how this made it in, but it's causing problems with PRINT_MODE:TEXT (not to mention filling up stdout.log)
> Remove output from filetype()

- NEWS
- library/Core.cpp
SDL has been reporting the modifier key state incorrectly after alt-tabbing between the DF and DFHack windows.
Fixes issue #448, though more testing is warranted.
> Repairing the stuck Alt key

- plugins/zone.cpp
When processing units(animals) for autobutchering, checks to see if the unit will not breed due to orientation issues. If the unit will not breed, it is placed into a separate list that will be processed first when creating butchering requests.
Should fix #357
> Autobutcher: prioritize non-breeders

- scripts/modtools/skill-change.lua
This is needed because the skills vector is actually sorted. Adding skill with id<last one would mess things up very badly.
> fix skill-change so it would use insert_sorted

- library/Core.cpp
- library/LuaApi.cpp
- library/include/Core.h
MOD_* constants are defined in Winuser.h on Windows, which causes problems with DFHack's modifier handling (Alt and Shift are reversed)
> Change MOD_* to DFH_MOD_*

- package/linux/dfhack
Some 64bit distros fail with errors about libpng when running df becaue of multilib issues. This
can be fixed by setting LD_PRELOAD properly, but dfhack doesn't let you dod that without manually
editing the script.
This patch includes the user specified PRELOAD_LIB if it exists in the final LD_PRELOAD value used.
> Allow user to include custom libraries in LD_PRELOAD

- Compile.rst
The GCC 4.5 changes required to build on OS X Yosemite have been merged upstream
> Point Homebrew users to homebrew/versions

- NEWS
- scripts/modtools/skill-change.lua
It was trying to set the level to the string "Proficient" instead of 5, same for every other skill level. There was no workaround, especially since it expected numbers for the value.
> Make skill-change actually work with level

- Readme.rst
- plugins/zone.cpp
Closes #554.  This changes the result of `autobutcher list-export` to be platform-independent, and match `workflow list-commands`.
> Change autobutcher export format a little

- Contributors.rst
- NEWS
- plugins/manipulator.cpp
This replaces the Profession/Squad toggle with an enum of 3 different modes: Profession, Squad or Job. Sorting and the like works with it properly (Idle has the lowest "priority" when sorting, not sure if that will be desired or not but its easy enough to rip out). Eventually it may be nice to set the color of the job to the profession it belongs to, but I'm not currently sure of the best way to handle that.
This is my first time writing any C++ code ever, so there may be better ways to do the mode switching that I am unaware of.
> Add current job as a view mode in manipulator

- plugins/autolabor.cpp
> Negative autolabor pool size uses most unskilled dwarves.

- library/LuaApi.cpp
- library/include/modules/World.h
- library/modules/World.cpp
- plugins/3dveins.cpp
- plugins/createitem.cpp
- plugins/reveal.cpp
- plugins/seedwatch.cpp
This addresses issues in several plugins (possibly scripts as well) which do not recognize certain game types as valid game types in fortress mode (particularly DWARF_UNRETIRE, which is new in 0.40.xx).
See #532
> Add gametype checks to World module

- plugins/lua/stockpiles.lua
- plugins/stockpiles/stockpiles.cpp
The code already handles stocksettings not existing for the loading half.
> plugins/stockpiles: only create the stocksettings directory when it is requested

- scripts/ban-cooking.rb
Bans cooking of specified types of items, including not-yet-discovered items of those types. For example, ban-cooking tallow at the beginning of the game bans all tallow cooking even if there is no tallow on the kitchen menu.
ban-cooking booze  - bans cooking of drinks
ban-cooking honey  - bans cooking of honey bee honey
ban-cooking tallow - bans cooking of tallow
ban-cooking oil    - bans cooking of oil
ban-cooking seeds  - bans cooking of plants that have seeds (tree seeds don't count)
> ban-cooking script

- scripts/modtools/syndrome-trigger.lua
Before, it was trying to look at the syndrome ID it didn't actually find.
> Made "could not find syndrome" error work.

- Lua API.rst
- NEWS
- library/Core.cpp
- library/lua/dfhack.lua
- scripts/add-thought.lua
- scripts/modtools/reaction-product-trigger.lua
- scripts/modtools/reaction-trigger.lua
See #548
This currently works by scanning comments for lines of the form `--@ enable = true`, for example (`--@ enable = false`  also works, if script authors want to be explicit). Feel free to suggest a better way of retrieving data from a script without actually executing it.
> Allow Lua scripts to implement enable/disable commands and specify other behavior (e.g. "module mode") that they implement

- NEWS
- Readme.rst
- scripts/burial.lua
- scripts/fix-ster.lua
Adds two scripts which have been useful to many people through my pack.
`burial.lua` is very simple; it just allows burial for dwarves (and optionally pets) in unowned coffins.  @Putnam3145 is presumably fine with this.
`fix-ster.lua` was written by Tacomagic on DFFD, and allows control of animal (and dwarven) fertility.  Very useful for livestock, or if there's some other breeding issue.  The code style might not be great, but it works and is again useful to a fair few people.
> Add scripts: burial and fix-ster

- library/PluginManager.cpp
- library/include/PluginManager.h
This allows plugins to make certain functions available to an object. It currently works much like the Lua side by returning a single object with all functions that a plugin exports available as methods.
> Plugin exports

- library/modules/Materials.cpp
- plugins/lua/workflow.lua
Changes workflow's handling of built-in plant processing jobs to understand that the results are always plants even if no specific material is set, and that they also produce seeds.
> Workflow changes for plant jobs

- plugins/workflow.cpp
Fixes #487
* This doesn't fix existing stuck jobs, in order to fix, remove repeat, cancel, add, repeat
* Most workshops worked great after this, however, I noticed my bone bolts and wood bolts still got stuck, not sure if it is the same issue
* The unk_v4020_1 field was not being reset to -1 when resuming the job.
* Updated to be reset only when the job is being resumed
* Setting it to -1 without checking sets this field on all workflow jobs, which causes a crash
* Made other calls to suspend call set_resumed rather than setting the suspend field
This is the behavior I saw for the unk_v4020_1 field:
Suspended jobs: -1
Jobs not in the top of the list but not suspended: -1
Jobs at the top of the list to work next, not suspended: A positive integer (priority of job?)
> Improved issue with workflow job being resumed but never being worked

- scripts/item-descriptions.lua
Including a short list of the screen's limitations would be a good idea, I think.
> Add format guide to item-descriptions.lua

- scripts/view-item-info.lua
Previous order of comparisons would describe any amount of strain at yield below 50000 as "elastic". Flip the order of checks and it works as intended. Seems like a simple mistake, I don't think this'll break anything else.
> Fixed elasticity descriptions

- scripts/view-item-info.lua
Turns out that *get_plant_reaction_products* is tuned to look for the specific material reaction products in the Natural Balance mod that this was originally designed around instead of looking at the basic item types.
The calls for liquid pressing, rendering, soapmaking and cheesemaking work as intended (being handled with MRPs by default), but the brewing stuff overlapped with the similar set of instructions in the next function and the milling/threshing/sugaring(?)/extracting/plastermaking were looking for tokens that just aren't there.
So what I did was comment out the addition of any DRINK_MAT material reaction products into the description and extended the mechanism at the ass-end of *GetFoodPropertiesStringList* to handle basic products other than the present booze, thread and …
> Rebuilt missing half of plant product descriptions

- CMakeLists.txt
- library/CMakeLists.txt
- library/Core.cpp
- library/DFHackVersion.cpp
- library/PluginManager.cpp
- library/git-describe.cmake
- library/include/.gitignore
- library/include/DFHackVersion.h
- library/include/PluginManager.h
This runs `git describe --tags` to produce a more descriptive version identifier, like `0.40.24-r3-155-g0fa5570` (commit 0fa5570, 155 commits after 0.40.24-r3). Currently, plugins can be loaded as long as their DFHack version matches core's, but a warning will be displayed if their commits don't match.
> Add git commit information to libdfhack-version

- library/include/DataDefs.h
This addresses #654. I think it should work in MSVC, but it should be tested before merging.
> Work around GCC enum bound checking bug

- Readme.rst
- scripts/autounsuspend.rb
- scripts/ban-cooking.rb
- scripts/exportlegends.lua
- scripts/fixnaked.lua
- scripts/unsuspend.rb
This ensures that all scripts in the general and `fix/*` directories are documented in the readme, and the existence of `devel/*` is noted.
GUI scripts are less clear, and several scripts could be moved to `gui/*`.  `dfstatus` appears to be duplicated by `gui/dfstatus`; I left this alone.  I haven't looked at plugins or builtin commands.  Some scripts that I documented also needed an initial comment, which I added in cases I noticed but didn't check for.
`exportlegends` is now compatible with `open-legends`.
> Documention fixes

- NEWS
- library/Core.cpp
- library/LuaApi.cpp
- library/LuaTools.cpp
- library/LuaTypes.cpp
- library/PluginManager.cpp
- library/include/LuaWrapper.h
- library/include/PluginManager.h
- plugins/devel/counters.cpp
- plugins/remotefortressreader.cpp
- plugins/stockflow.cpp
* load/unload/reload are no longer restricted to plugins that exist
on startup
* Names passed to DFHACK_PLUGIN must match the plugin's filename
(see remotefortressreader vs RemoteFortressReader, counters vs probe)
* `plug` output lists all plugins and state/command information
* Deleted plugins can be reloaded again if they are replaced
* load/unload/reload don't fail silently with broken plugins
* Built-in commands are recognized internally (e.g. "help help"
does not display "help is not a recognized command"), although help
for them is not yet implemented
* New command: `type` (bash-like) - shows where/how a command is
implemented
* `plug` can accept multiple plugin names
* `ls` displays more information about unloaded/unrecognized plugins
* `load all` changed to `load -all` (or `load …
> PluginManager improvements

- .gitmodules
- CMakeLists.txt
- library/CMakeLists.txt
- scripts/CMakeLists.txt
- scripts/Scripts.cmake
Repos need to include a CMakeLists.txt file with calls to the DFHACK_SCRIPTS macro, which functions similarly to DFHACK_PLUGIN. The `open-legends` script from lethosor/dfhack-scripts is included as an example.
Examples:
```cmake
DFHACK_SCRIPTS(foo.lua)
DFHACK_SCRIPTS(gui/foo.lua SUBDIRECTORY gui)
```
> Add a framework for including 3rd-party script repos

- scripts/gui/gm-editor.lua
It was broken because df.global is not a real struct and does not have ._field at all.
> Fix gm-editor to work with df.global structs

- library/modules/Items.cpp
- library/modules/Materials.cpp
This change allows a _somewhat_ more manageable filtering for 'Collect Web' material selections. Without it, every body part of every creature is available, with this addition in place it's a manageable three pages, all of actually valid items.
> Add 'undisturbed' flag to job item checks

- library/PluginManager.cpp
Commit 4fc6cb6f175aebc96bf7ec4629a90cd05b71e8ee broke binary compatibility with (third party) plugins compiled against r3 (or any develoment build from before this commit).
Specifically the renaming of `pluginmanager.h`'s `DFHACK_PLUGIN_AUX` fields `name` and `version` to `plugin_name` & `plugin_version` in https://github.com/DFHack/dfhack/commit/4fc6cb6f175aebc96bf7ec4629a90cd05b71e8ee#diff-bd71300c004474c4053e54ada7483b31L290 and corresponding changes to  `pluginmanager.cpp`'s `Plugin::load`at https://github.com/DFHack/dfhack/commit/4fc6cb6f175aebc96bf7ec4629a90cd05b71e8ee#diff-bcb993821b53968bc228a308c6193963L229 cause errors on load for 'old' plugins. 
One **popular** example would be *twbt* from LNP ;). Last available version is compiled against r3, which means it only has fields …
> Allow loading (external) plugins compiled against r3

- scripts/gaydar.lua
Since there was some confusion in FOTF that was caused by the lack of checking for that in gaydar.
> Add indeterminate orientation to gaydar

- CMakeLists.txt
passing -D_GLIBCXX_USE_CXX11_ABI=0 to disable new C++11 name mangling and remain compatible with DF.
> Re-enable GCC 5 compilation for OSX and Linux

- library/Core.cpp
For example, `./dfhack +echo foo` would be equivalent to running `./dfhack` and then typing `echo foo` into the console. uses shell argument splitting, so `./dfhack +somecommand "foo bar" baz` does the right thing.
See DFHack#755.
> vim-style +args

- docs/Compile.rst
Needing cmake.portable instead of cmake
> Updated Windows compile docs

- scripts/autolabor-artisans.lua
alcohol has no quality level, so brewer skill has no effect on output quality
> autolabor-artisans.lua remove brewer skill

- plugins/blueprint.cpp
Without this, `std::find` is not found, leading to the same problem as in https://stackoverflow.com/questions/27996423/how-do-i-pass-a-constant-string-vector-to-a-function-for-string-matching .
> blueprint: fix compilation (i.e. undefined find)

- scripts/ban-cooking.rb
brew: bans cooking of plants and fruits that can be made into alcohol
(assuming default brewing reaction)
mill: bans cooking of plants that can be milled.
thread: bans cooking of plants that can be turned into thread.
milk: bans cooking of animal liquids that can be turned into cheese
(assuming default cheesemaking reaction)
> Add brew, mill, thread, and milk to ban-cooking. See #796 and #795.

- library/Process-linux.cpp
valgrind replaces the readlink system call, but not the open system
call. By calling readlink first, we guarantee that /proc/self/exe is the
actual Dwarf Fortress executable and not the valgrind executable.
See also: https://bugs.kde.org/show_bug.cgi?id=86921
> allow dfhack to run inside valgrind

- plugins/lua/stockflow.lua
The manager can now specify each type of craft individually, as well as in general.
There may be a better justification for not allowing pearl and shell scepters, though.
> Updating Stockflow for version 42.06

- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/manipulator.cpp
histfig.entity_links vector is one of things that determines ability to set unit's labors.
If it contains histfig_entity_link_memberst with entity_id equals to ui.group_id - player will be able to set labors in vanilla v-p-l menu otherwise menu shows "No labors available" text(assuming all other requirements are met).
histfig.entity_links vector also contains other types of entity links including histfig_entity_link_former_memberst. So type should be checked.
No more need in isOwnRace check since you can have not own race citizens.
flags2.bits.visitor and  antity links should be checked instead.
flags3.bits.ghostly should be checked - ghosts cant be edited in vanilla way, and they are not flags1.bits.dead.
Also added new 0.42.x skills to table.
Rebase fixupped one error, thanks warmist …
> Manipulator update and fix

- library/modules/Job.cpp
if job cannot be assigned right now, game puts it in `df.global.world.job_postings` vector
when job finally can be done, game removes job from postings and clears its `posting_index`
that index should not be cloned by job-duplicate(new jobs(added by vanilla way) have that value -1 always anyway)
invalid (because another job will have that index or no posting with that index will be  present in postings vector) `posting_index` causes the new job(and other jobs after it in the workshop's joblist) to be ignored(in the best case).
> fix job-duplicate bug (ignoring cloned jobs with posting_index)

- library/modules/Units.cpp
Fixes a lot of issues where plugins ignore non-dwarf citizens and work
with dwarf mercenaries and bards that are not actual citizens.
May be it should be renamed, or all those plugins should be fixed to use another method. Because in-game "citizen" term includes mercenaries, bards, scholars, that cannot be assigned to labors and noble positions (hit u in main dwarf mode to see list of "citizens").
> fix Units::isCitizen

- scripts/modtools/force.lua
Avoid segfault in case of invalid or abscent civ argument
Remove CivAttack. It was broken in 40.0X
> fix modtools/force.lua

- library/include/df/custom/building_handler.methods.inc
- library/include/df/custom/machine_handler.methods.inc
These errors:
> 07:12 < _Q> G:\dwarfort\dfhack\library\include\df/static.ctors.inc(8103): error C2248: 
>             'df::building_handler::building_handler' : cannot access protected
> 07:12 < _Q> member declared in class 'df::building_handler' 
>             [G:\dwarfort\dfhack\build\VC2010\library\dfhack.vcxproj]
> 07:13 < _Q> same for machine_handler
Fixed by making world friend of machine and building handlers. (fix requires change in structures: https://github.com/DFHack/df-structures/pull/99)
> Fix build errors

- plugins/fastdwarf.cpp
fix https://github.com/DFHack/dfhack/issues/835
Mother has `flags1.bits.ridden` 
Baby has `flags1.bits.rider` and `relations.rider_mount_id`
And it looks like all riders are stored in `world->units.other[units_other_id::ANY_RIDER]`
So I propose check unit's `flags1.bits.ridden` and teleport units from `world->units.other[units_other_id::ANY_RIDER]` with matching `relations.rider_mount_id` to its pos.
> fix teledwarf bug (leaves babies lying on ground)

- scripts/gui/mod-manager.lua
it fails if mods folder does not exist
> Fix gui/mod-manager

- scripts/modtools/item-trigger.lua
This should allow item-trigger to correctly handle items lacking a subtype.
> item-trigger.lua fix

- NEWS.rst
- scripts/gui/gm-editor.lua
Allow to insert ints and other simple types. Also allow inserting of same base type as the container.
Waiting for better message ideas. Would like to merge before next release.
> Gm editor changes

- scripts/gui/create-item.lua
When -multi option is selected, gui/create-item doesn't set quality neither on stackable nor unstackable items. Fixed this quirk.
No refactoring or optimizations. Just moved a variable and added code inside the createItem function.
> Fixed quality in gui/create-item with -multi.

- scripts/item-descriptions.lua
Meph summarises the raw changes [here](http://www.bay12forums.com/smf/index.php?topic=158038); the relevant bit in this case is two new `ITEM_TOOL` subtypes to describe.
Also removed the leading space in `HIVE`
> Add new item descriptions for DF 43.01

- plugins/search.cpp
The list of workers in the workshop profile page can take nearly the full height of the screen.
> Moving a search option to the bottom of the screen.

- library/include/df/custom/knowledge_scholar_category_flag.methods.inc
Instead of having to go through a bunch of one-bit tests, this means the knowledge type can be used as an enum with switch statements and all the extra compiler stuff that comes with that.
Requires DFHack/df-structures#126
> knowledge category flag

- depends/tthread/fast_mutex.h
- depends/tthread/tinythread.cpp
- depends/tthread/tinythread.h
- library/RemoteServer.cpp
1. update to tinythread version 1.1, which provides a detach method
2. move the thread disassociation to the join function, which allows
attached threads to be joined even after they finish (this was the main
leak)
Also update RemoteServer.cpp to detach threads and delete the thread
objects instead of leaking them (although they are much smaller than the
actual threads).
> tinythread memory leak

- plugins/lua/stockflow.lua
SpinThread jobs now get the proper material category flag, and metal mechanisms can be ordered.
> Stockflow reaction updates

- docs/Core.rst
- docs/Plugins.rst
I started by adding docs for the command syntax introduced in #767, but realised that most of the "misc notes" were actually about how to use commands and their syntax.  So that's a section now, and I did some minor rearrangement of the table of contents too.
This leaves the Misc. Notes section at the end as a placeholder with just two entries, both of which have associated issues to resolve them.
I also confirmed that the `+`-args work as expected on Windows before adding the docs.
> Core.rst: document how commands work and are used

- dfhack.init-example
After updating the extra init file in my pack, I realised that many of
the changes could be merged into the standard init.
This enables a few more UI improvements, adds neglected keybindings, and
removes the roses-init and binpatches sections (third-party only and
obsolete respectively).
> Update the example init file

- docs/Plugins.rst
I never did get around to adding basic docs for the Professions feature of Manipulator. So, I guess here it is?
I'm not that familiar with RST but I think I did it right.
> Add documentation for manipulator professions

- NEWS.rst
- conf.py
- docs/Plugins.rst
Closes issue #971 - DFHack/scripts#5 is the complementary pull.
This pull:
* adds a new directive to Sphinx, for keybindings, with most information pulled from `dfhack.init-example`
* automatically adds the directive to script documentation if there is a keybinding at build time
* adds the directive to plugin docs as appropriate (by hand)
* causes a build of the docs to fail if there is an undocumented keybinding, and warns if a documented keybinding no longer exists (which also fails the Travis build)
* updates `NEWS.rst`, including for `dwarfvet`
* removes an obsolete special case from `autodump` (since keybinds may now have spaces in the command if quoted).  Further work, to remove the `autodump-destroy-item` case, would be welcome but is beyond my C++ skills.
> Document keybinds in dfhack.init-example

- docs/Plugins.rst
- plugins/labormanager.cpp
This adds documentation for labormanager and also a minor patch to handle leather crafts.
Closes issue #1004.
> Labormanager - docs and a minor patch

- plugins/labormanager.cpp
I did test that furniture hauling is responsible for building instruments
> make labormanager know building instruments is furniture hauling

- plugins/labormanager.cpp
Trap components were left to mechanic labor, which stalled my only carpenter's workshop when trying to craft a wooden corkscrew. Screw pumps would not get built unless the pipe section's material's labor matched the block's, and other multi-material constructions had similar problems. This fixes these issues.
> Labormanager trap components and constructions with multiple materials

- plugins/labormanager.cpp
This corrects an error introduced in #1025.
> labormanager: fix deconstruction of buildings containing items

- library/LuaApi.cpp
- library/include/modules/Job.h
- library/modules/Job.cpp
Job remove eliminates a job's worker & holder references, if any, puts
the worker on cd, if appropriate, removes the job's postings, eliminates
the job from the global linked list, and then finally deletes it.  This
code was tested by incorporating it into autochop and it does make the
plugin work.  However, chop jobs don't have holder building references,
and anyway, with DF being 90% edge case by volume, this could use a heck
of a lot more testing.
I saw elsewhere code that prevented worker removal if the job was a
special job, and that made me feel funny so I made the job remove method
not work if the job is a special job.
> Add job remove method

- plugins/labormanager.cpp
This patch adds the deconstruct labor for constructed instruments (missed in #1020)
> labormanager: add deconstruct labor for constructed instruments

- plugins/labormanager.cpp
StoreItemInVehicle requires the labor appropriate to the item being
stashed
> labormanager: fix StoreItemInVehicle labor inference

- plugins/ruby/ruby.cpp
This surreptitiously forces ruby to use 64-bit longs instead of 32-bit longs on Win64, solving most if not all of our win64 ruby crashes.
Should close #1023.
> hack to make ruby work on win64

- depends/tinyxml/tinystr.cpp
- depends/tinyxml/tinystr.h
- depends/tinyxml/tinyxml.cpp
- depends/tinyxml/tinyxml.h
- depends/tinyxml/tinyxmlerror.cpp
- depends/tinyxml/tinyxmlparser.cpp
Upstream has moved onto tinyxml2, so this is likely to be the last release of the original tinyxml (2.6.2 came out in 2011). dfhack should therefore probably ship 2.6.2, since it's unlikely there will ever be future fixes to this code. The upstream changelog (taken from "changes.txt" in upstream tarball) contains many bugfixes and is included in the commit message below.
This PR was originally motivated by #1009. I poked around the git history and it seems that, at one point, tinyxml was updated to [2.6.1, but then reverted soon after](https://github.com/DFHack/dfhack/commits/v0.31.25/library/depends/tinyxml) way back in 2011. The comment doesn't explain why, though, and I tested that dfhack runs successfully with the newer tinyxml substituted instead. (I generated a world and started a …
> Update bundled tinyxml version from 2.5.3 to 2.6.2

- plugins/ruby/CMakeLists.txt
If DOWNLOAD_RUBY is set to OFF, the build will not attempt to download a prebuilt libruby.so and not fire a warning that one is not present. This may be desired if one wants to link dfhack against a newer system
libruby.so, now that dfhack supports ruby 2.x and also supports linking against system libruby (at least, on Linux), as per this recent [commit](https://github.com/DFHack/dfhack/commit/df9b5bca7311489748ab100dfc51080841c3f196).
This also allows the dfhack build to proceed without network access (once all submodules have been fetched), which at least some Linux distributions, like Fedora, require.
By default DOWNLOAD_RUBY is set to ON, so this should not change the behavior of default builds.
I tested that when DOWNLOAD_RUBY is set to OFF, dfhack still launches and that the Ruby …
> Add DOWNLOAD_RUBY option to Ruby plugin cmake, defaulting to ON

- README.md
Github's markdown parser does not permit newlines between link titles
and link text. This change removes the newlines, resulting in a less
pleasing source, but one which renders when viewed on github.
Github also requires a space between the '#' and text of headings, so
we fix that, too.
> README.md: Fix broken markdown links and header.

- README.md
The README is pointing to the old thread, which in turn leads to an old download.
> Fix forum thread link in README.md

- plugins/autolabor.cpp
This reduces the number of haulers. Another solution would be limiting the number of haulers to the number of possible haulers.
> autolabor: Fix an array bounds overrun when assigning haulers while traders are active.

- plugins/strangemood.cpp
missing "break;" statements in deep material item searches
> Fix silly error in strangemood plugin

- library/Console-windows.cpp
This patch:
- Replaces `long` with `intptr_t` for a OS handle. In theory, this could cause a crash at startup in 64-bit in the unlikely event that Windows allocated a handle not in the first 2GB or last 2GB of virtual memory. I've never seen this happen, but it is in theory possible.
- In one place makes a downcast from `int` to `SHORT` explicit.
> Fix a couple MSVC warnings

- plugins/lua/luasocket.lua
Did not correctly detect when you typed in a number instead of pattern.
> Fix luasocket receive with byte count

- plugins/listcolumn.h
This was preventing my TwitchName plugin from compiling on Linux - `list.add(ListEntry<T>(x,y))` would error out with `invalid initialization of non-const reference of type 'ListEntry<T>&' from an rvalue of type 'ListEntry<T>'` (though curiously it worked just fine on Windows).
> listcolumn tweak for GCC

- plugins/stockpiles/StockpileSerializer.cpp
When I save and load stockpile settings with stockpile management plugin, then saved barrels count will be loaded in bins and barrels are zero. So I think this change should correct it.
> max_barrels was serialized on max_bins position

- library/Core.cpp
- library/include/Core.h
Addresses https://github.com/DFHack/dfhack/issues/720
Output:
cl is not recognized. Possible completions: cls cleanconst clean cleanowned clear-smoke
di is not recognized. Possible completions: die disable digexp digcircle digFlood diggingInvaders digfort
he is not recognized. Did you mean help?
... etc.
Commands still work correctly. (Tested with cls, help, die, etc.)
Happy to take feedback!
> Autocomplete built in commands (die, etc.)

- library/Console-windows.cpp
Embarrassing!
It turned out that when the screen buffer gets full, the "new" console output command adds a line feed the "old" one didn't, so typing at the prompt caused a line feed for each letter, landing each one on a new line (without a carriage return, so the X position was the correct one).
I tried a fancier correction than the one here, but it didn't work out, possibly because I don't know what happens with line numbers as the buffer is full and starts to scroll.
The solution here essentially uses the original solution for blanking out the (remainder of) the line and the new one for the "business" output.
As can be seen, a semicolon has also been removed from a #define (there's a semicolon after its single use anyway).
The regressions of the previous attempt have been reperformed …
> Blocked errant line feed at full buffer

- library/RemoteTools.cpp
This was breaking things before that relied on dwarf mode being set, and the fortress was unretired.
> add more world mode options to world info

- library/modules/Gui.cpp
add new cases for Gui::getSelectedUnit: (these cases are mostly from gui/unit-info-viewer.lua)
- report list, 
- combat log list, 
- military screen, 
- unit health, 
- unit custumize, 
- assigning to cage, 
- viewing cage, 
- pitting, 
- penning, 
- burrows, 
- look at corpse, 
- look at named corpse piece, 
- look at named spatter.
This is a better implementation of a closed pull request https://github.com/DFHack/scripts/pull/44 that made the same change in lua for specific scripts.
> More cases for Gui::getSelectedUnit

- dfhack.init-example
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/pausing-fps-counter.h
This FPS counter only counts frames when the game is not paused.
This commit enables it in dwarfmonitor by default. But it is only shown if [FPS:YES] is set in init.txt.
Its positioned on top of the default FPS counter (when its pushed by the "*PAUSED*" text).
It does not support changing FPS:YES at runtime.
> FPS counter that does not need to stabilize after unpausing

- library/lua/gui.lua
It was used in different order than the return happened.
> Fix parse_inset in gui.lua

- library/modules/Gui.cpp
It seems unlikely we will end up on an `df::viewscreen_announcelistst` without a `world`. But we perform the same check elsewhere, and segfaults are bad.
I also verified that most cases in Gui::getAnyUnit still work in 44.10 (could not figure out what `df::viewscreen_dungeon_monsterstatusst` is).
> Fix unlikely GUI::getAnyUnit segfault

- library/LuaApi.cpp
`designateRemove(pos)` cannot be invoked because it isn't registered.
> enable lua api construction functions

- library/lua/syndrome-util.lua
The presence of syndrome data in unit.syndromes.active generates corresponding wound data in unit.body.wounds. This wound data acts to produce all of the syndrome's actual effects, including but not limited to flag changes, interaction abilities, body transformation and display name alterations. Wound data persists when syndrome data is cleared from unit.syndromes.active. Since syndrome-util did not touch wound data at all, the erase function was completely ineffective at actually removing syndromes.
Note that syndromes also generate a bunch of data in the historical figure information of units. I have observed that this historical data is sufficient to restore the syndrome in a unit following map reload (at least in adventure mode), so its clearance (which needs to also include removal …
> syndrome-util: added function to remove syndrome wound data

- package/linux/dfhack
First, simplifies the quoting of the environment variables. Then sets
startup-with-shell to off so that gdb does not start bash first; if it
starts bash ld will see the LD_PRELOAD and try to load libdfhack.so
into the bash process, which is not what we want.
We could instead use an exec-wrapper, but that would be a slightly
larger change and we don't need any of the convenience features that
using a shell gives us (argument expansion and redirects, basically).
> makes dfhack -g work correctly

- LICENSE.rst
- docs/Lua API.rst
- docs/changelog.txt
- library/lua/profiler.lua
Lua profiler module is pure lua profiler implementation. It support time based and call entry exit based profiling. The base profiler code from http://lua-users.org/wiki/PepperfishProfiler required some porting to lua 5.3 and dfhack specialization.
While I ported the code to dfhack I noticed that profiling hooks looked like doing a lot of unnecessary work. I decided to rewrite profiling hooks in hopes that lower profiling costs would improve profiling statistics quality.
> Add Lua profiler module

- docs/Authors.rst
- plugins/buildingplan-lib.cpp
- plugins/buildingplan-lib.h
- plugins/buildingplan.cpp
Fulfills feature request #1274
Additionally, made it so one can set the minimum quality to Artifact (if it was intentional that buildingplan did not allow for placement of Artifact furniture, I can quickly fix that up.)
Only built/tested on Windows, but the scope of the changes is pretty small.
(Not sure where to drop the notice in the changelog.)
> Add 'Max Quality' setting to buildingplan

- .ycm_extra_conf.py
YCM flag function returning None result an error from YCM python code
everytime a file is opened. The None return can happen if database
lookup fails for any reason. To let YCM have resonable flags without
database entry the .ycm_extra_conf.py can include default fallback
flags.
> YCM fallback defaults if database lookup fails

- CMakeLists.txt
- depends/protobuf/CMakeLists.txt
- plugins/Plugins.cmake
All platforms seems to either have compiler supporting c++14. Windows
already requires msvc2015 that supports c++14 which should make it
minimal issue to require c++14 support from all compilers because gcc
is pretty easy to upgrade.
I decided to make the change and submit the pull request to raise discussion if there is any setup blocking the change. I tested it quickly by creating a new pocket world and making a very short embark to there. I didn't notice any issues which at least shows most common features work with c++14 selected for gcc.
> Request c++11 support from compilers (through cmake)

- package/linux/dfhack
I have made a few modifications to my dfhack script. Here are modifications if they look like something that would help others too.
I didn't include ltrace change because I don't know setup that would feel like useable. I either get very slow execution or not enough information. A compromise could be allowing the -x argument of ltrace to be passed for dfhack. But I don't know if it can be done with a simply change.
> Start script additions strace, gdbserver and df arguments to gdb

- depends/jsoncpp/jsoncpp.h
Passing a 64bit integer to Json::Value fails to find matching. Even
tough long long int is also 64bits gcc considres long long int different
to long int. But fix can't be as simple as removing an long from type
because that would reduce 32bit builds to have only 32bit maximum int
size. But standard offers fixed width integer types that can be used to
get correct underlying type depending on platform.
> jsoncpp: Fix (U)Int64 to long int on 64bit linux

- library/MiscUtils.cpp
vsnprintf man page claims:
"If an output error is encountered, a negative value is returned."
That means we has to call vsnprintf twice at most to have whole output
written to a string. But in case of error we return an empty string.
The code also optimizes an expected common case of outputting single
line with a small stack allocated buffer. If the stack buffer is too
small then it uses std::string::resize to allocate exactly enough memory
and writes directly to std::string.
Second call could use vsprintf because memory is known to be large
enough. But I think that difference isn't detectable outside micro
benchmarks.
> Make stl_vsprintf return if there is an vsnprintf error

- docs/changelog.txt
- plugins/uicommon.h
Inventory items have stale position information. The coordinates can be
very old if item is owned and continuesly carried for long time. The fix
checks if item is carried. To avoid filtering carried items that are
assigned (containers) to the stockpile the assignment needs to be
checked.
Fixes #1288
> Fix stockpile inventory not to include inventory items

- docs/changelog.txt
- library/include/modules/MapCache.h
- library/include/modules/Maps.h
- library/modules/MapCache.cpp
- library/modules/Maps.cpp
While I was implementing the fix I decided to make a minor change to index_tile. I tough that index_tile should automatically determine return type from the array element type because c++11 allows it easily. That change would conflict with the fix so I included it as a separate commit to same pull request.
The map_block->designation.{dig,smooth} are reset to zeros when a job
posting is created for the designation. The job is then used to override
the designation state in the map_block. To make the new designation set
propogate to jobs the job structure would require updating. The update
would be possible a complex operation. The simple alternative is to
remove the job and let df create a new job in the next tick.
Fixes #1229
>  Update jobs when committing MapCache changes

- CMakeLists.txt
- library/Console-posix.cpp
- library/Console-windows.cpp
- library/Core.cpp
- library/LuaTools.cpp
- library/PluginManager.cpp
- library/RemoteTools.cpp
- library/include/Core.h
- library/include/LuaTools.h
- library/include/RemoteTools.h
- library/lua/utils.lua
- plugins/Brushes.h
- plugins/liquids.cpp
- plugins/mode.cpp
- plugins/tiletypes.cpp
I noticed that console code doesn't support multibyte characters at all. This may lead messed up console state and invalid multibyte sequence passed into command handlers. I decided to fix the input handling to keep console state match printed characters and prevent any partial multibyte characters passed into command handlers.
While I was implementing the multibyte support I noticed select was getting a suboptimal nfds parameters (first).  The large nfs parameter doesn't affect anything but it is minor performance issue because kernel has to scan up to nfds -1 FD bits in the fdset.
Then I also noticed the data race potential in the shutdown code. I decided to implement a simple fix by joining the thread before Core frees or cleanups any state.
Windows change is untested. Can someone test …
> Multibyte console support for posix and fix potential data races in console shutdown

- library/LuaApi.cpp
- library/include/MiscUtils.h
- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/autochop.cpp
- plugins/buildingplan.cpp
- plugins/command-prompt.cpp
- plugins/dwarfmonitor.cpp
- plugins/embark-assistant/finder_ui.cpp
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-tools.cpp
- plugins/hotkeys.cpp
- plugins/manipulator.cpp
- plugins/stocks.cpp
Showing a screen which is already visible would mess up the linked list.
A simple check to prevent breaking the linked list is to let
Screen::show check if screen is in a list while looking for the parent
screen.
Fix unlikely memory leaks if Screen::show fails  …
The Screen::show takes ownership of the screen pointer. I decided to
switch the parameter to std::unique_ptr to make the pointer ownership
explicit. The unique_ptr then provides automatic screen destruction in
Screen::show unless pointer is inserted or is already in the linked list
that is managed by df.
> Fix for Unlikely screen show memory leak fix and check to avoid breaking the screen linked list

- library/include/Console.h
- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/devel/kittens.cpp
- plugins/devel/zoom.cpp
Reasons for changes:
- Fix devel plugin linking in linux
- Fix a few obvious data races in kittens
- nyan looked suspicious that it could prevent clean shutdown if iothread.join() is called (#1304 related)
> Kittens data race fix and zoom linking issue. ie devel plugins fixes

- library/Console-posix.cpp
- library/Console-windows.cpp
- library/Core.cpp
- library/LuaTools.cpp
- library/include/Console.h
- plugins/Brushes.h
- plugins/liquids.cpp
- plugins/mode.cpp
- plugins/tiletypes.cpp
@lethosor Is this closer to behavior you expect from lineedit?
Windows seems to not to support ctrl+c at the moment.
> Allow canceling lineedit with ctrl+c

- library/MiscUtils.cpp
I noticed an extra null when trying to grep dfhack.run ls output.
std::string manages null byte at end(). Pre C++11 didn't require null
termination for std::string but C++11 add the null termination to make
c_str() and data() truely const. It is undefined behavior to modify the
internal null termination but this modification sets the null to null.
> Remove null byte from string length

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/dfhack.lua
I often want to see multiple items quickly when trying to figure out
what states actually matter to an issue that I debug. I decided to make
it easier to quickly dump df structures with substructures and
containers. It will generate large amount of data which can be sometimes
slow to process manually. But processing can be automated using
dfhack-run lua ^<df data to inspect> and pipe to other tools (eg grep,
sed, perl, sort, uniq etc)
No changelog or documentation yet. I can add them when this looks acceptable. I still wonder if I should change some.
I'm not entirely happy how I formatted object keys.  I wanted to use format that is very close to printall(table) format. Basically only adding recursion to subjects and pointers. The original printing code used format that closely matched …
> Add dfhack.printall_recurse to quickly print df containers

- docs/changelog.txt
- library/include/Core.h
- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/command-prompt.cpp
command-prompt viewscreen may affect command execution if they are
looking for UI state. To make commands execute simillary to hotkeys or
console commands the viewscreen needs to removed from the top position.
Fixes #1194
I'm unsure if LowerScreen should be part of Core or module/Screen. I first put it to the Core but I can moved it to Screen if it sounds like a better place for this functionality.
What about lowering position? I only lower it a level but it might be better to lower to bottom (gview->view.child = screen_)
> Temporary lower command-prompt when executing the command

- library/Console-windows.cpp
I messed up the check. I forgot that windows commonly has opposite
return values to posix and failed to check it from documentation.
Fixes #1345
Still untested as I don't have windows machine.
> Fix windows ReadConsoleInput return value check

- depends/CMakeLists.txt
Removes the lib and include directories from the DFHack package.
~~Removes the status message that lists the jsoncpp version number.~~
> Exclude jsoncpp default CMake targets.

- library/Console-posix.cpp
plen+cooked_cursor==cols => begin = -1 which is passed to substr. The
sign is incorrect as code should be removing a character from begin
instead of trying to add a character.
> Fix crash when editing lines that are exactly console width

- docs/changelog.txt
- library/Core.cpp
> Fix windows crash when _exit calls static destructors in dll unload

- library/include/modules/MapCache.h
- library/modules/MapCache.cpp
To make sure that DF generates jobjs from desgination as soon as
possible the dsgn_check_cooldown should be reset when designations
change.
Combined with a janitor change:
Use constexpr to prevent attempts of linking static variable
> Reset dsgn_check_cooldown in Block::write

- plugins/ruby/codegen.pl
- plugins/ruby/ruby-autogen-defs.rb
Calling convention for memory return is that caller allocates (in stack)
memory to hold returned object. Then caller passes the pointer to callee
as implicit first parameter.
references:
https://github.com/hjl-tools/x86-psABI/wiki/X86-psABI
https://msdn.microsoft.com/en-us/library/7572ztz4.aspx
Fixes #1209
> Fix memory return calling convention in ruby bindings

- .gitignore
- CMakeLists.txt
- CMakeSettings.json
I tried to make the GCC settings as generic as possible, so anyone with SSH credentials configured in Visual Studio should be able to use this without modification.
I didn't add anything to help with starting the debugger, but that would be a good future addition. Microsoft's documentation, as always, is confusing and contradictory.
> Add CMakeSettings.json for MSVC 2017.

- library/Hooks-windows.cpp
> Use std::call_once to ensure thread safety for windows sdl hooks

- plugins/labormanager/joblabormapper.cpp
This adds job labor inference support for craft item from pearl jobs, and will close issue #1162.
> (labormanager) add support for craft item from pearl jobs (fixes #1162)

- plugins/labormanager/labormanager.cpp
I am fairly certain that Toady changed how cleaning jobs are spawned; this makes it so that cleaning actually happens with labormanager.
> labormanager: assign more dwarves to cleaning

- plugins/lua/cxxrandom.lua
There's been a print line enabled that should have been disabled long ago. Basically just getting rid of a message that floods the console.
> [Release] cxxrandom v2.0.1

- plugins/mousequery.cpp
This changes mousequery to use the map dimensions returned from Gui::getDwarfmodeViewDims() to determine map boundaries rather than some complicated (and inconsistent) math with other fields. Granted, mousequery predates the map_x2/y2 fields. However, TWBT breaks the old checks because it modifies the result of getMousePos() to support different map tile sizes. In the case where the map tiles are larger than the surrounding tiles, mousequery would think that the mouse wasn't close to the bottom/right edges of the map when it actually was.
This hopefully fixes some edge detection issues reported on the forums, as well as potential similar issues with other features (tracking and right-button scrolling).
> mousequery map boundary detection fixes

- plugins/ruby/unit.rb
Have been messing with this function in the dfhack repl and when it returns nil it's hard to know what that means unless you have also already read the code. So this handles a couple spots in `unit_ishostile` that previously just returned false-ey `nil`s to return `false`
> Make unit_ishostile always return a non-nil value

- CMakeLists.txt
- depends/lua/CMakeLists.txt
- depends/lua/include/dfhack_llimits.h
- depends/lualimit.h
- library/Core.cpp
- library/RemoteServer.cpp
- library/include/Core.h
- library/include/RemoteServer.h
Make lua data race free 
Fixes tsan trace report between lua viewscreen and other threads running
lua without CoreSuspender lock. But I would assume similar races exists
when using lua from console thread, remote thread and vmethods same time.
Fix data race between threaded init and EventManager
The initial run_dfhack_init loads shared state information that is used
by EventManager when state changes. There is a small risk that
EventManager can handle events while run_dfhack_init is still running.
Make ServerMain and ServerConnection data race free
RemoteServer and PluginManager side would need complete redesign to be
data race free and concurrent. But as that would be unlikely to be
required from DFHack I decided simpler solution that is fixing data
ownership to a thread and all …
> Tsan race warning fixes

- library/modules/Buildings.cpp
- library/modules/EventManager.cpp
- plugins/devel/eventExample.cpp
The pointer to the building ID was sometimes not dereferenced properly. Addressed by switching to an ID cast to a pointer type for consistency with other types of events.
(Note: not sure if this will reintroduce warnings that #1253 and 19695b4ee7e8b370c8ce53aa2dcd399e1e9ca94d fixed, hence the PR)
Fixes #1434
Ref #1003 (19695b4ee7e8b370c8ce53aa2dcd399e1e9ca94d)
Broken in #1253 (a7dfacd1c57490d08fc92a43eea963cff47c05eb)
> Fix EventManager building ID type

- plugins/dwarfmonitor.cpp
This needs more CoreSuspends but they are needed either way. This way
you can access other script environments and access this plugin enviroment
from lua.
> Change dwarfmonitor to use global lua state.

- plugins/devel/CMakeLists.txt
- plugins/devel/tailor.cpp
This devel plugin (semi)automates clothing management in a fort.
This is specifically here because neither the in-game manager nor workflow can detect clothing size. Now that forts routinely have humans in them, it is becoming tedious to keep around enough human-sized clothing to keep human residents from going naked.
Still WIP at this point; pull request at this point mainly for purposes of code review. There are several hardcoded choices in the code (material choice order, thresholds) that I'd like to break out as runtime options.
> Add "tailor" plugin, to provide clothing management

- docs/changelog.txt
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/embark-assistant.cpp
- plugins/embark-assistant/finder_ui.cpp
- plugins/embark-assistant/finder_ui.h
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/overlay.cpp
- plugins/embark-assistant/overlay.h
- plugins/embark-assistant/survey.cpp
- The optional 'fileresult' parameter causes the plugin to read the saved search profile, perform a search (twice) and then write the number of matching world tiles to the file <DF>/data/init/embark_assistant_fileresult.txt. This file was deleted when the plugin was started with this parameter.
Intended usage is with an external harness (no relation to the plugin at all) that generates worlds, searches them, and selects the ones with matches.
- Improved world tile traversal logic to speed up the second search onward by skipping moving to some tiles if not needed.
> Added 'fileresult' optional parameter, improved world traversal

- library/LuaApi.cpp
- library/include/MiscUtils.h
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader/remotefortressreader.cpp
This returns the physical unit description seen on the unit screen, e.g.
> His very long sideburns are braided.  His very long moustache is arranged in double braids.  His very long beard is arranged in double braids.  His hair is clean-shaven.  He has a scratchy voice.  His free-lobed ears are splayed out.  His nose is narrow.  His lips are very thin.  His nose bridge is slightly convex.  His dark peach skin is slightly wrinkled.  His emerald eyes have slightly thin irises.  His hair is ecru with a touch of gray.
There's no easy way to reproduce this string directly from the body information, as there's a substantial amount of logic that goes into deciding what appears in this string and in what order.
Requires a new symbol in symbols.txt, which I've currently only found for macos x64 …
> add Units::getPhysicalDescription

- docs/changelog.txt
- plugins/devel/CMakeLists.txt
- plugins/getplants.cpp
I've been unable to identify where DF stores information about actual growths on plants, and so the correction only removes plants where growths are out of season, but not those already gathered.
(#1479)
> Partial correction of issue 1479 and added verbose flag

- plugins/devel/CMakeLists.txt
- plugins/devel/autofarm.cpp
This reimplements autofarm in C++, using the biome inference module that was added in July to properly determine crop assignments on surface farms.
This replaces the Ruby autofarm script which does not work correctly (it never has) and which should be deleted; however, we can do that separately after this is approved. I find pull requests across multiple modules confusing.
Fixes #1144
Fixes #1421
> Autofarm script reimplemented correctly in C++ 

- library/Core.cpp
exit code `'f'` (102) is so the test script can detect it.
> exit if a fatal startup error is encountered while in headless mode

- library/modules/MapCache.cpp
Definition is required even for constexpr variables in some compilation
setups (e.g. debug builds).
fix #1495
> Define MapExtras::BiomeInfo::MAX_LAYERS

- library/lua/dfhack.lua
Objects with links like `job` output way too much. With this change, it's possible to provide an optional filter and exclude the `list_link` (and other stuff).
```
[lua]# j = dfhack.gui.getSelectedJob()
[lua]# printall_recurse(j, {[tostring(j.list_link)]=true, [tostring(j.pos)]=true})
```
>  allow custom filter in calls to `dfhack.printall_recurse`

- library/lua/gui/widgets.lua
Using search feature of `FilteredList` with plain string choices was throwing errors :
```lua
widgets.FilteredList { choices =  { "foo", "bar" } }
```
> ./hack/lua/gui/widgets.lua:795: bad argument #1 to 'match' (string expected, got nil)
Inside `FilteredList:setChoices`, choices list is correctly given to `self.list:setChoices` but `self.choices` isn't updated afterward and thus not correctly formatted. (_e.g._ `"foo"` isn't formatted to `{text = "foo" ...}` )
> Fix widgets.FilteredList widget search on plain string choices

- library/DataDefs.cpp
While debugging further (see debugging session bellow), I found that calling `tag_container_type->getFullName(nullptr)` will always returns only the container name with `void` as its item, so I change this to call `tag_container_type->getFullName()`.
Also, it seems in this particular case that the container is a `vector<char>`, so I excluded this one also from the if (where we assume the container contains a struct ?).
Anyway, I may not really know what I am doing, but it fixes #1514 , so it works now and I had fun doing it :)
```
(gdb) info locals
__PRETTY_FUNCTION__ = "const DFHack::struct_field_info* DFHack::find_union_tag(const DFHack::struct_field_info*, const DFHack::struct_field_info*)"
tag_candidate = 0x7ffff7f3f780 <df::viewscreen_petst_fields+96>
container_type = <optimized out> …
```
> getFullName of the container AND the item, also exclude container of char

- plugins/tweak/tweaks/embark-profile-name.h
This changes the embark-profile-name tweak to remove the undocumented abort key and reenable the abort key shown in game.
Fixes #1532
> Update embark-profile-name tweak

- plugins/search.cpp
This PR adds search to both the conviction and interrogation selection pages on the justice screen. 
Compiled and tested on Linux64.
Depends on DFHack/df-structures#391
> Add search to justice screen

- docs/changelog.txt
- plugins/manipulator.cpp
Display the intrigue skill of units in manipulator. I put it in the social category for now, because I though that's where it would fit best, but that can be easily changed. 
Depends on DFHack/df-structures#394 (skill needs to have a caption_noun attribute for manipulator to display it properly)
> Add intrigue skill to manipulator

- dfhack.init-example
Autodump is a useful plugin that most players would probably want so it should be active in the default config.
> Activate autodump in default config

- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/stocks.cpp
Items::getDescription only gets the title of codices that have their titles in their title field. However, some codices and all tool "books" have the title buried in their improvements. Items::getTitle returns the first title found, either from the title field or buried, or a blank string if no title is found (as is the case for non "books").
It can be noted that it might have been useful to include slab descriptions, but I didn't have access to a written one, so I don't know if it would be too lengthy. Also, it seems one of the unmapped "item" functions ought to provide the functionality of this operation.
The stocks plugin calls getTitle first and getDescription if no title was found. A few codices were found not to get any title, but further investigation showed their contents was …
> Issue #1262. Added Items::getTitle and used in stocks

- library/LuaTypes.cpp
- library/include/BitArray.h
- library/include/DataDefs.h
- plugins/ruby/codegen.pl
- plugins/ruby/ruby-autogen-defs.rb
In C++. Still needs Lua and Ruby support.
See DFHack/df-structures#402.
> Implementation for df-other-vectors-type

- package/darwin/dfhack
This is a follow-up on #1465 . (I was pretty sure I tested the change after it made it into a release, but maybe it wasn't on a fresh install.)
The issue is that, when using find with an `-or`, the `-print0` is only applied to the last clause, so only the dwarfort.exe file is un-quarantined. Adding parentheses fixes that. (Example below.) FWIW, I also checked the version of find packaged with Ubuntu and the behavior is the same, so I'm assuming it's standard.
I also added the .framework files to the list of files to un-quarantine – these are included with DF and by default are blocked by OS X.
```bash
$ find hack/ libs/ dwarfort.exe -name '*.dylib' -or -name '*.exe' -print0
dwarfort.exe%
$ df 47.04 find hack/ libs/ dwarfort.exe \( -name '*.dylib' -or -name '*.framework' -or -name '*.exe' …
```
> Fix the un-quarantine behavior on OS X.

- docs/Plugins.rst
- docs/changelog.txt
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/reaction-gloves.h
When enabled, custom reactions will begin to produce gloves in sets, based
on the number of hands the job performer's race has, and set the
Handedness flags accordingly.
The "createitem" plugin already contains a simpler workaround (which
doesn't check body plan but instead just produces pairs), but it shouldn't
trigger when this tweak is enabled (unless you use it on a creature which
has been modded to only have "neutral" hands).
> Add a new tweak, "reaction-gloves"

- docs/changelog.txt
- library/Core.cpp
- travis/script-docs.py
#499 Enables the quickfort script to span multiple .lua files without polluting the output of #DFHack ls
This could also be useful for advfort, which is split into a main file and a module, but the module gets uselessly listed when we run ls -a
> Support internal scripts that don't show up in #DFHack ls

- library/lua/gui/dialogs.lua
#499
While implementing the quickfort GUI, I needed to be able to set the row_height for ListBox rows. The lower-level FilteredList provides the config option, but ListBox didn't have a way to pass the config through.
> quickfort: allow row_height to be set from the ListBox class

- library/lua/gui/widgets.lua
#499
The FilteredList class already provides a string filtering mechanism, but it failed to match many of the strings I needed it to match because it only looks for strings that come after spaces. This change allows it to match strings after spaces or punctuation. I *think* this is a general improvement in functionality, but if there are reasons not to make this change, I can instead change the format of my search key that this regex is applied against.
> quickfort: listbox filter can match strings after punctuation

- docs/Lua API.rst
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
#499 
I ran into trouble in the quickfort script while constructing activity zones. Zones that happened to be taken up by trees on the surface were failing to get created. Creating such zones in the UI works fine, so I investigated.
It turns out checkFreeTiles doesn't handle civzones properly. It assumes that no "building" can be placed in a wall, which is usually true, but not for civzones.  There was no other way to get whether the building is a civzone in that function, so I added an optional parameter to pass the information in. I would have liked to handle it at a higher level, but checkFreeTiles has useful side effects (like allocating extents) that are difficult to factor out.
> Properly calculate valid tiles for civzones in the Buildings module

- docs/Authors.rst
- docs/changelog.txt
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/finder_ui.cpp
In worlds generated with very low erosion count and "periodically erode extremes" off, you can find many waterfalls with very tall drops that are well over the original maximum embark-assistant search limit of 9 Z-levels.
An example: in one such world I created, embark-assistant found 906 waterfalls over 9 Z-levels tall, and by skimming the results manually I could see that quite a few were over 30 Z-levels. I wanted to find the most precipitous without inspecting every single result by hand. After making the edits in this merge request, embark-assistant located it for me: it was 47 Z-levels tall!
> Allow searches for higher waterfalls in embark-assistant

- data/blueprints/README.md
#499
also a bit of cleanup and reorg
> quickfort: document marker mode and buildingplan

- data/blueprints/library/dreamfort.csv
- use #notes blueprints instead of "invisible" "Notes" sheets
- remove smoothing guildhall blueprint
- rearrange statues in guildhall so no pre-smoothing is required
> quickfort: update dreamfort.csv library blueprint

- library/modules/Items.cpp
otherwise the bucket for wells (and asheries and dyer's workshops) can never be matched
> fix bug: buckets are missing lye_milk_free attribute in item matcher

- CMakeLists.txt
- docs/guides/quickfort-user-guide.rst
- add the dreamfort case study to the quickfort user guide
- fix one bad link and some missing text around labels (<word> syntax was lost by the doc conversion process)
- make sure the guide is actually built by sphinx (the guides dir was missing from the build path)
I learned in the PR that urls can be split over multiple lines in `label <url>`__ format and they still get resembled properly. Not in .. _label: url format, though.
> quickfort docs: dreamfort case study

- plugins/createitem.cpp
Adds support for plant growths to createitem.
Support for gui/create-item is still pending and will likely require significant UI work (to prompt for the plant+growth info)
> Fix createitem to properly create plant growths (#898)

- library/MiscUtils.cpp
- library/include/MiscUtils.h
- plugins/search.cpp
Normalize searches so that words/names with accented characters and diphthongs are more easily found with a standard keyboard.
This will fix #1598
> Normalize search

- docs/Lua API.rst
- library/include/modules/Materials.h
- library/modules/Materials.cpp
- plugins/buildingplan-lib.cpp
- plugins/buildingplan-lib.h
- plugins/buildingplan-planner.cpp
- plugins/buildingplan-planner.h
- plugins/buildingplan.cpp
- plugins/fortplan.cpp
- plugins/lua/buildingplan.lua
- plugins/uicommon.h
#1640 Lots of refactoring and reorganizing, with only cosmetic player-visible changes.
- show quickfort mode hotlkey label regardless of whether the current building type has buildingplan enabled. before, it was only shown after the user enabled buildingplan for the current building. this eliminates the extra step when enabling quickfort mode, which force-enables all building types.
- changed signature of lua-exported isPlannableBuilding to take subtype
and custom type in addition to building type. this is only used by
quickfort, and it already sends all three params in preparation for
this change
- added lua-exported scheduleCycle(), which is like doCycle(), but only
takes effect on the next non-paused frame. this lets quickfort
run only one buildingplan cycle regardless of how many …
> [buildingplan] step2: prep buildingplan for core algorithm changes

- plugins/buildingplan-planner.cpp
- plugins/buildingplan-planner.h
- plugins/buildingplan.cpp
- plugins/fortplan.cpp
- plugins/lua/buildingplan.lua
#1640
but restrict to only the currently supported set so we can still assume only one filter is required for each building.
Code can be reviewed after #1674 is merged.
changes:
- update buildingplan plugin version to 2.0
- new serialization format for planned buildings
- old persistent data is automatically migrated to new format on load
- algorithm now respects job_item filters; items must match job_item filter and buildingplan ItemFilter
- more invalid items are now filtered out, like items encased in ice. are there any others we should be checking (see BadFlags struct)
- items are sorted before job is unsuspended so final item ordering is correct regardless of what order the items were matched and attached
- item counts in filters are kept up to date so if buildingplan is disabled …
> [buildingplan] step4: generalize buildingplan to handle all building types

- data/blueprints/library/dreamfort.csv
- docs/Plugins.rst
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- library/modules/Buildings.cpp
- plugins/buildingplan-planner.cpp
- plugins/buildingplan.cpp
- plugins/lua/buildingplan.lua
Closes #1640
Allow buildingplan to handle all building types, update the docs, and add in little extra fixes to ensure all the new types work correctly.
Code can be reviewed after #1675 is merged.
There is a keybinding conflict with rollers that we should address. buildingplan takes over interpretation of 'q' and 'w' to adjust the min quality filter when planning mode is enabled for rollers, and then the roller speed can never be set. You can temporarily disable buildingplan for rollers, set the speed, enable buildingplan, and place the building, but that is a poor user experience. It might also break python quickfort blueprints that place rollers.
I don't really want to change the q/w hotkeys that people are used to, but a conflict is a conflict. Maybe just change the min quality hotkeys …
> [buildingplan] step5: support all building types

- library/lua/dfhack/buildings.lua
Code added to https://github.com/DFHack/dfhack/pull/1675#discussion_r506725773 for applying these filters.
changelog entry for quickfort attached to DFHack/scripts#212 (though technically buildingplan and anything else that directly or indirectly uses dfhack.buildings.getFiltersByType() will benefit)
> Add filter support for bookcases, display cases, and offering places

- dfhack-config/quickfort/quickfort.txt
- docs/changelog.txt
- plugins/buildingplan-planner.cpp
- plugins/buildingplan-planner.h
- plugins/buildingplan.cpp
- plugins/lua/buildingplan.lua
This PR can be reviewed after #1682 is merged
￼
Migrate quickfort's buildings_use_blocks functionality to buildingplan, where it fits in with buildingplan's other material selection functionality.
- remove buildings_use_blocks setting from quickfort config file
- add a new Buildingplan Global Settings dialog to house global settings
- move Quickfort Mode (for legacy Python Quickfort) into that dialog
- add four settings to control how generic building materials are matched:
- blocks
- boulders
- logs
- bars
- ajust the buildingplan algorithm to register duplicate tasks for building material item filters, one for each type. since we track how many items we've matched for a filter, the first matched item will "win" and the extras will get detected as invalid and popped off the queue.
- …
> [buildingplan] global settings and building material filters

- docs/changelog.txt
- plugins/buildingplan.cpp
The code previously only checked World::ReadPauseState(), but this flag is not set to true if the game was paused implicitly by going to a submenu or switching modes.
we now also check if we're in a mode other than the default map or squads or if we're in a subscreen.
> [buildingplan] ensure we don't run cycles while the game is paused

- docs/changelog.txt
- plugins/buildingplan.cpp
- plugins/lua/buildingplan.lua
for items that cannot have a quality or be decorated:
in place mode, don't show quality adjustment hotkeys (or isDecorated flag hotkey) and don't interpret the associated keycodes if they are pressed.
in query mode, don't show quality or decorated fields.
this prevents players from erroneously requiring that items have a quality when they never will.
> [buildingplan] don't show quality properties for no-quality items

- plugins/buildingplan.cpp
Fixes #1695
allows buildingplan to prevent unsuspension of planned buildings without also eating the 's' key when the user is trying to use it to give the building a custom name.
> [buildingplan] don't eat keys while building is being renamed

- plugins/buildingplan-planner.cpp
- plugins/buildingplan-planner.h
- plugins/buildingplan.cpp
this ensures that a player's preferences are saved across map reloads. this is particularly important for the building material filters, since item fulfillment tasks are regenerated on map load, and any changes in settings when buildingplan is reset will change the item vectors that will be searched for planned buildings. if the settings were allowed to reset, then a player who thought all walls would be made out of blocks would be surprised to find boulders and logs being used after the map is reloaded.
the quickfort_mode setting is intentionally not persisted, as it seems like that would be a "per session" kinda setting. I'd be happy to change that if people think differently, though. It might also depend on what other global settings we end up adding in the future, and whether it makes …
> [buildingplan] persist global settings across map reloads

- docs/Lua API.rst
- docs/changelog.txt
- library/include/modules/Items.h
- library/include/modules/Job.h
- library/include/modules/Materials.h
- library/modules/Items.cpp
- library/modules/Job.cpp
- library/modules/Materials.cpp
- plugins/buildingplan-planner.cpp
Fixes #1699
allows MaterialInfo to match metal bars as a building material. This allows metal bars to be used for construction in buildingplan.
> identify bars as non_economic items

- plugins/dwarfvet.cpp
Make sure `Patient::spot_index` actually gets initialized, as I can only assume was the original intent.
Note that I don't have the means to test this fix right now, and given how long this functionality has been broken, it's possible that there are other bugs in the plugin that rely on it.
> dwarfvet - initialize spot_index (#1711), fix types in Patient

- docs/Lua API.rst
- docs/changelog.txt
- library/include/modules/Buildings.h
- library/lua/dfhack/buildings.lua
- library/modules/Buildings.cpp
This allows callers of `Buildings::setSize()` to "pre-initialize" the extents to declare non-rectangular structures. The main beneficiary of this change is quickfort, which currently has a bug where non-rectangular structures *appear* correct on the map, but the occupancy is set incorrectly for non-occupied tiles within the bounds of the extent.
From inspection, the existing code appears to clear existing extents to protect against the case where the passed-in size does not match the size eventually assigned to the building. We can check for that case, though so the extents can still be reset as before if the size of the building doesn't match the caller's expectations.
This commit also fixes a memory leak when `setSize()` allocates memory for extents, but the memory is not deallocated if …
> only reset extents in Buildings::setSize() if they are unusable

- docs/Lua API.rst
Whitespace in the wrong place.
> fix example in Lua API.rst

- plugins/embark-assistant/survey.cpp
- plugins/embark-assistant/survey.h
as it says in the title
details:
- survey.cpp: removing maps layer_bottom and layer_top, which are never read, but slow down survey_mid_level_tile significantly because entries are added quite often into the tree map structure
- survey.h: removing now obsolete include for map
forum discussion for reference
http://www.bay12forums.com/smf/index.php?topic=169634.msg8128622#msg8128622
and more current
http://www.bay12forums.com/smf/index.php?topic=169634.msg8235898#msg8235898
@PatrikLundell: Just remembered that it helps to "@" the reviewer... :facepalm:
> [embark-assistant] removing 2 dead stores to speed up survey::survey_mid_level_tile

- docs/Plugins.rst
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- plugins/buildingplan.cpp
Add commandline parsing/validation and documentation for buildingplan global settings.
More info in the Plugins.rst documentation, but quick example usage:
`on-new-fortress buildingplan set boulders false; buildingplan set logs false`
> [buildingplan] set global settings from DFHack# prompt

- plugins/embark-assistant/embark-assistant.cpp
- plugins/embark-assistant/matcher.cpp
details: 
- embark-assistant.cpp: checking if a search is active, if so return early
Especially for large worlds the repeated calls to embark_update during the survey phase can burn a significant amount of cycles while the user often can't see the results before they are reset with the next ones.
@PatrikLundell: ... and here as well.
> [embark-assistant] early return from embark_update during an active search to improve performance

- LICENSE.rst
- docs/changelog.txt
- library/lua/3rdparty/alt_getopt.lua
- library/lua/utils.lua
Happy new year! This PR introduces a more flexible alternative to the existing `processArgs()` function in utils.lua
In addition to a more powerful argument handling syntax, this implementation don’t force "flag" options to be at the end. For example, with processArgs, `quickfort list dreamfort -l` is legal but `quickfort list -l dreamfort` is not. This causes confusion when users try the second (IMHO, more natural) syntax.
The new implementation is based on https://github.com/LuaDist/alt-getopt (MIT license), modified to support non-flag options and to replace calls to `os.exit()` with `qerror()`.
The new `processArgs2()` function is a wrapper of the core getopt logic and provides a handler callback interface for processing parameters. Documentation for the new function is in utils.lua. …
> [Lua] getopt-compatible lua script args parser

- plugins/embark-assistant/defs.h
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/survey.cpp
By defining an additional struct "mid_level_tile_incursion_base" that only contains those attributes that are actually used during incursion processing - notably not the vectors for the inorganics (e.g. metals, economic stone and minerals) as those had the biggest impact on the memory footprint even when empty (48 bytes per vector on Windows) - it is possible to reduce memory consumption of the plugin significantly. 
While users likely won't notice this for small world, for large world (257*257) this amounts to savings of at least 580MiB/608MB.
(48 bytes * 3 vectors * 64 mlt_per_world_tile * world_width * world_height)
Using this new struct as parent for embark_assist::defs::mid_level_tile allows this adaptation with only minimal changes in some classes.
forum discussion for reference …
> [embark-assistant] reduce memory footprint

- docs/Plugins.rst
- docs/changelog.txt
- plugins/buildingplan.cpp
- plugins/lua/buildingplan.lua
A quick way to enable planning mode for all building types. This kind of functionality is much more important now than it used to be since now there are so many supported building types.
Also modified the 'Planning Mode' status on the building placement screen to reflect whether we're in quickfort mode, enable all mode, or whether just the building type is enabled.
this setting is not persisted (just like quickfort_mode is not persisted), but it can be set from onMapLoad.init
> [buildingplan] add 'enable all' option

- docs/changelog.txt
- plugins/stockflow.cpp
discovered while testing quickfort when my "jugs" stockpile never got named correctly and messed up the remainder of the blueprint.
> [stockflow] don't steal input during building rename

- plugins/autofarm.cpp
Change the autofarm plugin to set any farm to fallow whenever no plant remains that both
- can be planted on it
- and has not yet reached its user-configured threshold.
This prevents serious excess plant yields when total farm production potential exceeds total plant consumption.
Resolves #1741.
> [autofarm] fallow farms when no further plants requested

- docs/changelog.txt
- library/lua/gui/widgets.lua
Allows Label text to scroll with Up/Down/PgUp/PgDown keys, just like the ListBox classes.
Not being able to scroll Label text became an issue for quickfort because blueprint help text is displayed in a MessageBox (which uses a Label to display the text). Blueprint help text is user-defined, so long blueprint walkthroughs (I'm looking at you, dreamfort) could not be fully displayed.
I would have loved to accept Space as equivalent to PageDown, but that interacts poorly with text input fields (depending on the order components' onInput() functions are called, it could end up scrolling every time you typed a space into a text field)
> scroll Lua Label text when height exceeds viewrect

- data/quickfort/aliases-common.txt
- docs/changelog.txt
- docs/guides/quickfort-alias-guide.rst
discovered by ldog on the [forums](http://www.bay12forums.com/smf/index.php?topic=176889.120)
fixed aliases for tallow, iron, copper, and steel weapons; added aliases for bronze and crafts
> [quickfort] update quickfort library aliases

- docs/changelog.txt
- plugins/stockpiles/stockpiles.cpp
They were overwriting each other when both plugins are enabled.
I removed stockpiles's dynamic placement code as well. it attempted to move the hotkey help text down if it covered any stockpile links, but this will no longer work since other hotkey text already takes up all the lines below stockpiles' hotkey text.
there are five plugins (that I know of) outputting hotkey help text at the bottom of stockpile screens: automelt, autotrade, stockpile, stocks, and stockflow. I suspect this is not the last conflict between that set that we'll see.
> [stockpile, stockflow] resolve hotkey help text conflict

- docs/changelog.txt
- plugins/orders.cpp
to reproduce: take a regular exported orders file, remove a comma between two elements, try to import.
this PR also adds the filename to error messages that have to do with file read errors.
> [orders] don't crash on importing malformed json

- docs/changelog.txt
- plugins/embark-assistant/embark-assistant.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/matcher.h
- plugins/embark-assistant/survey.cpp
@PatrikLundell: as announced.
I'll do some comparisons between the current version and the one with the following changes "in place" before removing the "WIP" just to be sure - but the code is mostly taken from the index feature branch which I scrutinized repeatedly concerning the performance of those changes.
Replace the local/automatic mid_level_tiles variable in matcher::match_world_tile with a dynamic one that is created and initialized once during the setup phase. The dynamic part of the contained 768 vectors is being allocated on the heap in both cases - which made the repeated instantiations of the automatic variable so slow/expensive in the first place.
Also replace calls to vector<bool>.resize in nested loops with direct assignments to those vectors, which curiously even after a …
> [embark-assistant] Improve performance of surveying => faster search

- docs/changelog.txt
- plugins/prospector.cpp
Fix #1772 
It can be noted that I've changed the somewhat arbitrary "average" amounts a little from what I've written in the issue.
Apart from adjusting the calculations, it turned out to be necessary to adjust their summing up, as the previous code applied integer truncation to the parts, resulting in e.g. a faint yellow diamond estimate drop from 128 to 0 when the factor was changed from 42 to 16.
As the comments added indicate, there are more intricacies that can be added, but with doubtful benefit. If someone would perform an analysis to determine more precise "average" cluster, vein, and small cluster sizes it would probably have a greater impact.
The main objective, i.e. to reduce cluster one estimates from 10 times the number of the small cluster material tiles it was enclosed …
> improved pre embark mineral estimates

- .gitmodules
- LICENSE.rst
- depends/CMakeLists.txt
#1690
This is just the pure Lua implementation of luacov. I'll investigate possibly integrating with cluacov later. cluacov replaces the debug hook and "improves accuracy", but in my tests I've been perfectly happy with the accuracy of the lua implementation of the debug hook.
I installed it in `hack/lua/luacov` as a generally accessible library even though luacov will not be accessed directly by the majority of scripts. It still needs to be accessible to the luacov report generation script (`scripts/devel/luacov`) and to the C++ code, which calls `luacov.runner.init()` and manages installing the luacov debug hook in coprocesses.
I fixed the luacov repo to the recent 0.15.0 release. This release is mistakenly named '0.14.0' internally, but this is cosmetic.
> [luacov] add luacov as a DFHack dependency and install it into hack/lua/luacov

- docs/changelog.txt
- library/Core.cpp
- travis/script-docs.py
#1690 
exempt lua test files from docstring requirements and don't display them with 'ls'
this prevents test files from cluttering up the ls output. users can't run them directly anyway, and as far as I can see, it doesn't seem that seeing the list of test files in ls output is valuable.
this also removes test/main from ls output. is that ok?
> [test] exempt lua test files from docstring requirements

- docs/changelog.txt
- test/main.lua
- test/test.lua
- test/test_test.lua
- travis/run-tests.py
#1690
new test/main API is backwards compatible with existing usage.
- allow configuration set in test_config.json to be dynamically overridden on the commandline
- make `expect.table_eq()` diff recursively (all existing tests that use it still pass)
- fix implementation of testing for multiple test name filters. the original implementation filtered out too many tests if more than one filter was specified.
- add ability to filter by mode (title, none, etc.)
- add ability to rerun tests that have already been run (I'm actually not sure what the purpose of `test_status.json` is. why would we want to skip a test if it has already been run? If you're running the tests again, haven't you just edited the code and wouldn't you want to see if tests that previously passed are now failing?)
- done …
> [test] test/main.lua enhancements

- docs/Core.rst
- library/Core.cpp
- library/LuaTools.cpp
- library/lua/dfhack.lua
- library/lua/luacov_helper.lua
#1690
Use the DFHACK_ENABLE_LUACOV environment var to control whether we initialize and patch luacov in to Lua threads owned by the DFHack core context.
This PR depends on DFHack/scripts#261 for the `devel/luacov` doc header reference (the docs added by this PR will fail until that PR is merged).
On initialization, we load `luacov.runner` and initialize it directly from C++. We also need to ensure the debug hook is installed correctly for coroutine threads. Since creating coroutines in C++ bypasses the [monkey patching luacov does](https://github.com/keplerproject/luacov/blob/master/src/luacov/runner.lua#L449) to inject itself into coroutine contexts, we compensate by reimplementing the monkey patch in our code. We use our own little lua helper function to do this because luacov's similar …
> [luacov] enable luacov coverage monitoring if DFHACK_ENABLE_LUACOV is set

- ci/test.lua
- library/lua/dfhack.lua
and invalidate scripts once tests are complete. this ensures that the
IN_TEST flag is respected.
note that this invalidates *all* scripts after running tests, even those that did not affect the test itself. we could potentially make this more targeted by remembering which scripts were loaded while IN_TEST was true and only reload those.
ooooorr, we could change the real reqscript to force a reload of the script if the value of IN_TEST in the calling environment doesn't match the value of IN_TEST that was in the environment when the script was loaded.
> [test] force reloading of scripts under test

- docs/changelog.txt
- plugins/lua/buildingplan.lua
Planning a 4x2 construction with DF's `umkh` keys (i.e. not automaterial's box-select) would previously produce a 5x3 construction instead, for example.
> buildingplan: fix size calculation for constructions

- docs/changelog.txt
- library/include/modules/Screen.h
- library/modules/Screen.cpp
- plugins/command-prompt.cpp
Fixes #1803
Running a command that created a new screen would previously result in a screen order that looked like this, due to how `Screen::Hide` works:
- DF screen
- `command-prompt` screen (dismissed)
- New screen
The `command-prompt` screen remained on the stack until the new screen was dismissed, so it would intercept viewscreen vmethod calls intended for the DF screen.
This change adds a new behavior to `Screen::Hide` that results in this screen order after running a command:
- DF screen
- New screen
- `command-prompt` screen (dismissed) - DF removes this screen immediately
> Ensure that command-prompt is dismissed after a command creates a new screen

- docs/changelog.txt
- plugins/tweak/tweaks/hide-priority.h
To reproduce:
1. Enter the `d`esignation menu
2. Press `-+` to change priorities
3. Create a designation
4. Press `Alt-p` to hide priorities
5. Exit and re-enter the designation menu (`Esc`, `d`)
Previously, priorities would be visible again after step 5. With this change, they are not visible until you press `Alt-p` again.
Fixes #1068. Note that this is a relatively unobtrusive fix: selecting a priority with `+-` will still result in priorities being shown again. This is native DF behavior that I am reluctant to override because users of designation priorities likely want to see them.
> tweak hide-priority: make toggle state persist across designation menu uses

- build/.gitignore
kdevelop (I'm running 5.5.2) creates this cache. it seems harmless, but should be ignored. here's a sample of the files inside:
```
build/.cmake/
build/.cmake/api
build/.cmake/api/v1
build/.cmake/api/v1/query
build/.cmake/api/v1/query/client-kdevelop
build/.cmake/api/v1/query/client-kdevelop/query.json
build/.cmake/api/v1/reply
build/.cmake/api/v1/reply/target-autohauler-Release-2cf2e423cc3f1bf66cd3.json
build/.cmake/api/v1/reply/target-confirm-Release-e79f0253fdba29c5f26d.json
build/.cmake/api/v1/reply/target-dfhack-Release-fdf0a7ef6226ca73777e.json
...
```
> ignore build/.cmake cache created by kdevelop

- ci/test.lua
- library/lua/test_util/mock.lua
- test/library/test_util/mock.lua
This is currently a relatively low-level `patch()` implementation, inspired by pytest's `mock.patch()`, since I noticed several recent tests using the same `with_finalize()` pattern to patch builtins (note: most of these tests are in the scripts repo, so I didn't modify them here, but see `ci/test.lua` for example usage). Open to adding other things that might be useful.
> Add some mock-related test helpers

- data/blueprints/library/quickfortress.csv
- docs/changelog.txt
Fixes #1838 
- fix references to deprecated aliases
- use freeform stockpile layouts instead of expansion syntax and `x(1x1)` to remove individual tiles. this didn't work in the original quickfortress distributed with python quickfort and it doesn't work here (there is no guarantee that the `x` tiles will be processed after the stockpile that they are intended to modify). also I haven't implemented `x` yet for stockpiles (it's trickier than it seems).
> [blueprint library] fix quickfortress.csv stockpiles

- ci/test.lua
- docs/changelog.txt
- travis/run-tests.py
#1690 
- implement navigation function for loading a fortress from the title screen (requires a fortress save to be ready to load).
- navigation function also handles case where a fortress map is already loaded
- ensure we don't try repeatedly to enter a mode that we can't reach (such as getting back to the title screen from fortress mode). failing to enter the mode once will skip all remaining tests in that mode.
This PR combines the VALID_MODES and MODE_NAVIGATE_FNS tables into a new MODES table that contains mode order, state, and related functions
> [test] support fortress mode

- docs/changelog.txt
- plugins/buildingplan.cpp
this lets ``isPlanModeEnabled()`` return true when "enable all" is set. this fixes the `automaterial` plugin interface when building constructions and buildingplan's "enable all" setting is set.
> [buildingplan] make isPlanModeEnabled() consider enable_all

- plugins/blueprint.cpp
remove the unneeded cache layer. the cache is for writing. we're just reading. all the cache is doing is adding latency as it makes its copies of map data structures.
generating a 190x190x100 dig blueprint:
before change: 1.7s
after change:  1.0s
the performance gains aren't as important here as the reduced complexity of the algorithm, though. for reasonably-sized blueprints, the time savings are unnoticeable. I'm not sure if this even needs a changelog entry.
this PR also includes minor editing to the header comment and the short description displayed in `ls`. if these are at all controversial, I can move them to a different PR.
> [blueprint] speed up dig blueprint creation by 70%

- docs/Lua API.rst
- docs/Plugins.rst
- docs/changelog.txt
- library/include/modules/Gui.h
- library/modules/Gui.cpp
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
#1842
This is the first stage of the blueprint plugin overhaul.
Depends on #1846 for support for negative depths and #1841 for the MapCache change (though the MapCache commits are included in this PR as well to avoid future merge conflicts)
The `blueprint gui` command has a soft dependency on DFHack/scripts#281. You'll be able to run the `blueprint gui` command, but it won't do anything until the `gui/blueprint` script has something in it.
User visible changes to blueprint:
- `depth` and `name` parameters are now optional (defaulting to `1` and `blueprint` if not specified)
- `depth` can now be negative to indicate that we should iterate through the levels top-down instead of the previous hard-coded bottom-up
- new `--cursor` option for specifying start position (game cursor is not needed …
> [blueprint] Support new commandline syntax and semantics

- plugins/resume.cpp
It turns out option 5 from https://github.com/DFHack/scripts/pull/284#issuecomment-848815321 was equivalent to option 1, and they're both cheap and effective.  the `process_jobs` flag is handled internally by df on every frame, so it only stays true for one frame. this allows us to invalidate once and rescan only when required.
no changelog entry since this was never a user-visible problem until DFHack/scripts#284
> [resume] invalidate cache when buildings are added programmatically

- docs/changelog.txt
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/survey.cpp
By changing the element type of the 3 vectors used to determine which inorganics (metal, economic stone and minerals) are present on a embark tile it is possible to make use of std::memset instead of manual direct assignment.
std::vector<bool> is being optimized by the compiler which leads to a smaller memory footprint but a significant overhead when  assigning values. Also it prevents the usage of std::memset as the entries in std::vector<bool> are not guaranteed to stored contiguously in memory - compare https://en.cppreference.com/w/cpp/container/vector to https://en.cppreference.com/w/cpp/container/vector_bool.
This change increases the memory usage a little but makes the search faster by around 6 seconds for large regions. Also it makes sure that the actual size of each vector is …
> [embark-assistant] Improve performance of surveying => faster search (again)

- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/fastdwarf.cpp
so it can be reused by `dig-now` and the `teleport` script (which has a much less sophisticated algorithm)
> move fastdwarf's teleport routine to the Units module

- docs/changelog.txt
- library/lua/dfhack.lua
- test/library/string.lua
added to the string class like `startswith()` and `endswith()`
refactored and improved from the implementation in `quickfort`'s `dialog.lua`
> new library string function: wrap()

- ci/test.lua
- docs/changelog.txt
delays until a predicate returns true or the timeout (in frames) elapses
> [test] add delay_until function

- library/lua/test_util/expect.lua
so you can see confusing hidden trailing spaces
> [test] add quotes around printed unequal values

- docs/Authors.rst
- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Maps.h
- library/modules/Maps.cpp
Derived from disassembly of DF code. Returns a pointer to plant struct that owns the tile at position. Useful for finding a tree from one of its branches. Lua API support.
> Add getPlantAtTile function to Maps namespace

- library/lua/test_util/mock.lua
- test/library/test_util/mock.lua
so we can mock functions like `screen.getCursorPos()` which returns `x`, `y` and not an otherwise mockable table of `{x=x, y=y}`
I changed the field value from `return_value` to `return_values` to highlight the change in semantics. I verified that no current code references this field (other than the unit tests, which I modified accordingly).
> [test] allow mock.func() to return multiple values

- docs/changelog.txt
- library/lua/gui/dwarfmode.lua
- test/library/gui/dwarfmode.lua
refactored and improved from `quickfort`.
this common implementation will replace the now redundant functions in `quickfort`, `gui/mass-remove`, and `gui/blueprint`.
> [gui.dwarfmode] new function: enterSidebarMode()

- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
Depends on #1890 for the path normalization library function
uses the new path normalization library function and fixes handling of blueprint basenames that end in a slash (that is, basenames that are directories). For a basename of `dirname/` the code previously generated the following files:
```
blueprints/dirname/-dig.csv
blueprints/dirname/-build.csv
...
```
it now drops the dash and generates files like:
```
blueprints/dirname/dig.csv
blueprints/dirname/build.csv
...
```
> [blueprint] normalize pathnames and handle dirs as basenames

- docs/changelog.txt
- plugins/orders.cpp
Fixes #1893
This is similar to the fix in #1770, which caught errors during initial read, but this PR catches errors thrown during processing. This came up because a manually edited orders json file had a string ID instead of a numeric ID.
I believe this now covers all the places that can throw errors for import. I also believe export is safe since we control the input there and don't do string processing, but I can't say that for absolute certain.
> [orders] fix crash on malformed order IDs

- library/lua/dfhack.lua
- test/library/string.lua
step 2 of #1888
this implementation of `string:split` is based on `utils.split_string()` but adds infinite loop protection and the ability to treat the delimiter as a literal instead of as a pattern.
- added string:split
- added string:trim
- added a default value for wrap width
- added function comments
- added tests for all string functions (the tests for string:split will be commented out until we remove the competing implementation in gui/load-screen
> add dfhack string functions and tests

- docs/changelog.txt
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-assistant/matcher.cpp
An attempt to compare world tile data to the search profile before the world tile data had been collected for waterfalls was removed.
> embark-assistant early waterfall quit removed

- library/lua/gui/materials.lua
Useful for high boot/low boot etc.
I think I got that in right...
The pcall is because sometimes the item type is, for example, a toy which doesn't have an adjective field, and it's made to error if you index a nonexistent field.
> Show adjective in item prompt

- library/lua/gui/widgets.lua
Current logic is because @myk002 fixed it so label would allow other widgets control when label(s) are present. However that breaks label key detection for default scroll keys. This can be worked around by setting scrollkeys to empty.
TBH: label is quite complicated and used everwhere so i'm reluctant to touch it and would love for someone to look over if i'm correct.
> Fix label early key detection in scrolling logic

- docs/changelog.txt
- library/modules/Buildings.cpp
fixes #1817
I hadn't run into this with `quickfort` since `quickfort` always initializes the room structure itself.
> ensure extents are populated for civzones and stockpiles

- docs/changelog.txt
- plugins/buildingplan.cpp
Hi,
This PR improves the interactions of the "Building Material" screen.
The key bindings currently used in this interface are:
```
Move selector up/down - for item selection
Move view/cursor left/right - for column selection
```
There will be no problems with the default DF key bindings because "Move selector ..." and "Move view/cursor ..." both use Up/Down/Left/Right. However, if you use different key bindings for them, the problem arises.
This PR uniformly uses "Move selector ..." as key bindings for item/column selection:
```
Move selector up/down - for item selection
Move selector left/right - for column selection
```
> Fix keybindings in the "Building Material" screen

- library/lua/argparse.lua
- library/lua/gui/widgets.lua
- library/lua/utils.lua
- plugins/lua/blueprint.lua
- plugins/lua/stockflow.lua
- test/plugins/blueprint.lua
Fixes #1888 
Depends on #1897 
step 5 of #1888 
This PR migrates library and plugin lua code to use the new string and argparse library functions (with some minor auxiliary cleanup). Each change has been manually tested, with coverage of changed lines verified with luacov (except for stockflow. I verified that it works but for some reason luacov doesn't show coverage for that particular file).
> migrate existing lua code to use new library fns

- docs/changelog.txt
- docs/guides/quickfort-library-guide.rst
Screenshots are hosted on Google Drive along with the dreamfort blueprints. I could add copies to the dfhack repo as well, if you prefer.
> [quickfort library guide] update dreamfort docs and add screenshots

- ci/test.lua
so we can keep tabs on how long tests take to run and optimize particularly inefficient tests.
This is becoming more relevant now that I'm starting to write more involved integration tests. It has already helped me get several `quickfort list` integration tests down from 300ms to 40ms.
With the other, higher-level changelog entries for the test harness, I'm not sure if this deserves its own changelog entry. WDYT?
> [test] measure and display elapsed milliseconds for tests

- docs/changelog.txt
- library/Core.cpp
Fixes #1878 (Keybindings sometimes act as if Alt is stuck down)
> [Core] clear modstate on window focus

- docs/changelog.txt
- plugins/buildingplan.cpp
This allows the player to determine which items are missing and need to be produced before a building can be built. It is most useful for buildings that take multiple items, such as dyer's workshops.
the information is visible in the `q`uery sidebar when examining a planned building
> [buildingplan] display which items are attached and which are pending

- docs/changelog.txt
- plugins/autogems.cpp
Add a test so that autogems will not assign cut gem jobs to workshops that are not allowed to do them.
Fixes #1263
> update autogems to respect workshop profiles

- docs/changelog.txt
- plugins/orders.cpp
- test/plugins/orders.lua
implemented for both import and export
uses the new test wrapper functionality to export current orders, run the test, clear orders, import the player's previous orders, and remove temp files. this prevents the tests from having visible side effects. The tests will reset the next order id, but this isn't visible to the player.
> [orders] support reaction-specific item traits

- docs/changelog.txt
- library/include/MiscUtils.h
- library/modules/Items.cpp
This allows `moveTo*()` and `remove()` functions to work with projectiles.
This solves the issue with the `build-now` script in DFHack/scripts#310 when an extra item remains in the game world when a construction is built on a tile that has no adjacent walkable tiles.
> Handle projectiles in Items module functions

- library/lua/3rdparty/alt_getopt.lua
> alt_getopt.lua: allow `?` as an option

- docs/changelog.txt
- library/lua/dfhack.lua
- test/library/misc.lua
- test/library/print.lua
prepares for the Lua upgrade in #1915
suggested fix for lua 5.3.6 change to how `pairs` works (or doesn't) with non-table input.
This ensures `!`, `^`, `@`, `~`, and plain `printall` all behave sanely with both table and non-table input.
```
[[lua]# !('hi')
hi
[lua]# ^('hi')
hi
[lua]# @('hi')
hi
[lua]# ~('hi')
hi
[lua]# printall('hi')
hi
[lua]# !({'hi'})
table: 0x7fffd0113680
[lua]# ^({'hi'})
table: 0x7fffd01137c0
1                       = hi
[lua]# @({'hi'})
table: 0x7fffd00927b0
1                        = hi
[lua]# ~({'hi'})
table: 0x7fffd00c2ad0
1                        = hi
[lua]# printall({'hi'})
1                        = hi
```
> [lua] ensure printall, ~, and @ behave in lua 5.3.6

- library/lua/test_util/expect.lua
- test/library/test_util/expect_unit.lua
Adding a pattern-matching function to `expect` since I got tired of writing tests like `expect.true_(mock_print.call_args[1][1]:find('^Prioritized 2'))`. This works fine when the test passes, but when it fails it doesn't give you any information about why it failed. The new `expect.find()` function will report the pattern and the string it failed to match.
I settled on `find()` since the string method of the same name has the same semantics.
Other options might be: `str_find()` since it fails on non-string or `match()` (but that might imply that the pattern needs to match the entire string).
No changelog entry for PRs like this, right?
> [test] add pattern matching expect.find()

- docs/Compile.rst
- plugins/buildingplan.cpp
- plugins/uicommon.h
This should make `-fpermissive` (from #1924) unnecessary, so I also removed those instructions.
@chrismdp could you confirm that this works for you without `-fpermissive`?
> Fix compilation error on macOS with GCC 11.2

- library/lua/gui/dialogs.lua
- test/library/gui/dialogs.lua
`dismiss_on_select = false` makes it easier to implement toggleable options, where we don't want the list to disappear on selection. Like work order conditions' trait selection.
> ListBox attributes controlling self:dismiss()

- data/examples/init/onMapLoad_dreamfort.init
- docs/Plugins.rst
- docs/changelog.txt
- docs/guides/examples-guide.rst
- plugins/orders.cpp
I have found that orders with daily frequency will prevent lower priority orders for the same types of items from ever getting scheduled. This is a problem when "workflow"-type orders that keep a small stock of a thing will prevent large one time orders for that same type of thing, significantly slowing down the project that the large order was created for.
This PR implements the `sort` command for the orders plugin, which can be called with `repeat` to automatically keep a fort's orders sorted so daily-frequency orders don't "shadow" any other orders.
> [orders] implement "sort" command

- docs/changelog.txt
- plugins/automaterial.cpp
Don't extract an anchor tile when using buildingplan. It isn't used in the buildingplan code path and the extraction process puts the tile out of order. this causes the tile to get fulfilled by buildinplan last, which is an unexpected experience for players who are carefully managing the suspension of certain tiles to ensure the corner tiles get built first (before they are blocked by other constructions and become inaccessible).
This is how it *should* have been implemented in 22ac163 where we first integrated with buildingplan.
manually tested with buildingplan enabled and disabled, and with open air placement mode enabled and disabled.
> [automaterial] lay down tiles in strict order when using buildingplan

- docs/changelog.txt
- plugins/blueprint.cpp
You can invoke `gui/blueprint` by running `blueprint gui`, and any optional params you pass to `blueprint` will get passed on to `gui/blueprint`. The problem was that `blueprint` was also passing the literal "gui" string as the first parameter, causing `gui/blueprint` to interpret it as the intended name of the generated blueprint. Whoops.
No unit test since we can't mock out the invocation of the `gui/blueprint` script, and running the script can error out depending on the current state of the game.
> [blueprint] don't pass literal "gui" to gui/blueprint when running blueprint gui

- docs/Plugins.rst
- docs/changelog.txt
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
- test/quickfort/ecosystem.lua
Part of milestone 2 of #1842
`--splitby=none` is the new default, allowing all blueprint phases to be written to a single file. old behavior of one phase per file is supported via `--splitby=phase`.
> [blueprint] add --splitby option

- data/blueprints/library/test/ecosystem/in/allbuildings-build.csv
- data/blueprints/library/test/ecosystem/in/allbuildings-dig.csv
- data/blueprints/library/test/ecosystem/in/basic-build.csv
- data/blueprints/library/test/ecosystem/in/basic-dig.csv
- data/blueprints/library/test/ecosystem/in/basic-place.csv
- docs/changelog.txt
- plugins/blueprint.cpp
part of milestone 2 of #1842
this allows quickfort to address the blueprints by name instead of their default numeric label.
ecosystem tests updated to incorporate the new labels.
> [blueprint] generate labels in blueprint modelines

- docs/Plugins.rst
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
- test/quickfort/ecosystem.lua
Part of milestone 2 of #1842
Add the ability to output in either "pretty" format (equivalent to the old behavior) or "minimal" format (the new default). Minimal blueprints don't include any annotations or "shadows" of building footprints, but are much faster to read and write. This allows us to optimize for the use case where a player is generating blueprints to play back later without manual editing. More advanced users that want to edit the generated blueprints should continue to use "pretty" format.
I am confident that there was no behavior change for "pretty" blueprints since the `quickfort` `ecosystem` integration/regression tests continue to pass without modification. I did make a few modifications to the `ecosystem` test harness to make it more efficient, but I did not need to …
> [blueprint] support multiple output file formats

- docs/Plugins.rst
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
part of milestone 2 for #1842
allows the cursor offset to be specified for when the blueprint is played back with quickfort, corresponding to the [start marker](https://docs.dfhack.org/en/latest/docs/guides/quickfort-user-guide.html#start-positions) in the quickfort modeline.
also reformat docs. parameter syntax help was being split over multiple lines, making it difficult to read.
> [blueprint] implement --playback-start parameter

- data/examples/orders/furnace.json
- docs/changelog.txt
- docs/guides/examples-guide.rst
- remove gypsum plaster orders until the [df bug](https://www.bay12games.com/dwarves/mantisbt/bug_revision_view_page.php?bugnote_id=0041146#r16745) is fixed
- update docs for orders
- update docs for professions
> update example orders and docs in examples guide

- docs/changelog.txt
- library/lua/argparse.lua
- test/library/argparse.lua
Implement handling for long form parameters that are not an alias for a short form parameter. For example, you can now have a parameter like `--longparam` without needing to have an equivalent one-letter `-l` param.
This is useful for esoteric parameters that you don't want to waste a precious one-letter param on.
> [argparse] add support for standalone long-form params in processArgsGetopt()

- .github/workflows/build.yml
- ci/test.lua
This should help identify differences in environments, e.g. what the screen resolution is in `PRINT_MODE:TEXT`. The `scripts/gui/blueprint:render_labels` test currently fails in an 80x25 resolution, which implies that our CI is using something else.
> test.lua: Dump some DF globals

- docs/changelog.txt
- library/lua/gui/dwarfmode.lua
this is useful for gui scripts that want to show dig designations, such as @drummeur's `trackify.lua` script
> [dwarfmode.lua] allow enterSidebarMode() to switch to the designate menu

- data/blueprints/library/test/ecosystem/in/allstockpiles-dig.csv
- data/blueprints/library/test/ecosystem/in/allstockpiles-place.csv
- data/blueprints/library/test/ecosystem/in/allstockpiles-spec.csv
- data/blueprints/library/test/ecosystem/in/basic-place.csv
- docs/changelog.txt
- plugins/blueprint.cpp
Member of milestone 3 of #1842
also adds integration tests that ensure the generated blueprints can be applied correctly by quickfort.
> [blueprint] support multi-type and non-rectangular stockpiles

- docs/changelog.txt
- plugins/blueprint.cpp
- test/quickfort/ecosystem.lua
completes milestone 3 of #1842 
prevents a blueprint from being written unless there is data to write or the phase was explicitly requested on the commandline/gui.
adjusts the ecosystem integration tests to make use of the feature.
> [blueprint] don't produce empty blueprints for action-less phases

- docs/guides/quickfort-user-guide.rst
#1998
Documentation for the new extended syntax for jumping up or down multiple z-levels in quickfort blueprints in DFHack/scripts#354
> [quickfort] add docs for extended syntax for z-level changes in quickfort blueprints

- library/lua/test_util/mock.lua
this improves test introspection capabilities since the table is snapshotted at the time of the mock call. A deep copy would be ideal, but this should cover most use cases.
> [test] make a (shallow) copy of table params when storing call args

- docs/changelog.txt
- plugins/orders.cpp
- test/plugins/orders.lua
lists the .json files in `dfhack-config/orders` so you can see what orders you can import.
tested with:
- missing `orders/` directory (prints error message)
- empty `orders/` directory (prints helpful message)
- `orders/` directory with json files (they get listed)
- `orders/` directory with non-json files (they get skipped)
- `orders/` directory with subdirectory (it gets skipped)
- `orders/` directory with subdirectory that has a `.json` extension (it gets skipped)
These were manual tests instead of unit tests since we can't mock out the filesystem operations in the C++ code and I don't want to manipulate the user's real data files to create these situations. there is no way we can account for all failure modes.
> [orders] implement list subcommand

- docs/changelog.txt
- library/Core.cpp
Fixes #1776
This allows players to figure out where autorun commands are coming from, which is especially useful when an init script is doing something you don't expect and you need to figure out which one to edit.
Logging capability was already in `Core.cpp`, it was just turned off when executing most init scripts. This PR turns it on and adds logging to stderr. Also, to normalize the appearance of the script names, `./` path prefixes (which appear on some init script paths but not others) are not printed.
The names are logged to both the console and stderr since script output goes to the console and the script invocation log is in `stderr.out`.
> [Core] Print the names of executed init scripts to console and stderr

- docs/changelog.txt
- library/modules/Buildings.cpp
tl;dr: This PR allows `Buildings::findCivzonesAt()` to execute in amortized constant time. The memory cost is proportional to the combined area of all civzones, but is not significant compared to the total memory usage of DF+DFHack.
Long version:
The `blueprint` plugin recently acquired the ability to create `#zone` blueprints to record the layout of civzones in a map area. When scanning for zones, `blueprint` will call `Buildings::findCivzonesAt()` for each tile in the transcription area. Each call to `findCivzonesAt()` has to scan every civzone in the game since there is no way to directly look up which civzones cover which tiles. This isn't so slow when the number of civzones is very small, but as the player allocates more civzones, the algorithm starts to crawl. With thousands of …
> cache zones so Buildings::findCivzonesAt() is O(1) instead of O(N)

- data/blueprints/library/aquifer_tap.csv
- data/blueprints/library/dreamfort.csv
- docs/changelog.txt
add prisoner quantum stockpile and related help text for how to handle a siege and how to manage prisoners after a siege
also add a missing blueprint label to aquifer_tap.csv.
Online screenshots for dreamfort have also been updated: https://drive.google.com/drive/u/0/folders/14KdE2E2wQKj4F_E-NAe3G3E4x1wiWtrc
I uploaded them as new versions of the existing files, so the urls won't change. The new images should automatically show up on the DFHack blueprint library guide https://docs.dfhack.org/en/stable/docs/guides/quickfort-library-guide.html
> [blueprint library] add prisoner processing to Dreamfort

- docs/changelog.txt
- plugins/tiletypes.cpp
The code path was fine when run from another script, but crashed when run from the DFHack command line. The issue was that the code required a suspended core, but we never explicitly suspended. It was fine when run from another script because being in a script implied the core was already suspended.
> Fix crash in tiletypes

- library/include/modules/Kitchen.h
- library/modules/Kitchen.cpp
- plugins/seedwatch.cpp
I started this cleanup over a year ago (with the intent to eventually get rid of the Kitchen module entirely, since there's literally only one plugin that uses it), and then I forgot about it.
May as well get it merged as-is, assuming everything still actually works.
> Cleanup Kitchen module (and the seedwatch plugin which uses it)

- docs/changelog.txt
- plugins/stocks.cpp
Fixes #2015
allow search terms to match full item labels even when the item label is truncated for length.
this change also fixes items that were being incorrectly grouped due to having differences only in the truncated part of their labels
> Fix stocks search for truncated item labels

- docs/changelog.txt
- plugins/dig-now.cpp
I originally missed this because fortifications are indicated by the "smooth" field, not the dig designation field.
I would add this to the quickfort ecosystem tests, but `blueprint` will need some work first to properly support fortifications. see https://github.com/DFHack/dfhack/issues/1842#issuecomment-1065964099
> dig-now: handle carving fortifications

- data/examples/orders/basic.json
- docs/changelog.txt
- docs/guides/examples-guide.rst
Fixes #2024
Goblets are staple of dwarven happiness. No need to require players to manually produce them.
> Add goblets to example manager orders

- plugins/autofarm.cpp
This is a minor cleanup of autofarm, mostly to eliminate some code smells (like `using std`) and to be more consistent with modern C++ coding standards
> autofarm code cleanup

- docs/Compile.rst
- docs/changelog.txt
update instructions to recommend using VS 2022 or VS 2019 with downlevel tool support
> visual studio 2022/2019 build instructions

- docs/guides/examples-guide.rst
- docs/guides/quickfort-alias-guide.rst
- docs/guides/quickfort-library-guide.rst
- docs/guides/quickfort-user-guide.rst
So they are more distinct. Even I got confused about the difference between the quickfort library guide (which is about blueprints, but listing the pre-made onces) and the quickfort blueprint guide (which is about blueprints, but editing them)
The file paths and anchor names are unchanged, so current internal and external links still work.
> Reword the titles of the various guides

- docs/changelog.txt
- plugins/confirm.cpp
The command is called `confirm`, not `confirmation`.
> [confirm] Fix typo in help message

- plugins/dig.cpp
Changed line 1277 to say "This is a vein. Use digv instead!/n" instead of "This is a vein. Use vdig instead!/n"
> Typo Fix in dig.cpp

- docs/changelog.txt
- library/lua/gui/dwarfmode.lua
it would end up in `DesignateChopTrees` if you happened to be looking at the surface z-level.
this fixes a flaky test that checks the resulting mode for executing `guidm.enterSidebarMode()` with various parameters. the test would pass if you were underground and fail if you were on the surface.
> fix guidm.enterSidebarMode(DesignateMine)

- library/include/modules/EventManager.h
- plugins/eventful.cpp
the EventManager got a new event type for new active units, but the handler for the event was not added to the array of handlers in `eventful` so the wrong handlers were being called for some events. In particular, the onUnload event was being sent to the wrong handler and was causing a crash when a map was unloaded.
> fix crash in eventful due to misaligned fn map

- library/Core.cpp
- library/Debug.cpp
- library/include/Debug.h
- library/include/DebugManager.h
- plugins/debug.cpp
Fixes #2045 
Init script execution logging will now be configurable via the `debugfilter` command. To turn off script execution logging, add the following line to your `dfhack.init` file:
```
debugfilter set Warning core script
```
This PR, however, is mostly about allowing debug log output to blend seamlessly into our existing messages, and there are a number of policy questions to be answered. Since none of our code really uses the debug log yet, changing things won't break anything, but we do need to decide how things should work going forward, as adoption of the logging framework should increase in the future.
Before this change, log messages output through the debug logging framework had the following format:
`12:27:22.306:t1:core:script: Loading script: dfhack.init`
This is very …
> [core] Debug logging facelift

- .github/workflows/build.yml
`apt install gcc-11` in GitHub's Ubuntu 20.04 environment seems to pull from https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test, which gives GCC 11.1, not 11.2. I vaguely recall a difference in warnings between the two.
Nevertheless, this increases the coverage of our build matrix slightly.
> Bump max GCC in GitHub Actions build matrix to 11

- docs/changelog.txt
- plugins/manipulator.cpp
Use standout colors instead of just a darker foreground to indicate cursor position.
I spend half my time in manipulator jiggling the cursor around trying to spot it. This fixes that for me.
> [manipulator] Tweak colors to make cursor easier to locate

- .github/workflows/buildmaster-rebuild.yml
- ci/buildmaster-rebuild-pr.py
When merged, this wil add an option under https://github.com/DFHack/dfhack/actions like this, which will allow maintainers to re-trigger Buildmaster builds for PRs.
> Buildmaster rebuild action

- docs/changelog.txt
- plugins/autochop.cpp
redo of https://github.com/DFHack/dfhack/pull/1938 because... reasons.
only half implements https://github.com/DFHack/dfhack/issues/876 - i have zero idea about how to go about designating the largest / oldest / trees that won't grow anymore, so if anyone has any ideas on that, please let me know! - but the first part, only designating the amount of trees required to get to max_logs, is here and worked in my testing seven months ago.
Edit from myk002: Fixes #876
> only designate enough trees to reach max_logs

- test/quickfort/ecosystem.lua
I had this change floating around locally. If memory serves correctly, this test was previously failing on a clean install because the output folder didn't exist. Presumably CI is not failing because the affected tests only run in fortress mode.
> test: quickfort/ecosystem: avoid assuming output folder exists

- data/blueprints/library/test/ecosystem/golden/tracks-carve.csv
- data/blueprints/library/test/ecosystem/in/basic-carve.csv
- data/blueprints/library/test/ecosystem/in/fortifications-carve.csv
- data/blueprints/library/test/ecosystem/in/fortifications-dig.csv
- data/blueprints/library/test/ecosystem/in/fortifications-smooth.csv
- data/blueprints/library/test/ecosystem/in/fortifications-spec.csv
- data/blueprints/library/test/ecosystem/in/tracks-carve.csv
- docs/changelog.txt
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
- test/quickfort/ecosystem.lua
#1842
Fortifications and engravings were difficult to replicate in a blueprint because they need the surface to be smoothed before they can be designated. This required some reworking of the blueprint plugin:
- the `track` phase is renamed to `carve` and covers tracks, fortifications, and engravings
- a new `smooth` blueprint is created that smooths the tiles that will later hold fortifications and engravings
- a new commandline param (`--engrave`) that toggles whether engravings are captured. otherwise they are ignored and their tiles are not smoothed in the `smooth` blueprint
this PR also adds functional tests for fortifications (but not engravings since `dig-now` doesn't support engravings).
the `ecosystem` test harness was retooled slightly to play back the phases in a specific order, …
> [blueprint] capture carved fortifications and engravings

- docs/Lua API.rst
It was listed under listdir, but it only appears in listdir_recursive
> Move docs for include_prefix param to correct function

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/dfhack.lua
- test/library/string.lua
add `string:escape_pattern()` to dfhack.lua
stolen from `devel/query.lua` since it was such a nice implementation. will migrate scripts to use the common implementation later.
> Add string:escape_pattern() utility function

- docs/changelog.txt
- library/lua/gui/dialogs.lua
Currently, if a filtered ListBox has a filter that doesn't match any items, it will shrink the dialog box so small that users won't be able to see the message that says that nothing matches the filter.
This PR modifies the minimum dialog box height to take the error message into account.
There appeared to be a typo in the call to `super`. The wrong class name was used. This apparently gave the same result as the correct class name, so that wasn't much of an issue. I fixed it anyway, though.
> ensure ListBoxes always have enough height

- docs/Lua API.rst
- library/lua/argparse.lua
- test/library/argparse.lua
- moves existing documentation from in-file to `Lua API.rst`
- significantly extends documentation for `processArgs()` and `processArgsGetopt()`, hopefully making them more accessible to new developers
- adds unit tests for `argparse.processArgs()`
- use new string fns in `processArgs()` (e.g. `string:startswith()`) instead of using longhand code
- allow `processArgs()` to recognize options with two dashes instead of just one to make transition to `processArgsGetopt()` easier if devs want to upgrade from one to the other
> Document and update argparse module

- docs/changelog.txt
- library/lua/dfhack.lua
`safe_index` purports to make it safe to walk through a sequence of dereferences, but it fails to handle two cases:
1) the index is numeric and is the upper bound of a lua list
2) the index is numeric and is the index into a sparse lua map
the first issue occurs because `safe_index` assumes it is looking at a C++ vector when it gets numeric indices. in the case of C++, it correctly bails if index is < 0 or >= `#obj`.  however, for lua lists, this check doesn't make sense. first of all it's fine if you index to a location outside of the list (the next check will correctly return nil anyway). second, lua lists range from 1 to #, not 0 to # - 1.
The second issue occurs because to check the range of the list, it uses the `#` operator. this always returns 0 if the map is sparse and doesn't …
> handle number-indexed lua maps in safe_index

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
- `widgets.Panel`: if `autoarrange_subviews` is set, `Panel`s will now automatically lay out widgets vertically according to their current height.  This allows you to have widgets dynamically change height or become visible/hidden and you don't have to worry about recalculating frame layouts
- `widgets.ResizingPanel`: new `Panel` subclass that automatically recalculates it's own frame height based on the size, position, and visibility of its subviews
These are refactored from the current `gui/blueprint` implementation for reuse in `gui/quickfort` and to be made available to other scripts
> add ResizingPanel class and autolayout for Panels

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui.lua
- library/lua/gui/dwarfmode.lua
Refactor sidebar mode management code from `gui/blueprint` (and the new `gui/quickfort` that isn't merged yet) into the common library class.
Modifies the low-level `Screen:show()` function to handle `onAboutToShow()` dismissing a window. This allows a `MenuOverlay` subclass to reinvoke itself (or get run twice by the user) without having to manually track whether it already has a window shown so it can dismiss it before showing the new one. `gui/blueprint` does this, and now all that code can be removed.
There are many subclasses of MenuOverlay that can take advantage of the new code. I'll migrate them after this change is approved and merged.
> automatically manage sidebar modes in MenuOverlay

- docs/Plugins.rst
- docs/changelog.txt
- plugins/tweak/tweaks/stable-cursor.h
Allow the viewport to move a bit and still keep the cursor location. In addition to "enable" and "disable", the distance is now configurable with "tweak stable-cursor 20" (default is 10 tiles).
I chose a relatively small default in case people are using the 80x24 screen, in which case moving 10 tiles up is already near the edge of the screen. This still allows one viewport move (view moves 10 tiles at a time), and I think it feels like a nice compromise.
On a larger viewport, `tweak stable-cursor 30` feels natural to me.
> [tweak/stable-cursor] Keep stable cursor when viewport is near enough

- .gitignore
- plugins/CMakeLists.txt
This is more convenient for some devs than the old CMakeLists.custom.txt solution because it allows the plugins themselves (files or folders) to be ignored, rather than needing to remember to leave them unstaged.
Same as #2095
> Add new `plugins/external` subdirectory for external/untracked plugins

- library/modules/EventManager.cpp
- plugins/eventful.cpp
A PR for just the auto-generated arrays part so we can avoid manual synchronization and sneaky problems arising.
> EventManager/Eventful - Generate event arrays

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui.lua
This change allows writing `frame_inset = {r=1}` instead of `frame_inset = {l=0, r=1, t=0, b=0}`
> default unset `frame_inset` values to 0

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
`TooltipLabel` dynamically shows and hides like a tooltip (but can be used for any annotation-like text)
`HotkeyLabel` is just syntax candy around a label that reacts to a hotkey
`CycleHotkeyLabel` cycles through a list of options
`ToggleHotkeyLabel` cycles between On and Off
These widgets are refined from the original code in `gui/blueprint`. They have been cleaned up, generalized, and simplified.
The new widgets have been tested by rewriting gui scripts to use them and ensuring everything still renders and reacts properly.
> [lua] Add some more handy widgets to the library

- library/include/modules/EventManager.h
- library/modules/EventManager.cpp
The event manager's event data types now have hash functions. One is even put to use, for the constructions event manager. The rest don't get put to use in this PR, as they don't have existing behaviour that can be improve by a switch to an unordered container.
~~This is also branched from PR #2105~~
> EventManager types become hashable

- docs/Plugins.rst
- docs/changelog.txt
- plugins/cursecheck.cpp
This PR Closes #2087.
I added a new parameter `cprobe` to display part of cprobe output for the unit being evaluated by cursecheck. 
Also, added this parameter to the `help` and to the documentation.
Would appreciate feedback on those description texts.
Thanks in advance.
> Adding cprobe capability to cursecheck

- docs/Plugins.rst
- docs/changelog.txt
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/partial-items.h
When active, the displayed names of partially-consumed items (e.g. hospital cloth) will display a percentage indicator at the end.
Because otherwise it's impossible to see why certain pieces of cloth or thread are being ignored for other jobs.
> Add "partial-items" tweak.

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/dfhack.lua
If the Lua table `t` doesn't include the specified `key`, `t[key]` is set to the value of `default_value`, which defaults to `{}` if not set. The new or existing value of `t[key]` is then returned.
> add new global function: ensure_key

- data/examples/init/onMapLoad_dreamfort.init
- dfhack.init-example
- docs/changelog.txt
- library/CMakeLists.txt
- onLoad.init-example
Update the default init files with the following changes:
**dfhack.init-example**
- add `gui/quickfort` keybinding (is Ctrl-Shift-Q a good choice?)
- remove keybinding for obsolete `gui/assign-rack`
- remove reference to obsolete `tweak military-training`
- add `tweak do-job-now`
- add `tweak partial-items`
- add `tweak fast-heat 100`
- replaced the `sc-script` example with documentation on how to name files so they load automatically without needing to use `sc-script`
**onLoad.init-example**
- removed (replaced with documentation added to `dfhack.init-example`)
**data/examples/init/onMapLoad_dreamfort.init**
- added more documentation, removed "cheaty" commands and commands now moved to `dfhack.init-example`
Should anything in `onMapLoad_dreamfort.init` be moved to a more "default" file?
> Update init files

- docs/changelog.txt
- library/lua/gui/dwarfmode.lua
To assist with drawing tiles over the visible map
Refactored from `gui/quickfort` and `gui/blueprint`, library implementation tested with those scripts and `gui/mass-remove`
See usage by scripts in DFHack/scripts#377 and DFHack/scripts#371
> add dwarfmode.MenuOverlay:renderMapOverlay()

- docs/Remote.rst
- docs/changelog.txt
Add a link to https://docs.rs/dfhack-remote/latest/dfhack_remote/index.html, a library using the remote API for the rust programming language. Note: the github repo is https://github.com/plule/dfhack-remote if you prefer linking to it rather than docs.rs
> Add a link to the rust library for interacting with the remote API

- .github/workflows/build.yml
I tested on my fork with PR https://github.com/cppcooper/dfhack/pull/3
I added this commit and pushed, opened the PR, added a (temporary) document change commit and pushed. The second commit's build steps were seconds instead of minutes. So this works as far as I tested.
> Adds ccache to build workflow

- library/MiscUtils.cpp
- library/include/MiscUtils.h
- plugins/command-prompt.cpp
Adding word wrapping to the command-prompt responses is simple. But we want to preserve whitespace, which our existing `word_wrap()` (both C++ and Lua) don't do. So here's an upgrade.
Now that word wrapping is in place, it really cries out for scrolling the results up and down. That can be done in a separate PR, though.
Closes #2079
Tests for word_wrap(), to be added once unit testing for C++ is sorted:
```cpp
#include "Internal.h"
#include "MiscUtils.h"
#include <iostream>
#include <string>
using namespace std;
bool compare_result(const vector<string> &expect, const vector<string> &result)
{
if (result == expect)
{
return true;
}
else
{
auto e = expect.begin();
auto r = result.begin();
cout << "# " << setw(20) << left << "Expected" << " " << left << "Got\n";
while (e < expect.end() || r …
```
> Command prompt wrap

- docs/Removed.rst
ref: DFHack/scripts#382
This PR should be merged before the stroke of midnight so the docs don't suddenly become unbuildable when the automated submodule update happens.
> tombstone devel/unforbidall script

- ci/script-docs.py
The check previously matched any filename ending in `lua`, not `.lua`. This
caused failures in my fork because I had a branch ending in `-lua`, which
created a file of that name in `.git/refs` that was not a valid Lua script.
For extra good measure, anything under `.git` is ignored now as well.
(Fun fact: this dates back to the script's original implementation in #713)
> Fix script-docs.py extension check

- ci/update-submodules.manifest
#2131 
move jsoncpp to reading from the new `dfhack` branch instead of master so we can fetch upstream into master without it automatically getting pulled into the main build
also autoupdate isoworld, which wasn't currently tracked.
> update the list of submodules to autoupdate

- depends/CMakeLists.txt
This should get rid of those silly `WARN: CHECK_STARTLooking for _snprintf` messages
> reduce spurious warnings from libzip

- docs/changelog.txt
- plugins/confirm.cpp
- plugins/lua/confirm.lua
Fixes #2155
Working on "pausing" functionality for the confirm plugin in a separate PR.
> Confirmation dialog for removing manager orders

- docs/changelog.txt
- library/MiscUtils.cpp
- library/include/MiscUtils.h
Replace ``bool collapse_whitespace`` option with an enum. Options ``WSMODE_KEEP_ALL``, ``WSMODE_COLLAPSE_ALL``, and ``WSMODE_TRIM_LEADING``.
Related to https://github.com/DFHack/dfhack/pull/2113
> MiscUtils word_wrap: Add option to trim only leading whitespace after wrapping

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui.lua
- test/library/gui.lua
Context: #2137
This PR adds keyboard focus handling to the `View` base class. Behavior of existing widgets is unaffected unless they take advantage of the new capabilities. `EditField` will be modified to do just that in the next PR.
The new fields and methods have to be added to the `View` base class instead of, say, `Widget` because focus affects the implementation of `View:inputToSubviews()`. Also, if we put the code in `Widget`, we run the risk of someone adding a higher-level `View` subclass as a subview to a `Widget` subclass, and that would produce confusing and undesirable behavior.
> [lua] implement keyboard focus subsystem

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
Fixes #2137
Requires #2160 for the focus subsystem
Scripts that use EditField will get a related PR in the scripts repo.
Now views that include `EditField` widgets don't need to do any manual handling of keyboard focus or widget activation/deactivation.
`FilteredList` got an update since it no longer needed to manually manage the state of its `EditField`. This actually solved a long-standing bug that I was otherwise meaning to look into: now if you hit a number key that could be interpreted as an arrow key if you pressed it in the num pad (like 2), it will actually be input to the filter properly and not result in a list selection movement. So yay for that.
Changes have been manually tested with:
- `gui/quickfort` (uses FilteredList with no edit_key) (no script changes required)
- …
> Allow EditField widgets to manage their own activation and keyboard focus

- docs/changelog.txt
- plugins/confirm.cpp
Hit 'p' to pause confirmation until the current page/sidebar is exited.
As proposed in #2155
adds the "p to pause" hotkey help text to the main dialog.
I would have added it to the bottom bar, but just writing `p: Pause` isn't exactly explaining what will happen when you hit `p`. Adding more help text to the bottom bar makes the dialog unacceptably wide.
Screenshot:
Hitting `p` pauses and closes the dialog without confirming the action. The user has to invoke the action again, and it will be let through without the confirm dialog showing up.
> Allow player to pause the confirmation dialog without disabling

- .github/workflows/build.yml
as discussed on discord
this builds on https://github.com/DFHack/dfhack/commit/46f80bed3daeb105e6350a6ef12854447c245663 by adding the repo owner and branch name to the key. this allows the ccache that we build on to be the one most relevant to the branch.
> namespace the ccache key with the repo and branch

- docs/guides/examples-guide.rst
- docs/guides/quickfort-library-guide.rst
- docs/guides/quickfort-user-guide.rst
I apparently wasn't aware of extlinks when I wrote some documentation. Easy fix.
> use extlinks where appropriate in docs

- .github/workflows/build.yml
Pending #2182
Worth noting that Ubuntu 22.04 comes with GCC 11.2, as opposed to the previous 11.1, and runs into the error resolved in https://github.com/DFHack/dfhack/pull/2182/files#diff-b79c29d99dee0213b3e1fdb5b09641f0300949a0257ea3635a856dcf97b01149R514. I kept GCC 11 in the matrix for comparison, but plan to remove it before merging.
> GitHub Actions: Upgrade newest matrix entry to Ubuntu 22.04, GCC 12

- .github/workflows/build.yml
- ci/download-df.sh
Fixes #2195 
So we don't repeatedly download DF and the test save
> check for files, not md5 receipt in download-df.sh

- plugins/manipulator.cpp
Fixes #2192 
There's nothing in it, it's not referenced anywhere. we don't need to create it.
no changelog entry since it's not user-impacting.
> [manipulator] don't create the unused manipulator/ directory

- docs/changelog.txt
- library/modules/Job.cpp
Fixes #2179
The new df-provided `cancel_job()` doesn't disassociate items from the job for us whereas the old custom implementation did.
ref: #2028
> ensure refs are cleaned up when we remove a job

- docs/changelog.txt
- library/lua/gui/materials.lua
the dialog allows editing of item traits (where "item" is part of a job or work order or similar).
the list is the same as in vanilla work order conditions `t` change traits (but ordered differently).
example usage: `gui/workorder-details.lua` from https://github.com/DFHack/scripts/pull/358/
> add `ItemTraitsDialog` to materials.lua

- conf.py
- docs/styles/sphinx5.css
I installed sphinx-5.0.1 locally to get a preview of what's to come. It displayed a few warnings that looked legit:
- We should explicitly set a language for the docs (it defaults to 'en', but we should make that explicit)
- extlinks should have '%s' in the comment expansion text
Locally-generated docs still look good with the changes in this PR. I'll also check against the build action output.
> ensure our docs build cleanly with sphinx-5

- docs/changelog.txt
- library/modules/Job.cpp
Fixes #2207
We still disconnect the refs if we can. @ab9rf is this now the correct behavior? Are there any cases where I shouldn't call `disconnectJobGeneralRef()`
> manually handle DestroyBuilding jobs

- .github/workflows/build.yml
- .gitignore
- CMakeLists.txt
#2228 
This is first step to displaying rendered help text in-game. This PR adds a build step for text rendering of our current documentation. It installs the rendered text in the same directory as the html text (`<DF>/hack/docs/`) instead of creating a new directory to keep everything together. It doesn't have to be this way, it just seems simple. Users who browse the html will never see the text files, and this way we don't need to create an additional directory.
We were previously installing the intermediate `doctree` build files along with our html docs. This was unnecessary and also created file conflicts with the text render output. I moved the intermediate build output to our `build/` directory.
> Build and install text help alongside html

- docs/Tags.rst
- index.rst
- library/LuaApi.cpp
- library/lua/helpdb.lua
#2228 
Add lua-based help DB with the following API:
- get_entry_short_help(entry)
- get_entry_long_help(entry)
- get_entry_tags(entry)
- list_entries(filter)
- list_tags()
- get_tag_description(tag)
The DB lazy initializes when an API method is called. If already initialized, but it has been more than a second since the last API method was called, it scans sources for changes.
The help information is read from `hack/docs/docs/` if it exists. If no rendered docs exist for the identifier (plugin name or command), the strings passed to PluginCommand are checked for plugins and script sources are checked for scripts.
This means that existing scripts are already fully supported by the db. Plugins will gain support as we move the plugin docs to individual .rst files.
> Myk rendered help

- docs/Core.rst
- docs/changelog.txt
- library/Core.cpp
- plugins/hotkeys.cpp
In preparation for binding to `gui/launcher` once it is merged.
> Support backtick as a keybinding

- plugins/automelt.cpp
now that we actually have to document everything, frivolous commands actually cost something. let's get rid of the useless ones.
I don't think this is even worth a changelog entry, though. getting rid of this command isn't going to break anyone's workflow.
also added in proper cleanup when the plugin is reloaded. The old hooks weren't getting disabled.
> [automelt] remove un-useful command

- docs/changelog.txt
- plugins/seedwatch.cpp
Fixes #1941 
This PR makes two changes:
- The internal map of plant id -> plant index now only contains plants that have seeds. This will allow us to print an error message instead of succeeding but performing no useful action when a plant ID is passed to the API that doesn't have seeds.
- When `seedwatch all` is called, we iterate over our map and set targets for all plants that have seeds, instead of just the ones in the hardcoded abbreviation list.
No doc updates in this PR since the docs have been rewritten in the docs branch and we don't need to cause conflicts.
> modify seedwatch all to actually watch all seeds

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
- test/library/gui/widgets.EditField.lua
- test/library/gui/widgets.Label.lua
- test/library/gui/widgets.lua
Add mouse controls for `EditField`, `HotkeyLabel`, and `CycleHotkeyLabel`.
Also add cursor movement hotkeys for `EditField`:
- Left/Right arrow: move the cursor one character to the left or right.
- Ctrl-Left/Right arrow: move the cursor one word to the left or right.
- Alt-Left/Right arrow: move the cursor to the beginning/end of the text
> widget usability enhancements

- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/Console.h
Create a persistent CommandHistory repository that can be used from Lua. It is a direct access to the history and does not require `lineedit`, so it does not require that the script have access to the terminal.
The only consumer of this interface right now will be `gui/launcher` in DFHack/scripts#413
> Allow lua scripts to access a commandline history without a terminal

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
- test/library/gui/widgets.EditField.lua
like "+" and "-", so you can use them as hotkeys in the parent view
This will be used to fix `gui/gm-unit`'s current broken increment/decrement skill functionality
Example usage in DFHack/scripts#424
> allow EditFields to ignore specified keys

- docs/changelog.txt
- library/lua/utils.lua
- test/library/utils.lua
Fixes #2269, which caused a regression in `devel/query` 
The implementation now wraps `_field()` calls with `pcall()` to simplify logic, rather than attempting to detect in advance if `_field()` will work. This simplifies the logic significantly, and notably makes Lua table traversal work properly.
> Rewrite utils.df_expr_to_ref() for consistency, add tests

- library/lua/dfhack.lua
Fixes #2279
Ensures the arguments to `dfhack.run_script` are passed to the underlying script as strings so the commandline input is always a string.
> [dfhack.run_script] pass args as strings when invoking scripts

- conf.py
- docs/Lua API.rst
- library/lua/helpdb.lua
- test/library/helpdb.lua
default wrapping is at 80 columns. This lets console help wrap at 80 columns (instead of the previous 52) but allows `gui/launcher` to choose a width that will work for the current window size.
sphinx wrapping is disabled for the text renderer, so on-disk files will not be wrapped.
> [helpdb] dynamically wrap long help text, preserving block indents

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
- test/library/gui/widgets.Label.lua
Based on the appearance of the native DF help screen scrollbars.
Screenshot of text at top of screen:
Screenshot of somewhere in the middle of the text; note that the size of the scrollbar increases because of the shorter total text size for this tool:
> [widgets.Label] show full scrollbars instead of just scroll icons

- docs/Documentation.rst
- docs/Lua API.rst
Editing pass on the Documentation.rst file (and some Lua API.rst)
- Removed references to pulling short descriptions from "the first sentence" and replaced with references to the `dfhack-tool` directive.
- Added another example of using `...` in command syntax (for comma-separated values)
- Updated example format of in-script docs that reflect what our generated docs now look like
- Clarify that python 3 is now required, not just recommended
- Update reference to old parameters for `ls` builtin command
> update documentation documentation

- docs/builtins/tags.rst
- library/Core.cpp
- library/lua/helpdb.lua
- test/library/helpdb.lua
this allows the new `tags` builtin to serve as the entry point to the new help system. we already point new users to the `tags` command to list the categories. there is no need to direct them to another tool (`ls`) for showing the commands in those categories. `tags <tag>` can serve as an alias for `ls <tag> --notags`.
> [helpdb] list tools in categories with tags builtin

- docs/changelog.txt
- library/modules/Buildings.cpp
Fixes #2301
We keep state to make sure we don't scan civzones more than once, but we don't check that state for civzones when we're scanning all buildings in the buildings cache path.
This change make it so we don't scan for civzones in the general building pass. civzones are only updated when a lookup request for civzones is received.
> don't cache dup civzones when scanning buildings

- docs/changelog.txt
- library/lua/helpdb.lua
- test/library/helpdb.lua
make the tags part of the right column so the left column is easier to read and the tags are also properly wrapped. before:
```
[DFHack]# ls gm
gui/gm-editor        Inspect and edit DF game data.
tags: animals, armok, buildings, dfhack, inspection, items, jobs, map, plants, stockpiles, units, workorders
gui/gm-unit          Inspect and edit unit attributes.
tags: animals, armok, dfhack, inspection, units
```
after:
```
[DFHack]# ls gm
gui/gm-editor        Inspect and edit DF game data.
tags: animals, armok, buildings, dfhack, inspection,
items, jobs, map, plants, stockpiles, units, workorders
gui/gm-unit          Inspect and edit unit attributes.
tags: animals, armok, dfhack, inspection, units
```
> [ls] better formatting for tags output

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
This improves our emulation of scrollbars by allowing the mouse button to be held down to continue scrolling at a fast rate.
The rate is controlled by two user-overridable variables:
```
SCROLL_INITIAL_DELAY_MS = 300
SCROLL_DELAY_MS = 20
```
The user can set the values in `dfhack.init`, e.g. `require('gui.widgets').SCROLL_DELAY_MS = 100`
Some scrollbar implementations stop scrolling when the bar portion crosses where the mouse cursor is. Others continue scrolling in the same direction as long as the mouse cursor is held down, even if it passes the mouse cursor. I followed the latter example since it seemed to make more sense (and it also resulted in simpler code). It would not be hard to change this behavior if others have strong opinions, though.
> [widgets.Scrollbar] hold down the mouse button to continue scrolling

- docs/changelog.txt
- library/lua/gui/widgets.lua
Fixes #2312
This PR implements dragging scrollbars so you can scroll to a specific spot in the text/list.
It simulates up/down scroll events depending on where the cursor is in relation to the spot on the scrollbar where you started dragging. Moving the mouse quickly sends "large" scroll events and moving slowly sends "small" scroll events.
> [widgets.Scrollbar] support click and drag

- docs/plugins/blueprint.rst
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
#2306
Before, `blueprint` would only generate smooth designations for tiles if they are later to be carved into fortifications or engraved. This was done so the user wouldn't be forced to take the time to smooth all the tiles before progressing to the next stage, even if the final area would be smoothed. Smoothing is often done as a final step when the player isn't under so much time pressure to get the level functional. This option allows the user to capture all smooth tiles if they want to.
also get rid of in-plugin help text. we should be displaying the full rendered help text instead.
> [blueprint] add option to capture smoothed tiles

- docs/changelog.txt
- plugins/overlay.cpp
Change text from "[ DFHack Launcher ]" to just "[ DFHack ]" so it doesn't take up so much space.
> Reduce the size of the overlay button

- data/init/dfhack.keybindings.init
- docs/changelog.txt
Fixes #2341
so players with keyboard layouts that prevent them from sending certain keys (e.g. German QWERTZ keyboards and square brackets) can write DFHack commandlines that include those characters.
> [gui/cp437-table] add global keybinding for the on-screen keyboard

- docs/changelog.txt
- library/include/modules/MapCache.h
- library/modules/MapCache.cpp
Fixes #2342
Many callers of `MapCache::setDesignationAt()` simply didn't bother with the optional `priority` parameter. This PR changes the default value of the `priority` param so that by default we will keep the previous value instead of overwrite it. This fixes behavior of all callers, not just tiletypes. Tiletypes was just the one I happened to notice when I filed the bug.
> [tiletypes] don't overwrite dig priority by accident

- docs/changelog.txt
- library/lua/gui/materials.lua
- library/lua/gui/widgets.lua
Fixes #2327
fixed by ignoring just the hotkeys. we could have added the plumbing to ignore all capital letters, but that didn't seem necessary.
Also fix an off-by-one alignment error for hotkey hints in the scrollable list.
> [gui/create-item] Fix hotkeys getting swallowed by the list filter

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/materials.lua
- library/lua/gui/widgets.lua
this allows the capital letter hotkeys to be processed by the list widget without the special-casing of the ignore_keys attribute.
#2327 
This improves the solution merged in #2348
> make the materials dialog filter lcase only

- docs/Lua API.rst
- library/lua/gui/widgets.lua
Fixes #2349 
This PR sets the target position of the scrollbar directly when dragging instead of nudging it closer to the desired position every rendered frame. The nudge strategy was noticeably laggy when dragging large lists.
> make scrollbars more responsive when dragging

- docs/changelog.txt
- plugins/automaterial.cpp
Fixes #2274
If the player clicks the mouse within the SELECTION_IGNORE_TICKS window after finishing a selection, then the z-level changes. Reducing this window to the minimum prevents the issue from happening.
This does not address the root cause, but it does make the issue very unlikely to occur (at least with a human on the mouse).
> [automaterial] prevent z-level from changing after box select

- docs/changelog.txt
- plugins/mousequery.cpp
this happens when TWBT is enabled and multilevel is > 0. `Gui::getDepthAt()` returns inconsistent values for the same position, leading to a mismatch when we "unshift" the coordinates to account for render depth
> [mousequery] fix z-level jumps when clicking quickly

- docs/changelog.txt
- library/LuaApi.cpp
- library/LuaTools.cpp
- library/include/LuaTools.h
- library/modules/Screen.cpp
- Move the Lua::Push functions that somehow ended up in LuaApi.cpp into LuaTools.cpp with the rest of the Push implementations
- Refactor interface key shuttling code from Screen into LuaTools so it can be used by the upcoming overlay v2 implementation
> Move Lua::Push and interface key shuttling logic into LuaTools

- docs/changelog.txt
- library/ColorText.cpp
- library/RemoteServer.cpp
- library/VTableInterpose.cpp
- library/include/MiscUtils.h
- plugins/autobutcher.cpp
- plugins/autoclothing.cpp
- plugins/autonestbox.cpp
- plugins/createitem.cpp
- plugins/devel/itemhacks.cpp
- plugins/devel/kittens.cpp
- plugins/devel/tiles.cpp
- plugins/fix-unit-occupancy.cpp
- plugins/generated-creature-renamer.cpp
- plugins/uicommon.h
and get rid of some "using" statements in headers that were leaking into widespread cpp files.
This will also remove the need for twbt to cargo cult the `int_to_string` function.
> Move generally useful string functions from uicommon to MiscUtils

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui.lua
- allow View:getMousePos() to use a given ViewRect as its frame of reference (before, it only could use self.frame_body, but this made getting the mouse position relative to the frame itself difficult. this capability will be used in the upcoming overlay menu widget
- return self from Screen:show() so we can get the screen instance after calling `show()`. before, code had to get the reference and then call show() on the next line, which is just a waste of space.
> Make View:getMousePos() and Screen:show() a bit more flexible

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
- `widgets.List`: new `getIdxUnderMouse()` function for detecting the list index under the active mouse cursor
- `widgets.List`: shift-clicking now triggers the `submit2` attribute function if it is defined
both items will be used by the upcoming overlay menu widget.
> Allow widgets.List to report hover target and respond to shift-click

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
Reuse FramedScreen frame-drawing logic to allow panels to draw their own frames. This functionality will be used in the new overlay menu widget.
> [widgets.Panel] support frames around panel widgets

- data/init/dfhack.keybindings.init
- docs/builtins/keybinding.rst
Fixes #2384
Go through the keybindings and scope them closer to their area of use so they don't clutter the hotkeys list unnecessarily
the better solution for many of these commands is hotkey guards, but we don't yet support hotkey guards for scripts
see the second commit for actual content changes. the first commit is just reformatting and reordering.
> clean up default keybindings

- docs/changelog.txt
- plugins/autohauler.cpp
- plugins/autolabor.cpp
add missing entries for jobs 241, 242, and 243
this was fixed in labormanager in PR #1566 (see #1561) but was never addressed in autolabor or autohauler
should close #1994
> autolabor/autohauler: add labor entries for 241-243

- docs/changelog.txt
- plugins/autofarm.cpp
insert calls to std::flush as appropriate
fixes #2365
> autofarm: insert missing output flushes

- dfhack-config/overlay.json
#2339
the default config does not include positions so we'll use the default positions from the widgets themselves. This makes the default config agnostic to default position changes (though we might want to include a versioning scheme in the future so that saved positions can get reset if the DF UI changes and the default positions need to be adjusted)
> add a default overlay config with standard widgets

- CMakeLists.txt
- docs/changelog.txt
This makes MSVC warn at a level comparable to what we use on gcc for Linux builds
This basically the same thing for MSVC that we did in #1958 for Linux
> up MSVC warning level to /W3 /WX

- docs/changelog.txt
- library/Core.cpp
Fixes #2324
ensure ``foo.init`` always runs before ``foo.*.init`` (e.g.  ``dfhack.init`` should always run before ``dfhack.something.init``)
> Ensure init script file run order is consistent

- conf.py
- robots.txt
Fixes #2368
Google search does not grok our docs well. It often returns results for outdated versions. ReadTheDocs has an autogenerated robots.txt file we can use, but if we want to hide old DFHack docs from the crawler, we also hide it from the UI (in the flyout menu where doc readers can select the version of the docs they're reading). Therefore, it seems like the best idea to just create a custom robots.txt file to deploy to our docs site that only allows indexing of the `stable` docs. The other versions will still be there, they just won't show up in google search results.
Our generated sitemap.xml *does* appear to correctly give priority to `stable`, but it's easy to see that old docs still seem to outrank current docs in real search results. We may need a custom sitemap.xml as well, …
> Add robots.txt to our HTML docs

- docs/changelog.txt
- library/LuaTools.cpp
- library/lua/gui/widgets.lua
- plugins/lua/hotkeys.lua
- test/library/gui/widgets.EditField.lua
- test/library/gui/widgets.lua
before, when a mouse button was held down, we'd send a single _MOUSE_L and _MOUSE_L_DOWN event and that's it. now we properly send a single _MOUSE_L_DOWN event and _MOUSE_L events for as long as the button is held down. similar for the right mouse button
This PR fixes core behavior and updates lua library code to handle the newly correct behavior.
> Make mouse button event behavior conform to docs

- library/lua/gui.lua
for panels that do not need to be individually identified as belonging to DFHack
> allow frames to be drawn without the DFHack signature

- docs/changelog.txt
- library/lua/gui/widgets.lua
Fixes #1912
if a FilteredList list item has no search key and consists of tokens instead of plain text, synthesize a search key by adding the texts from the constituent tokens
> supply default search key for tokenized text

- docs/guides/overlay-dev-guide.rst
- docs/plugins/overlay.rst
- plugins/lua/dwarfmonitor.lua
- plugins/lua/overlay.lua
#2339 
- make shared functions non-local
- clean up trigger locking so it can be locked and released by gui/overlay
- add quiet mode for commands so dragging widgets in gui/overlay doesn't spam the console with repositioning successful messages
> [overlay] prep lua code for usage by gui/overlay

- library/modules/Units.cpp
(edit)
Now checks that the unit cannot learn or speak, and has either a wilderness population source, a pet/pet_exotic token, or is trainable for war/hunting
This mostly matches the Dwarf Therapist animal checks. Only we care about wild animals too.
> Updates Units::isAnimal

- docs/changelog.txt
- plugins/buildingplan.cpp
Fixes #2441 
Fixes #2358 
when a player cancels out of placing a building type with plan mode enabled and then immediately switches to placing a different building type where plan mode is not enabled, the placement errors array would be erroneously cleared and allow placement of the building. this would cause DF to crash if there were no materials available to build the building with.
> fix crash in buildingplan

- plugins/channel-safely/channel-groups.cpp
- plugins/channel-safely/channel-safely-plugin.cpp
- plugins/channel-safely/include/channel-groups.h
- plugins/channel-safely/include/channel-manager.h
Designations in marker mode don't flag their block(s) as having designations. The scan code attempts to avoid scanning every block in the map.
This combination of factors creates problems when, for example, loading a map where mega projects are in progress with many designations in marker mode as those designations won't get added to groups and thus cannot participate in checks.
To remedy this, I've removed the sometimes randomly checking a block anyways which still leads to strange behaviour and instead have added a `bool full_scan` parameter to function arguments to disable this optimization.. then made sure to build groups with that optimization disabled when first loading the map.
> Implements plugin: channel-safely v1.1b

- docs/plugins/dwarfmonitor.rst
- plugins/lua/dwarfmonitor.lua
Plus documentation
The old cursor widget behavior can be set with `"coords_type":"mouse_ui", "coords_short":true`. The default is unchanged.
> Dwarfmonitor cursor widget config

- plugins/channel-safely/include/inlines.h
Found a critical typo for an inline check. The check is not used heavily, so the broken behaviour will have been confined to a few niche edge cases.
> Implements plugin: channel-safely v1.1.1b

- library/proto/Basic.proto
- library/proto/BasicApi.proto
- library/proto/CoreProtocol.proto
- plugins/dig-now.cpp
- plugins/proto/AdventureControl.proto
- plugins/proto/DwarfControl.proto
- plugins/proto/ItemdefInstrument.proto
- plugins/proto/RemoteFortressReader.proto
- plugins/proto/isoworldremote.proto
- plugins/proto/rename.proto
- plugins/proto/ui_sidebar_mode.proto
- plugins/stockpiles/StockpileSerializer.cpp
- plugins/stockpiles/proto/stockpiles.proto
These are the salvageable parts from the aborted protobuf upgrade. It's not much.
proto files are explicitly declared as proto2. this was the default, but if we ever try to upgrade in the future, this will save us compatibility warnings.
a few places where we were using std identifiers without using the `std::` prefix have been cleaned up.
> explicitly declare namespaces and proto versions

- CMakeLists.txt
- depends/protobuf/CMakeLists.txt
- depends/protobuf/google/protobuf/stubs/hash.h
This PR will likely prevent us from building with old msvc, but we need these changes for the updated compiler used in our buildmaster build env (which is also required for DF 50 compatibility). if we need to do another 0.47.05 release, it will have to be done on top of the v0.47.05 branch.
> make tree compatible with new msvc compiler in cross compilation env

- .github/workflows/build.yml
as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> migrate usage of set-output (required by github)

- docs/dev/Lua API.rst
Since non-integers are rejected.
> Add math.floor to module example in Lua API

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
#2497
If dragging is enabled for a panel, it can be clicked and dragged around within its parent bounds (which could be the whole screen). Keyboard dragging is supported, though the hotkey to initiate keyboard dragging is left up to the containing Screen.
Resizing will be supported in a separate PR.
> Support drag and drop for DFHack Panel widgets

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
Fixes #2497
If resizing is enabled for a panel, it can be clicked and stretched around within its parent bounds (which could be the whole screen). Keyboard resizing is supported, though the hotkey to initiate keyboard resizing is left up to the containing Screen.
> Support resizing for DFHack Panel widgets

- library/Core.cpp
- library/modules/Screen.cpp
It's not good that we have to do this. This has the nasty effect of making the full screen element disappear if we cover even a single tile of it. For example, the entire minimap will disappear if we cover a corner.
This also doesn't seem to work properly for very large offset tile groups, such as the logos on the title screen. They don't appear to have all their tiles tagged with their id. the dinosaur, for example, only has the upper left 5x5 tiles marked, yet the image extends far beyond that range.
I'm beginning to think that maybe we *should* render straight to the SDL surface and bypass all this nonsense.
> prevent "offset" tiles from occluding DFHack-drawn tiles

- library/lua/gui.lua
- library/modules/Screen.cpp
and clean up more conflicts with other rendering layers.
The anchor layer still gives us trouble. it will overwrite us unless we cover the upper left tile of the anchor graphic, and then the entire anchor graphic will disappear. not ideal, but it's a start
> Render tile textures if specified in the pen

- CMakeLists.txt
- library/CMakeLists.txt
- library/Core.cpp
- library/Hooks-darwin.cpp
- library/Hooks-linux.cpp
- library/Hooks.cpp
- library/include/Core.h
- library/include/Hooks.h
as per the files in the new DFHack/hooks repo. Note that this API does not break our current injection strategy. Once we have a version that uses this new API, we can turn down the SDL-related injection code.
This PR builds a stub shared object for Linux and OSX and installs it in the main DF dir (where the dfhooks API knows to look for it). That stub calls into hack/dfhack.(so|dylib).
For Windows, where all the dlls are in the main DF directory anyway, there isn't much reason to have an additional stub, so the hooks are baked directly into the dfhack library, and we can just change from building the library as SDL.dll to dfhooks.dll.
> Prepare for the hook API

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- library/modules/Gui.cpp
- implement Gui::getMousePos()
- implement Gui::getDepthAt()
- don't cache USE_GRAPHICS anymore (it was static before. now it's not)
- allow Label widgets to write the tiles that are specified in the pens (was using :char() instead of :tile())
- expose getMousePixels to Lua
- docs
> Baby GUI steps

- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
this significantly reduces CPU utilization when DFHack-owned screens are visible.
> only do a full refresh when needed

- library/modules/Screen.cpp
There are a *lot* of textures that might be shown in graphics mode, but readTile can only return one. I decided to return the first tile found when scanning in this order:
screentexpos (unit), screentexpos_item, screentexpos_building_one, screentexpos_background_two, screentexpos_background
From examining several tiles with `devel/inspect-screen`, these seem to be the interesting ones. We could certainly extend the search list more in the future if we find we're missing something, though.
Also, the screen is specified in RGB values, but our pens use 16-bit color codes. I translate to the old codes if the color is a perfect match, but otherwise I just return 0 for the color. We could potentially improve on this by finding the *closest* color, if we need to.
> implement Screen::paintTile for both modes and readTile for graphics mode

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
We've been adding a lot of cool functionality to Panel, which OverlayWidgets have not been able to access since they inherit from Widget, not Panel. This PR shifts the inheritance to Panel so OverlayWidgets can be dragged, resized, and framed.
Also, allow overlay widgets to mark themselves as `always_enabled` if they want to control their own enablement via the overlay trigger mechanism. This will be used for the new `gui/pathable`.
> Make OverlayWidget inherit from Panel and allow overlays to be perma-enabled

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/lua/gui/dwarfmode.lua
- library/modules/Gui.cpp
in particular, return the correct map dimensions in getDwarfmodeDims()
> clear out obsolete area map and menu logic from the Gui module

- data/init/dfhack.keybindings.init
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
comment out keybindings for tools that aren't ready yet. also, we need to consider how we want to re-enable them eventually since most viewscreens are gone. the list of hotkeys associated with `dwarfmode` may be too long if we just blindly re-enable.
also allow overlay widgets to declare affinity with `all` viewscreens so the hotkeys widget doesn't have to list all the viewscreens individually.
also introduce a new snazzy multi-tile DFHack logo for the hotkeys overlay widget. It looks likd this:
maybe we can get some tile textures in there once we figure out how to add them to the game. Do we need a "mod" to add the textures?
> comment out most keybindings and revamp hotkeys widget

- library/include/DataIdentity.h
- plugins/ruby/codegen.pl
- plugins/ruby/ruby-autogen-defs.rb
Fixes https://github.com/DFHack/df-structures/issues/498
Required by https://github.com/DFHack/df-structures/pull/500
Deliberately targeting v0.47.05 first since this was tested there (and fixes an alignment issue)
> codegen: stub for std::map

- data/init/dfhack.tools.init
- docs/dev/Lua API.rst
- library/LuaTools.cpp
- library/lua/gui.lua
DF does not clear the `enabler->mouse_lbut_down` after the first run through a viewscreen's `feed()` function. Since we guarantee to Lua scripts that only one `keys._MOUSE_L_DOWN` event will be sent per button press, we've been manually clearing the `enabler` state so `enabler->mouse_lbut_down` will be false for the next run through `DFHack::Lua::PushInterfaceKeys()`.
This method worked fine in the past since DF didn't do much with the mouse. Now that it does, writing to enabler has nasty side effects on DF.
For example, adding a `keys._MOUSE_M_DOWN` event to capture middle mouse button clicks to our code also required clearing the `enabler->mouse_mbut_down` state. This immediately broke map dragging with the middle mouse button.
This PR removes the code that modifies `enabler` state and …
> Get correct mouse button down behavior in Lua without overwriting enabler fields

- library/LuaApi.cpp
- library/LuaTools.cpp
- library/include/modules/Screen.h
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- library/modules/Screen.cpp
Provides a gui.ZScreen class that lua gui tools can inherit from instead of gui.Screen. It allows the parent viewscreen to receive events if the ZScreen subclass doesn't handle them. It also allows other ZScreen subclass screens to raise to the top if windows on those screens are clicked with the mouse. In addition to providing "real window system" behavior for DFHack windows, it also lets the player interact with the map while DFHack tool windows are being shown and lets the game progress while DFHack tools are up if the game is unpaused. Note that DFHack tools can still choose to inherit from gui.Screen if they want the previous "modal" behavior.
ZScreen subclasses should *not* override the `onInput()` function. Instead, they should delegate any input processing to contained widgets …
> framework for passthru, z-order swapping windows

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/modules/Gui.cpp
useful for `devel/inspect-screen` and similar tools that want to know what the current DF screen is. it's not so obvious now that there can be multiple Z-layers
> add Gui::getDFViewscreen and Lua binding

- build/win32/set_df_path.vbs
- build/win64/set_df_path.vbs
This enables specifying the pathname on the command line for `set_df_path.vbs`, which is a longstanding pet peeve of mine
> set-df-path: accept path on command line

- data/init/dfhack.keybindings.init
since vanilla df comes with its own keybinding now
> remove twaterlvl from the global keybinding list

- library/LuaTools.cpp
I don't think anyone uses these functions currently and they're often removed from any program that has Lua scripting available.
> Remove os.execute and io.popen

- library/lua/gui.lua
- plugins/lua/hotkeys.lua
- plugins/lua/overlay.lua
- disappears on click outside its borders
- disappears on r-click
- mouse over the help panel counts as "over the menu" (so the menu doesn't close if the player moves the mouse to the help text)
- menu panels appear next to the logo hotspot instead of over it, allowing players to avoid clicking on the wrong item if they intend to click on the logo
> update behavior of hotspot menu

- package/linux/dfhack-run
This is useful for symlinking this script somewhere on your $PATH, and having it work without having to find the correct directory.
> Allow symlinked dfhack-run on linux

- ci/download-df.sh
- docs/Core.rst
- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
- library/Core.cpp
- library/lua/dfhack.lua
- plugins/autogems.cpp
- plugins/rendermax/renderer_light.cpp
- plugins/tweak/tweaks/title-start-rename.h
default script path has changed from:
#. :file:`dfhack-config/scripts`
#. :file:`data/save/{<region folder>}/raw/scripts` (only if a save is loaded)
#. :file:`raw/scripts`
#. :file:`hack/scripts`
to:
#. :file:`dfhack-config/scripts`
#. :file:`save/{world}/scripts` (only if a save is loaded)
#. :file:`hack/scripts`
likewise, init.d folders are now in the root dir or in the root of the savegame dir instead of in raw/init.d directories.
> adjust to new directory layouts

- CMakeLists.txt
this removes cmakefile code to detect msvc express, which did not support folder grouping in projects, because we only support vs 2022 on windows anyway, all available editions of vs 2022 support folder grouping in projects, and msvc express itself was discontinued with vs 2019
> remove compatibility with msvc express

- docs/changelog.txt
- plugins/autofarm.cpp
because C++ std::map is not the same as a ruby table
should close #2656
> autofarm: fix repetition in status output

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
Brief outline of the way zones + buildings interact:
1. Zones have a contained_buildings vector which is a list of buildings that meet a particular criteria
2. Buildings have a relations vector, which appears to be a list of civzones that contain them
3. The criteria for a building being put into a zone appears to be building->canBeRoom()
When a building is placed in a zone (including abstractly), zone->contained_buildings adds the building, and the civzone is added to the building's relation. When the building is uninstalled, its relations vector is used by the game to remove the building from the civzone's contained_buildings list (quite sure on this point). When a civzone is deleted, its contained_buildings list is used to update the contained building's relations list when it is …
> Zone <-> building interactions

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Maps.h
- library/modules/Maps.cpp
- plugins/autofarm.cpp
- plugins/embark-assistant/survey.cpp
This exposes getBiomeType to lua as its useful for farms and fixes the naming scheme. While I'm here, I fixed getBiomeTypeWithRef for consistency
> getBiomeType naming, docs, expose to lua

- data/orders/basic.json
This does require the lye to be in buckets rather than barrels for the limits to apply to a reasonable amount of lye. Make sure that you bar barrels from the lye stockpile.
> Attempt to fix lye order limits

- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
it was made for gui/pathable, but that became a ZScreen this option made me uncomfortable for overlays. it didn't seem like the right user experience
> remove unused always_enabled attribute for overlays

- library/include/MiscUtils.h
- library/modules/Buildings.cpp
This addresses the style changes, as well as implementing support for removing zones which have ever had a squad assigned to them. The removal of zones from squads is conservative, and handles duplicates if they arise - though I haven't seen it
It *is* worth noting that I discovered surprisingly that there isn't a 1:1 mapping between the zone's room-squad vector, and the squad's room-zone vector. A zone remembers any squads ever associated with it, whereas squads proactively clean up their zone associations
Additionally, given some of the suspicion about vanilla bugs in this kind of bidirectional mapping, I'm not sure how generally conservative the civzone changes want to be. At the moment I've taken the approach generally of df-is-not-to-be-trusted, which is somewhat borne out by some …
> More civzone <-> building work, add removing zones with associated squads support

- data/init/dfhack.keybindings.init
- docs/changelog.txt
global keybinding for gui/quickcmd: Ctrl-Shift-A
according to https://defkey.com/what-means/ctrl-shift-a it's not likely to conflict with any system hotkeys
Fixes #2697
> add keybinding for gui/quickcmd

- plugins/tailor.cpp
i think the previous window of 600 ticks was allowing it to miss bookkeeper runs, causing tailor to run less often than intended
reducing to 50 to reduce the chances of this happening
> tailor: increased check frequency

- .github/workflows/build.yml
- build/build-win64-from-linux.sh
- docs/dev/compile/Compile.rst
Thanks to @BenLubar for setting up the official build images on ghcr.io, we can now have automated win64 builds without requiring a win64 builder.
This updates the build to now generate Windows artifacts (for Steam users) for every single PR and commit. See here (scroll down):
https://github.com/kelvie/dfhack/actions/runs/4002114641
One side effect this will have is that the build now takes 20 minutes, as the new bottleneck is this new cross-win64 build, and this may be an issue with e.g. PRs that should be quick.
I haven't tried getting `cccache` working, though I don't think this will help the worst case PRs anyway.
> Add Github Actions build of win64 artifacts, and update compile instructions.

- data/orders/military_include_artifact_materials.json
- docs/plugins/orders.rst
Fixes #2718
Remove the creation of platinum weapons from military.json since they are normally only produced by strange moods and can't be crafted normally.  Retain the original code as data/orders/military_include_artifact_materials.json
> No platinum weapons

- docs/plugins/orders.rst
Fix documentation to show proper filename for library/military_include_artifact_materials
> Include proper name for library/military_include_artifact_materials

- plugins/dig.cpp
Found that the only compiler errors were cause by an (apparently unused) header include and a single other line that apparently just needed to be updated because some structures change.
I tested all the types of dig* commands and it seems to work fine. I also confirmed that the line of code changed is correctly setting the default priority to 4000.
I'd like to try creating a GUI for dig to allow mouse based circle/ellipses/etc... drawing and also adding a WxH label and maybe even X/Y guidelines to the designation to make creating symmetrical designations easier, but this is a good first step.
> Fix dig plugin and enable building it

- docs/changelog.txt
- library/include/modules/Screen.h
- library/modules/Screen.cpp
Fixes #2740
Guard against multi-insertion in Screen::Hide
> Solve the inception problem: prevent screens (e.g. gui/launcher) from hanging when they attempt to dismiss and show themselves simultaneously

- docs/changelog.txt
- plugins/getplants.cpp
Hey, just some small first-timer fixing issues I found for the *getplants plugin*.
Fixes #1805 
ID parameters are now added to `plantNames` with a `toUppercase` call, so case doesn't matter for input.
Fixes #2043 
The `designate` call was returning *false* for all trees because the `ripe` check was failing.
My guess is that the trees either have a different lifetime or aren't ripe but it doesn't matter because they can still be chopped. I'm wasn't sure what the best way to fix this one was, so I added an `istree` check for the tile and now the check passes if `istree || isripe`.
I did some brief testing and it seems good.
> getplants fixes

- library/lua/script-manager.lua
it just takes too long (>1s) to refresh every time. manual refresh with script_manager.reload() is still available for devs who need it
This change massively speeds up initial load and page changes in the (in-progress) `gui/control-panel`
Once we support workshop mod scripts, I expect we'll want to call `reload()` after we modify the script paths.
> don't autorefresh the enableable tools list

- data/init/dfhack.keybindings.init
- docs/Quickstart.rst
- docs/changelog.txt
Depends on DFHack/scripts#579
should we give the control panel an alternate hotkey for keyboards without a usable backtick? it's not as important as `gui/launcher`, so I'm not sure it's warranted.
> Update hotkeys and quickstart guide for gui/control-panel

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
I changed this a while back due to a misunderstanding. This PR undoes the change to fix the old (and correctly documented) behavior, but makes it ok to do what I mistakenly thought you could/should do (i.e. pass a texture id directly)
> allow tile in Label tokens to be either pen or id

- plugins/autobutcher.cpp
- plugins/autochop.cpp
- plugins/automelt.cpp
- plugins/autonestbox.cpp
- plugins/autoslab.cpp
- plugins/buildingplan.cpp
- plugins/examples/persistent_per_save_example.cpp
- plugins/nestboxes.cpp
- plugins/seedwatch.cpp
this allows the plugins to function normally even after one world is exited and a different world with a lower frame counter is loaded
> reset the saved frame counter on new world

- .github/workflows/build.yml
- build/build-win64-from-linux.sh
Stonesense was not being built by github actions for steam v50 builds. Thus not matching release.
> Always build stonesense

- .github/workflows/build.yml
Rather than calling `env` as part of the commandline.
Checked the zip created on my fork for stonesense, and it's there.
> Cleanup: GHA: use declarative env

- docs/changelog.txt
- plugins/automelt.cpp
i.e. that no longer refer to valid stockiples, which can happen if the persisted data is from another game
> [automelt] improve resistance to morphed building ids

- docs/dev/Lua API.rst
- library/include/modules/Gui.h
- library/include/modules/Screen.h
- library/modules/Gui.cpp
- library/modules/Screen.cpp
next steps for the focus string update
this allows the focus strings from the underlying DF viewscreen to come through, even when there is an unfocused DFHack tool window on the stack. Note that *focused* DFHack tool windows will be reflected in the focus string and will (correctly) *not* let the hotkey guard to function.
> allow focus string generation to fall through unfocused ZScreens

- library/lua/gui/widgets.lua
rationale:
- vanilla scrollbars dont get shorter than 2.
- 2-tall 'bars are easier to click on than 1-tall 'bars.
- this avoids having to make short custom graphics for 1-tall tiles, which most of the time look terrible...
cons:
- short scrollbars are cool : (
> increase min scrollbar height to 2 (from 1)

- docs/changelog.txt
- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
Fixes #2651
solves issue where initial races aren't configurable until tick 6000
> [autobutcher] tweak defaults, load initial races immediately

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
Add a `case_sensitive` attr to `FilteredList` to allow for case insensitive matching. Defaults to `true` so that existing `FilteredList`s keep the same behavior.
> Add case_sensitive attr to FilteredList

- data/orders/military.json
- docs/changelog.txt
It is not possible to create a work-order for making silver crossbows, so the silver crossbow recipe belongs in the alternative military library with other artifact/non-craftable weapon recipes.
It's already present in the library/military_include_artifact_materials work-orders, so it simply needed removal from the vanilla library/military orders.
> Remove silver crossbow work-order from library/military

- library/LuaApi.cpp
- library/LuaTools.cpp
- library/include/LuaTools.h
the circular template expansion went unnoticed before since we've never tried to Push a map of maps. Now that we are (to solve the Lua stack smashing problem in #2848), gcc doesn't like it. msvc seems ok with it, but it's still something we should fix.
> add const & to Push overloads; remove circular def

- docs/changelog.txt
- plugins/channel-safely/channel-manager.cpp
- Revises a few log lines
- Adds d_assert macro to replace assert usage
- provides a log line printed to the console to indicate d_assert failed in Release/Debug builds
This resolves #2818 (presumably)
> Implements plugin: channel-safely v1.2.3

- docs/changelog.txt
- plugins/nestboxes.cpp
Fixes #2846
in DF 50, forbidding an item is not enough to cancel the associated job. we now need to do that manually.
> [nestboxes] remove in-progress jobs when protecting fert eggs

- library/lua/dfhack.lua
This PR makes the pattern for matching `--@ module = true` match only from the start of a line, fixing the error `Parse error: ...` for lines like annotations `---@param foo bar`.
This is especially useful as if we start annotating the Lua codebase we could automatically generate future definitions for autocomplete/lsp.
> Fix annotation parse error

- docs/changelog.txt
- plugins/nestboxes.cpp
The rewrite in #2773 introduced a bug (identified by KMFrench on Discord) where nestboxes themselves would be forbidden, which prevents egglaying citizens from using them since the nestboxes would be claimed before use. The previous version of the plugin handled this by skipping the first item in `contained_items`, which is the building material (in this case, the nestbox).
This fix limits the `forbid` flag manipulation to egg items only, which should be a reasonable limitation that still allows the plugin to serve its purpose.
> nestboxes: avoid forbidding non-eggs

- docs/changelog.txt
- plugins/autobutcher.cpp
* Add check for unit->name.nickname field is not an empty string
* Refactor repeated checks for inappropriate and protected units
Note: Dwarf Fortress is not persisting nicknames set on units from the Dwarf Fortress naming interface if those units don't already have `has_name` set. In order for nicknames created in-game to be persisted, the user needs to be running `fix/protect-nicks`.
> Autobutcher check for nickname field being set - fix for #2871
