DFHack/dfhack

- dfhack.init-example
Add adventure mode keybinding context to adventure mode keybindings.  Add a keybinding to gui/companion-order.
> adventure keybind contexts, bound companion-order

- plugins/autolabor.cpp
- plugins/manipulator.cpp
- plugins/mousequery.cpp
- scripts/devel/export-dt-ini.lua
* autolabor, manipulator: Add BUILD_CONSTRUCTION and BUILD_ROAD labors
* mousequery: Support "toggle engravings" sidebar mode
* devel/export-dt-ini.lua: Add body_part_flags
> Update some plugins/scripts for 0.40.22

- scripts/devel/export-dt-ini.lua
From https://github.com/splintermind/Dwarf-Therapist/commit/356ae80
> Update devel/export-dt-ini for 0.40.21+

- NEWS
- Readme.html
- Readme.rst
- dfhack.init-example
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/eggs-fertile.h
- plugins/tweak/tweaks/max-wheelbarrow.h
* `eggs-fertile`: Displays an egg fertility indicator on nestboxes
* `max-wheelbarrow`: Allows assigning more than 3 wheelbarrows to a stockpile
> New tweaks

- scripts/gui/hack-wish.lua
Yeah, not sure what the heck I was doing there before.
> Made restrictive mat filter work properly

- scripts/siren.lua
Runs now without exception/error and adds emotions correctly. Seems to work as intended. Fixes #438.
> Update siren.lua for emotions

- library/modules/EventManager.cpp
Doing a pull request instead of just merging it myself because the bug never happened for me in the first place and others are still testing it.
> EventManager: Fix a crash bug with EQUIPMENT_CHANGE event.

- plugins/search.cpp
> Add support for searching more lists

- plugins/stockpiles/stockpiles.cpp
> Create `stocksettings` directory on startup

- NEWS
- scripts/hfs-pit.lua
Via notfood, here:
http://www.bay12forums.com/smf/index.php?topic=139553.msg5984896#msg5984896
> Fix hfs-pit feature search

- Compile.rst
- Contribute.rst
- Contributing.rst
- fixTexts.sh
> Contributing doc

- NEWS
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/include/modules/Units.h
- library/modules/Buildings.cpp
- library/modules/Units.cpp
- plugins/autolabor.cpp
- plugins/catsplosion.cpp
- plugins/dwarfmonitor.cpp
- plugins/manipulator.cpp
- plugins/petcapRemover.cpp
- plugins/search.cpp
- plugins/showmood.cpp
- plugins/tweak/tweak.cpp
- plugins/zone.cpp
Refactored many utility functions into the Units and Buildings modules. Also got rid of various gcc warnings.
> Zone plugin cleanup

- NEWS
- Readme.rst
- dfhack.init-example
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/tradereq-pet-gender.h
> New tweak to display pet genders on trade request screen

- scripts/ShowUnitSyndromes.rb
The variable names were changed back in 2013 but this script never got updated.
> fix ShowUnitSyndromes

- NEWS
- scripts/add-thought.lua
Not used much, but still very much a problem that it wasn't there.
> Added subthought properly to add-thought.

- NEWS
- scripts/gui/hack-wish.lua
So entirely unsure why I did that weird thing before.
> Made hack-wish stack properly.

- package/linux/dfhack
> LD_PRELOAD should use colon rather then space as delimiter

- package/linux/dfhack
> avoid dangling colon

- library/Console-darwin.cpp
- library/Console-linux.cpp
- library/Console-windows.cpp
- library/Core.cpp
- library/include/Console.h
> Adds new console methods and commands to hide/show console. 

- scripts/show-unit-syndromes.rb
This fixes mental/physical attribute-changing syndromes.
> Fix show-unit-syndromes (part 2)

- library/lua/dfhack.lua
> Fix lua environment persistence

- NEWS
- Readme.rst
- scripts/exportlegends.lua
Originally written by Mason11987, adapted and included with permission.
The 'info' option now exports more data than is possible in vanilla, to a "region-date-legends_plus.xml" file developed to extend the World Viewer utility and potentially compatible with others.
> exportlegends -  more data in legends_plus.xml

- Readme.rst
Fixed typos.  Made hyperlinks inline.  Some editorial changes for
clarification.  Updated and expanded introduction.  Fixed a few
formatting errors.
> Update and clarify readme

- library/PlugLoad-posix.cpp
> Pass RTLD_LOCAL to dlopen()

- Lua API.rst
- NEWS
- plugins/building-hacks.cpp
- plugins/lua/building-hacks.lua
Fixed buildings not consuming correct value of power. Added way to ignore unpowered state. Added setPower/getPower to change how much power building uses on the fly.
> Building hacks changes.

- plugins/autohauler.cpp
Get rid of useless code, refined comments, add ability to change frame skip
> Small update

- scripts/fix/blood-del.lua
This version of blood-del.lua will catch the new bodily emissions too, mostly from gremlins or gnomes.
> Extend fix/blood-del to include tears and sweat

- plugins/manipulator.cpp
Map doesn't make sense when we're iterating over everything anyway.
This should also correct the compiler issue @expwnent was seeing.
> Simply maniuplator professions by adding the text token to the SkillColumn entries

- NEWS
- plugins/lua/stockflow.lua
- plugins/stockflow.cpp
- travis/lint.py
* A potential memory leak has been closed.
* An error message had been reported in arena mode, as reported by Propman and scamtank in the forum thread.
* The DF version is no longer used for deciding which reactions to exclude from the list.
* Ballista arrow heads had been getting ordered incorrectly.
> Stockflow repairs

- plugins/manipulator.cpp
Pro-tip from @lethosor. Hopefully the last PR related to manipulator professions (at least for a while).
> Remove explicit tokens and use ENUM_KEY_STR for profession templates

- NEWS
- scripts/gui/hack-wish.lua
Also made it so that it can be used with dfhack.script_environment, though some coroutine wizardry is required to actually have it function correctly (meaning return success/failure values).
> Made hack-wish assign quality properly.

- plugins/autolabor.cpp
Fix bug in autolabor that caused DISABLED skills to be modified in some circumstances.
Try harder to develop specific skills on dwarves.
Change handling of jobs that use tools.
> Autolabor changes

- NEWS
- Readme.rst
- scripts/warn-starving.lua
With minor changes to the original version; it doesn't repeat here.
Closes issue #596.
> Add warn-starving.lua

- plugins/search.cpp
> Add look menu search

- NEWS
- Readme.rst
- scripts/points.lua
Adds a trivial but useful script, and adds some useful documentation I needed last week.  Also closes #670.
> Points.lua and readme

- scripts/gui/gm-editor.lua
Fix a small bug that broken some flag editing.
> Fix bug in gm-editor

- plugins/lua/luasocket.lua
- plugins/luasocket.cpp
Added new functions: select, set(non)blocking, isBlocking.
Set default to non-blocking. Added "would block" to ignored errors.
> Lua socket: some additions and fixes.

- Contributors.rst
- NEWS
- Readme.rst
- scripts/armoks-blessing.lua
- scripts/brainwash.lua
- scripts/elevate-mental.lua
- scripts/elevate-physical.lua
- scripts/make-legendary.lua
- scripts/pref-adjust.lua
- scripts/rejuvenate.lua
[*Source on the wiki*](http://dwarffortresswiki.org/index.php/User:Vjek)
Vjek's scripts are pretty much classic at this point, and there's a reasonably wide user base.  However installation can be tricky - at the very least, more so than coming included - and not being on Github Lethosor's proposed inclusion system won't work.  Given that upstream changes are very slow now the scripts are mature, I suggest merging them entirely.
Currently (two commits) all I've done is import the .lua files and added appropriate documentation.  It is likely that style or substantive changes might be needed (and I've heard of fourth-party-updates), so this pull request is for discussion rather than immediate merging.  Thoughts?
> Import Vjek's scripts from the wiki

- scripts/exportlegends.lua
Fixing assume identities since it causes a crash.
> Fixing assume identities since it causes a crash.

- scripts/deteriorateclothes.rb
- scripts/deterioratecorpses.rb
- scripts/deterioratefood.rb
- scripts/starvingdead.rb
[Bay12 forums thread](http://www.bay12forums.com/smf/index.php?topic=150782).  The `deteriorate*.rb` scripts could probably be merged, but I'm terrible with Ruby.
> State of decay - Onmiclasm's FPS boosting scripts

- plugins/zone.cpp
> zone: Fix typo in help text

- library/include/modules/Constructions.h
- library/modules/Constructions.cpp
- plugins/automaterial.cpp
> Automaterials: Partial fix for constructing floor over existing floor

- plugins/eventful.cpp
Can someone test if it's working? If i'll find time to do it myself i'll change this message...
> Add furnace to fillsidebarmenu hook

- docs/Plugins.rst
restrictliquid is actually restrictliquids.
This time with lengthened underline for sphinx.
> Typo Restrictliquid fixed

- docs/Compile.rst
- docs/Contributing.rst
- docs/Introduction.rst
minor to Linux; new section re compiling documentation; many small fixes.
Introduction.rst: fix typo and remove erroneous end version for OSX.
All changes have been tested as compiled HTML.
> Compile.rst: major updates to Windows and OSX sections;  

- package/linux/dfhack
This will help with the zlib preloading issue
Although waiting until this PR is accepted might be a good idea
Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#28
> Use distro_fixes.sh from LNP if it exists

- scripts/exportlegends.lua
i've added the following to exportlegends
* export poetic, musical and dance froms
* export written content, contents of artifacts
* additional site & structure date
* hf sex and race
* entity positions and assignments
> Additional legend exports

- plugins/ruby/building.rb
See also: 248331a1967d2527a13bcf259f35bffe4dec86b8, #808
> Add support for grates and bars to Ruby.

- plugins/autogems.cpp
Now disabled by default, until the workshop order (o-W) is toggled.
Now ignores forbidden gems, among other flags.
> Autogems bugfixes

- plugins/autolabor.cpp
- plugins/devel/autolabor2.cpp
Stop spamming unit has unknown job. 
Accidentaly linked wrong pull request
> add new jobs to autolabor

- library/include/LuaTools.h
- plugins/eventful.cpp
Fixed eventful and other places where it was broken.
> Some simplification to eventful

- NEWS.rst
- docs/Lua API.rst
- plugins/lua/building-hacks.lua
For automatic animation and gear positions.
Simplifies using building-hacks yet more
> Add auto-gears mode for building hacks

- scripts/exportlegends.lua
* added export for materials and item types of masterpiece events
* added export for occasions and schedules (requires datastructures, see pull request on df-structures)
* export underworld spire name (if name field available)
> Additional exports (masterpiece events, occasions and schedules)

- scripts/view-item-info.lua
https://www.reddit.com/r/dwarffortress/comments/4aq6wp/thats_1520000_kgm3/
> Make view-item-info not show density as 1,000 times what it actually is

- library/lua/gui/dwarfmode.lua
This will make other stuff that depends on dfhack.gui.getSelectedBuilding work with workshop overlay
> add onGetSelectedBuilding to workshop overlay

- plugins/lua/eventful.lua
E.g. when destroying buildings
> Fix eventful not showing sidebar sometimes

- plugins/lua/building-hacks.lua
Now it should select the gear color correctly
> Fix building-hacks color for auto_gears option

- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/zone.cpp
Also colorize output from the zone plugin, and clean it up a tiny bit.
> Implement #804, move some functions to Units

- plugins/autogems.cpp
Requires: DFHack/df-structures#113
> adjust autogems to work with the workshop profile changes

- dfhack.init-example
- plugins/lua/stockflow.lua
New manager order flags, new manager interface behavior, and no limit on order number.
> Updating Stockflow for v0.43

- plugins/lua/stockflow.lua
There's a chance that not doing so could lead to a crash, somehow.
> Incrementing the manager order id properly.

- plugins/ruby/codegen.pl
Sizes were calculated using Visual Studio 2015 Update 3.
> Add windows container sizes to ruby codegen

- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader.cpp
I'm not sure how to exclude the submodule from the commit.
> RemoteFortressReader changes

- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader.cpp
This also include the df-structures update that's required for new variable names.
> RemoteFortressReader updates

- docs/Plugins.rst
More improvements in labormanager. This version is _much_ better at maximum labor allocation.
> Labormanager 0.43.05 r1

- plugins/labormanager.cpp
This fixes
>LABORMANAGER: Cannot deduce labor for make job, workshop type Bowyers
> labormanager: support for jobs in bowyer's shop

- library/include/modules/MapCache.h
- library/modules/Gui.cpp
- library/modules/Maps.cpp
- plugins/building-hacks.cpp
- plugins/burrows.cpp
- plugins/stocks.cpp
- plugins/workflow.cpp
> Avoid non-trivial bitfield constructors

- plugins/lua/stockflow.lua
This appears to resolve #1044.
> stockflow: Fix "integer expected" problem in stockflow

- plugins/buildingplan-lib.h
- plugins/workflow.cpp
> df::dfhack_material_category has no constructor, must be manually initialized

- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader/remotefortressreader.cpp
Included dwarf professions and noble positions in RemoteFortressReader
> Unit profession

- library/lua/makeown.lua
There is a lot more errors in this file, mostly called unk variables... I bet they have names, I've tried to figure out what they were renamed too, but I'm not fully understanding the xml.
> fix of relations errors.

- library/lua/repeat-util.lua
> Make repeatUtil.cancel work even when called from the callback.

- plugins/labormanager.cpp
> exclude on-duty military personnel from health labor check

- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader/building_reader.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
I've got everything I need for my own version increment, so I might as well make the PR
> RemoteFortressReader updates.

- plugins/orders.cpp
> Fix fencepost error in orders import.

- library/RemoteServer.cpp
use unique_ptr instead, ~~with the C++14 helper function make_unique.~~
> auto_ptr is deprecated

- plugins/proto/RemoteFortressReader.proto
- plugins/remotefortressreader/df_version_int.h
- plugins/remotefortressreader/remotefortressreader.cpp
To be merged before the next dfhack release.
> Remote reader

- plugins/autochop.cpp
> Add tree product exclusions to autochop

- CMakeLists.txt
Still need to write release notes and add tags.
I can't push this to develop, so sending as a PR.
> Partial preparation for 0.44.07-alpha1.

- build/win64/install-debug.bat
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/embark-assistant.cpp
- plugins/embark-assistant/finder_ui.cpp
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/overlay.cpp
- plugins/embark-assistant/survey.cpp
Corrected reanimation detection
I've tried the modified code in a DF installation, and it does seem to work as intended.
> Corrected reanimation detection

- plugins/dig.cpp
This is not extensively tested. :)
> check for tile material == MINERAL in digtype (#1243)

- library/lua/gui.lua
> fixed bug causing gui scripts to fail when sidebar is closed

- .gitmodules
This is mostly a test to see whether I set BuildMaster up correctly to build pull requests. It is also a valid change to the DFHack repository which we can merge as the last step in this test.
> Replace submodule URLs with relative URLs so they will be downloaded via the same transport as the main repo (HTTPS or SSH, usually)
(Don't merge until I say I'm ready.)
> Pull request test

- library/lua/dfhack.lua
> Prepend script name to qerror messages, if applicable

- docs/changelog.txt
- plugins/stockpiles/StockpileSerializer.cpp
>  stockpiles: Fix unusable and usable loading for weapon and armor

- plugins/advtools.cpp
- plugins/cursecheck.cpp
- plugins/diggingInvaders/diggingInvaders.cpp
- plugins/dwarfvet.cpp
- plugins/labormanager/labormanager.cpp
- plugins/manipulator.cpp
- plugins/petcapRemover.cpp
- plugins/rendermax/renderer_light.cpp
- plugins/siege-engine.cpp
Addresses parts of df-structures issue 247.
> Dead plugins

- docs/changelog.txt
- plugins/deramp.cpp
> Add designation job check to deramp

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
> Add missing Unit::isDiplomat

- plugins/ruby/ruby-autogen-defs.rb
- plugins/ruby/ruby.rb
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/dfhack/dfhack).
> Apply fixes from CodeFactor

- docs/changelog.txt
- library/lua/gui/widgets.lua
Requires https://github.com/DFHack/scripts/pull/65 to keep adventure fort script working.
Fixes #1171
> Change gui.widgets.List:setChoices to keep state in internal table 

- docs/changelog.txt
- plugins/lua/workflow.lua
> Fix crafts advanced constraints in workflow

- docs/changelog.txt
- library/Core.cpp
- library/PlugLoad-posix.cpp
- library/PlugLoad-windows.cpp
- library/VersionInfoFactory.cpp
- library/include/PluginManager.h
- library/modules/Screen.cpp
Uses changes from https://github.com/DFHack/df-structures/pull/282
>  Support dlsym loading from libgraphics vtables

- docs/Compile.rst
- docs/Plugins.rst
- docs/changelog.txt
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/finder_ui.cpp
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/survey.cpp
Added scrolling of Finder search criteria, plus the new criterion of Frozen.
As expected, the changelog.txt update has to be handled manually.
> Embark assistant

- plugins/labormanager/labormanager.cpp
Add a number of tests to ensure that only assignable labors are assigned
to units, and that only units that are eligible to be assigned labors
are considered at all.
I borrowed logic from Dwarf Manipulator to identify units eligible to be
assigned labors.
This should prevent pets., ghosts, visitors, or any other noneligible
entities from being assigned labors by labormanager, and should thus fix
#1142.
> (labormanager) only assign valid labors (fix #1142)

- plugins/labormanager/labormanager.cpp
Units with values regarding NATURE will be preferenced or dispreferenced
for jobs which might give them a good/bad feeling because of that value
> (labormanager) respect NATURE value

- plugins/labormanager/labormanager.cpp
Also switching to case insensitive labor name matching.
> labormanager: add option to disable the management of a labor.

- .travis.yml
- travis/download-df.sh
- travis/get-df-version.sh
- travis/run-tests.py
This avoids issues with DFHack being (partially?) installed from an old build when the current build fails - possibly the cause of hangs in #1414.
buildmaster:skip-pr
> travis: Always clear DF folder

- .gitignore
- docs/Compile.rst
This basically does small improvements to the build and maintenance of the rep.
See individual commits for details.
> Improve readme, dependencies, and gitignore

- plugins/remotefortressreader/remotefortressreader.cpp
Only pull active units, not all of them.
> Smal RFR change

- plugins/createitem.cpp
These values are actually pretty difficult to determine, since they're iterated anyway for the check, we might as well collect them and output them when the user enters an invalid value.
> Output Castes on Error

- plugins/dwarfvet.cpp
naive fix, just to get rid of the log :)
> dwarfvet log only if enabled (fix #1504)

- docs/changelog.txt
- plugins/autogems.cpp
> autogems: check container content in linked stockpiles

- library/modules/Translation.cpp
> Fix issue #1528

- docs/Plugins.rst
- docs/changelog.txt
- plugins/getplants.cpp
The file contains a comment at the beginning trying to explain the logic used and the source of that logic.
> Added switches for farm seeds and plant counts

- plugins/labormanager/joblabormapper.cpp
- plugins/labormanager/labormanager.cpp
Add no-labor mappings for new jobs 241 through 243. This addresses #1561.
> Update joblabormapper.cpp for new jobs in 47.04

- plugins/labormanager/joblabormapper.cpp
Also clean up how paved roads are handled (the way it was was stupid)
fixes #1595 
WIP b/c not tested yet
> fix labor inferences for custom furnaces [labormanager,WIP]

- plugins/search.cpp
…so that item counts are updated correctly with other information.
> Switch trade screen search to use search_multicolumn_modifiable

- data/quickfort/aliases-common.txt
- dfhack-config/quickfort/aliases.txt
also do a quick editing pass on the existing alias documentation
> quickfort: document r+ -> r+& built-in alias

- docs/guides/quickfort-user-guide.rst
default dig
notes blueprints
buildingplan
> update quickfort docs

- plugins/zone.cpp
Small improvements for 'zone' plugin.
I have added enumnick command which create nick-s for creatures from given prefix and position on the list.
I have also changed maxage/minage so they accept float.
uinfo displays "slaughter" flag.
uinfo displays "Matched creatures" i.e number of creatures matched by filters at the end of the list.
> enumnick: command added to 'zone' plugin and other QoL improvements

- data/blueprints/library/dreamfort.csv
- docs/changelog.txt
This PR can be reviewed after #1682 is merged.
Add more dreamfort help in response to forum discussion: http://www.bay12forums.com/smf/index.php?topic=176889.msg8202032#msg8202032
> [quickfort] Add walkthroughs for each dreamfort level

- plugins/buildingplan.cpp
> [buildingplan] don't use cached iterators across map reloads

- LICENSE.rst
missed this when I was adding the libraries
> add libexpat, libzip, and xlsxio to LICENSE.rst

- plugins/raw/reaction_spatter.txt
The inconsistent [DOES_NOT_DETERMINE_PRODUCT_AMOUNT] distribution is right, I assume?
> Cover artifacts at greasing station

- docs/changelog.txt
- plugins/embark-assistant/defs.h
- plugins/embark-assistant/embark-assistant.cpp
- plugins/embark-assistant/help_ui.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/survey.cpp
The world tile level river size determination doesn't provide the complete picture as smaller rivers may join larger ones and rivers change size along their courses. Thus, river size determination has to be performed on the MLT level to be correct.
> Corrected river size handling

- docs/changelog.txt
- plugins/lua/workflow.lua
- test/main.lua
- test/plugins/workflow.lua
- test/test.lua
Fixes #1722 
(@calibhaan if you're able to double-check this fix before r4, that would be great)
> Fix workflow error related to milling jobs

- plugins/embark-assistant/matcher.cpp
- plugins/embark-assistant/survey.cpp
Don't think this small bug fix warrants another line in the change log, as there is already a bug fix one.
> corrected index usage

- plugins/embark-assistant/survey.cpp
As per discussion at http://www.bay12forums.com/smf/index.php?topic=169634.msg8224012#msg8224012.
> corrected mismatched indices

- data/blueprints/README.md
- docs/changelog.txt
- docs/guides/quickfort-library-guide.rst
- docs/guides/quickfort-user-guide.rst
no pictures yet, but just something to describe what is available in the blueprint library so it's more accessible. pictures will take more work -- v2 of this guide.
> high level docs for the quickfort blueprint library

- library/PlugLoad-windows.cpp
fix #1735
I wonder if I should use std::system_category instead of FormatMessage (not portable but DFHack is only compiled with MSVC), and rtrim instead of a custom algorithm (it requires the creation of a std::string but performance is not important here).
> Add an error message when LoadLibrary fails

- data/quickfort/aliases-common.txt
- docs/guides/quickfort-alias-guide.rst
depends on DFHack/scripts#241
changelog entry attached to that PR
> [quickfort] use and document new {Empty} quickfort keycode

- docs/guides/quickfort-user-guide.rst
documentation for DFHack/scripts#244
> [quickfort] documentation for #ignore blueprints

- data/blueprints/library/dreamfort.csv
- docs/changelog.txt
- add checklist for all required dreamfort commands
- give names to stockpiles, levers, bridges, and zones
- ensure diggers don't dig deeper than they need to using dig priorities
> [quickfort] Dreamfort blueprint improvements

- docs/changelog.txt
- library/modules/Buildings.cpp
Fixes #1758 
see linked bug for root cause analysis
> fix crash: avoid infinite parentage when linking rooms

- docs/changelog.txt
- plugins/search.cpp
> Fix crash in look menu search

- docs/changelog.txt
- plugins/seedwatch.cpp
should fix #682 =]
i've also removed the comment that states seedwatch doesn't work with linux. surprised it took over a decade to be removed!
[i don't really know how c++ works, so it's possible i got this wrong - please let me know if anything needs to be changed!]
> don't turn off seedwatch on map load

- docs/Plugins.rst
- docs/changelog.txt
- plugins/fortplan.cpp
step 2 in the #1644 deprecation plan
> [fortplan] add deprecation warnings to fortplan

- docs/guides/quickfort-alias-guide.rst
- docs/guides/quickfort-user-guide.rst
documentation for DFHack/scripts#257
> [quickfort] add documentation for #aliases blueprints

- data/blueprints/library/dreamfort.csv
- data/quickfort/aliases-common.txt
- docs/guides/quickfort-alias-guide.rst
since quantum stockpiling them dumps out their contents
last change before 0.47.05-r1. i swear.
> [dreamfort] separate sand bags into their own stockpile

- docs/changelog.txt
- plugins/strangemood.cpp
Adapts to changed enum value in df-structures.
Depends on DFHack/df-structures#422
> adapted to changed df-structures enum value names

- CMakeLists.txt
- docs/changelog.txt
DFHack/dfhack#1690
spiritual companion to DFHack/scripts#262
> [test] ensure test/scripts does not exist in dfhack repo

- test/main.lua
- travis/run-tests.py
introduce and use --resume option for ci
> [test] rerun all tests by default

- docs/Lua API.rst
- docs/changelog.txt
- plugins/lua/xlsxreader.lua
- plugins/xlsxreader.cpp
makes the API easier to use for Lua clients
this change also allows the API to limit the number of tokens returned from get_row
The new class API will be used in DFHack/scripts#263
> [xlsxreader] add Lua class wrappers

- ci/test.lua
so `dfhack.internal.scripts` isn't polluted with `IN_TEST` envs
this patches `dfhack.run_script`. there are other holes, though, like `dfhack.run_command`, `dfhack.enable_script` and, of course, `dfhack.run_script_with_env` itself. This minimal fix *might* be good enough for now, but a more robust solution would be to deprecate the global `internal.IN_TEST` and instead have the `IN_TEST` flag and the `scripts` table automatically inherited from parent environments. That way we wouldn't have to whack-a-mole patch all the entrypoints.
> [test] wrap dfhack.run_script for tests

- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
also refactor so we can get this data from `gui/blueprint`, plus a bit of code hygiene updating.
> [blueprint] report output filenames when creating blueprints

- docs/Plugins.rst
- plugins/plants.cpp
the `extirpate` and `immolate` commands were removed some time ago
> remove outdated info from plant plugin docs

- docs/changelog.txt
- library/lua/utils.lua
- test/library/utils.lua
I'm finding this function is useful across several scripts and could do with a common implementation.
> [Lua] add utils.normalizePath() function

- ci/test.lua
To support BeforeEach and AfterEach semantics (terminology taken from [JUnit](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods)). However, much of our code is scope-based (lambda-based?) so it seemed to make sense to use a single wrapper function instead of separate `before_each` and `after_each` functions.
We don't have much in the way of documentation for the test harness, so I added some explanatory text and an example to the code where we initialize the default config.
> [test] add support for custom test wrapper functions

- library/lua/gui/dwarfmode.lua
- test/library/gui/dwarfmode.lua
it's a top-level mode and should be supported.
> support view unit mode for guidm.enterSidebarMode

- library/lua/memscan.lua
> Fix out-of-bounds access in memscan.field_offset()

- docs/changelog.txt
- plugins/autofarm.cpp
Update autofarm to count PLANT_GROWTHS as well as PLANTS for threshold purposes. This resolves #1902.
Also addresses some pointer hygiene issues in autofarm.
> fix autofarm berry problem

- docs/changelog.txt
- plugins/tailor.cpp
Add support in tailor for user-specified material list. Also refactor, fix some mostly-innocuous bugs.
Resolves #1911.
> tailor: add support for user-specified material list

- data/blueprints/library/dreamfort.csv
- data/examples/init/onMapLoad_dreamfort.init
- docs/guides/quickfort-library-guide.rst
- add links to fully-built dreamfort on dffd
- add more explanatory comments in onMapLoad_dreamfort.init
> [dreamfort] doc updates

- data/blueprints/library/test/ecosystem/in/allbuildings-spec.csv
- docs/changelog.txt
- plugins/blueprint.cpp
that is, farm plots and paved/dirt roads.
missed this bit for milestone 3 of #1842
> [blueprint] support non-rectangular extent-based buildings

- docs/guides/quickfort-user-guide.rst
companion to DFHack/scripts#344
+@drummeur
> [quickfort] add documentation for quickfort single-tile tracks

- data/blueprints/library/test/ecosystem/golden/tracks-track.csv
- data/blueprints/library/test/ecosystem/in/tracks-track.csv
for more natural expression of the track blueprint.
> [quickfort] use goldens for quickfort track ecosystem test

- data/blueprints/library/dreamfort.csv
- docs/changelog.txt
- docs/guides/examples-guide.rst
Fixes #1998 
also:
- add in iron and flux indicators on the industry level
- fix out of date docs for professions
> [dreamfort] simplify blueprints with new quickfort features

- data/blueprints/library/aquifer_tap.csv
- docs/changelog.txt
- docs/guides/quickfort-library-guide.rst
blueprint, walkthrough guide, and blueprint library docs
> [blueprint library] light aquifer tap

- docs/changelog.txt
- library/modules/Job.cpp
> Job cancel update

- docs/changelog.txt
- library/lua/gui/materials.lua
Hopefully I'm not messing anything up this time.
Is the changelog entry alright?
>  Added (chain) for [CHAIN_METAL_TEXT] armours in library/gui/materials.lua used by the gui/create-item script-- again (oops)

- docs/Plugins.rst
Written in the GitHub online editor on my phone. It was painful (but but we painful as using the GitHub editorb on my phone for resolving merge conflicts).
> [blueprint] document new phases and options

- README.md
Adds discord badge, and updates IRC info.
> Updates chat in readme

- docs/Plugins.rst
I alphabetized things in distinct clear cut commits. First each section [separately] as they were in the file, then finally the order of sections.
edit: sorry they don't match +2,212 −2,218 it's hopefully whitespace O_O
> Alphabetizes Plugins.rst

- library/modules/EventManager.cpp
I implemented all the clang-tidy suggestions clion had for the file that could be implemented quick and easy.
> Clang-tidy suggestions for EventManager

- library/include/modules/Maps.h
- library/modules/Maps.cpp
The Maps module was missing int32_t signatures for certain functions, this adds the missing.
> Adds consistent interface signatures for Maps module

- docs/Lua API.rst
- docs/changelog.txt
- plugins/cxxrandom.cpp
- plugins/lua/cxxrandom.lua
- test/plugins/cxxrandom.lua
Fixes a mistake in the `bool_distribution` and adds a unit test
Resolves https://github.com/DFHack/dfhack/issues/2098
> Adds cxxrandom unit test and fixes interface problems

- data/examples/orders/basic.json
- docs/changelog.txt
- choose to make easy or lavish meals depending on how much food is already in stock
- remove unneeded material conditions on jugs and pots
> Update example manager orders

- depends/lua/src/lapi.c
> fix warning on windows about possible loss of data

- docs/Lua API.rst
- docs/changelog.txt
- library/lua/gui/widgets.lua
needed for the script refactoring that will take advantage of the new self-managing `EditField`s in #2137
> [lua] make key_sep more configurable

- docs/Removed.rst
#2081 
Partner to DFHack/scripts#384
> tombstone deteriorate*rb scripts

- ci/test.lua
- library/lua/test_util/mock.lua
- test/library/test_util/mock.lua
observe_func() is similar to func() but passes through all calls to a specified function.
Intended for use in https://github.com/DFHack/scripts/pull/385
> Add mock.observe_func(), improve mock.lua documentation

- library/lua/gui/widgets.lua
- test/library/gui/widgets.Label.lua
`update_scroll_inset` might change `frame_inset`, i.e. we need to `computeFrame` with the new values.
> fix wrong `Label.frame_body.x2` value

- data/blueprints/library/aquifer_tap.csv
- data/blueprints/library/pump_stack.csv
- docs/guides/quickfort-library-guide.rst
promote usage of `gui/quickfort` and update text/links
> Update blueprint library docs

- .github/workflows/build.yml
> key the DF cache on the hash of download-df.sh

- data/blueprints/library/test/ecosystem/in/gui_quantum-spec.csv
- test/quickfort/ecosystem.lua
the current naming is more confusing than it needs to be. see #2175
> make the extra_fns functionality clearer

- plugins/debug.cpp
- plugins/embark-assistant/matcher.cpp
- plugins/prospector.cpp
- plugins/stockpiles/StockpileUtils.h
- plugins/uicommon.h
I was having issues building on gcc12, and gcc11 (11.3) as it turned out. These are the modifications I used to obtain a complete build.
> GCC12 build fixes

- docs/Authors.rst
As suggested in: https://github.com/DFHack/scripts/pull/404#issuecomment-1152780958
> Add myself to Authors.rst

- plugins/orders.cpp
This was detected by gcc and causing the build to fail on my
Linux machine
> Fix use after free's

- docs/changelog.txt
- library/lua/gui/materials.lua
Now the dialog not just shows the traits, but also actually changes them out of the box.
> Add default selection handler to `materials.ItemTraitsDialog`

- plugins/building-hacks.cpp
- plugins/orders.cpp
Requires dfhack/df-structures#465.
This also pulls in dfhack/scripts#407, for which there was no corresponding submodule update.
> The great de-anon-ification

- conf.py
- docs/Tools.rst
- docs/tools/cromulate.rst
- index.rst
#2228 
Add sample tool documentation in proposed format.
@lethosor feel free to modify, I was just adding something to start with. I'm going to start basing the help ingestion logic on the text rendering of the sample help doc.
Items I was hoping you could help with:
- Generate a TOC in Tools.rst that includes the tags and the first sentence from each doc page
- Generate a page that indexes the tools by tag
- Generate a footer for each tool page that links to other tools with the same tags
> Myk sample command help

- docs/Builtin.rst
- docs/Core.rst
- index.rst
- library/lua/helpdb.lua
#2228 
implement list API for the `ls` builtin to call
also significantly clean up and document helpdb code
> Support builtin commands in helpdb

- library/Core.cpp
- library/lua/dfhack.lua
- library/lua/helpdb.lua
#2228
and also the new built-in "tags" command
> Use helpdb to implement help and ls built-in commands and dfhack.script_help()

- docs/changelog.txt
- library/Core.cpp
- library/LuaTools.cpp
- plugins/liquids.cpp
- plugins/tiletypes.cpp
To follow up on DFHack/scripts#417
> Move .history files to dfhack-config

- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/LuaTools.h
- library/lua/helpdb.lua
- test/library/helpdb.lua
#2224 Merge the helpdb logic into develop
of course it's not going to serve the highest quality data without also merging the doc updates from the docs branch, but it's a chunk that can be reviewed, tested, and merged separately, so we should do so. Moreover, it does work perfectly fine with existing in-cpp plugin docs and in-lua/rb script docs since it supports the legacy formats.
> add helpdb and associated Lua API

- data/init/dfhack.keybindings.init
Adds default keybindings for gui/launcher
Depends on DFHack/scripts#413
> Add keybindings for gui/launcher

- data/blueprints/library/dreamfort.csv
- docs/changelog.txt
direct dwarves to the grand hall for food selection and eating. otherwise they tend to steal raw ingredients and eat in the manager's office : p
> [dreamfort] add traffic designations for better dining behavior

- docs/Removed.rst
> Add removed scripts to the graveyard

- docs/sphinx_extensions/dfhack/tool_docs.py
The resulting index looks the same as the one we prototyped, which is both good and bad. Everything is there, but the links are anchored to the summaries, not the tool names.
Depends on #2294 and #2295
> [docs] create genindex entries for all tools and commands

- library/lua/helpdb.lua
- test/library/helpdb.lua
easter egg suggested by thurin : )
> [helpdb] replace die's underline with tombstones

- .readthedocs.yml
since we no longer appear to be building docs for scripts : /
> ensure readthedocs checks out submodules

- docs/changelog.txt
- library/modules/Units.cpp
Per Doublestrafe's suggestion on Discord
> `Units::teleport()`: set idle_area

- docs/plugins/3dveins.rst
- docs/plugins/add-spatter.rst
- docs/plugins/autohauler.rst
- docs/plugins/autolabor.rst
- docs/plugins/autonestbox.rst
Fixes #2288 (along with DFHack/scripts#444)
> address feedback on the docs

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/dig.cpp
> [digtype] optionally process only the cur z-level and below

- docs/changelog.txt
- docs/plugins/blueprint.rst
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/quickfort/ecosystem.lua
#1842
- record stockpile/building/zone names
- record accurate room sizes
> [blueprint] split rooms phase from query

- docs/changelog.txt
- docs/plugins/blueprint.rst
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- test/plugins/blueprint.lua
- test/quickfort/ecosystem.lua
#1842
generate meta blueprints where beneficial to reduce the number of blueprints the player has to apply
> [blueprint] generate meta blueprints

- docs/Lua API.rst
- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Constructions.h
- library/modules/Constructions.cpp
> Implement/change/expose to Lua constructions findAtTile & insert

- library/Core.cpp
I added this to debug a thorny issue with hotkey guards. no need to let the instrumentation go to waste! the debug framework has near-zero performance impact for unprinted log lines.
> instrument core keybinding resolution

- docs/changelog.txt
- library/include/MiscUtils.h
- plugins/autochop.cpp
> [MiscUtils] add string_to_int

- data/orders/basic.json
- docs/changelog.txt
- docs/plugins/orders.rst
> [orders] replace shell crafts with shleggings

- CMakeLists.txt
- docs/changelog.txt
> Merge robots.txt change from master to develop

- docs/changelog.txt
- docs/plugins/spectate.rst
- plugins/spectate/spectate.cpp
Adds a status message on map load if the plugin is enabled.
edit:
I haven't added a change log entry since the persistent info is new to this release.
> Updates spectate plugin

- docs/changelog.txt
- plugins/autolabor/joblabormapper.cpp
> correct QUERN construct labor

- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/fastdwarf.cpp
Implements #2244 
Haven't made a changelog or documented anything yet because I don't know if this is going to be the final form of the API, but I did remember changelog this time haha. Unless you would have wanted me to changelog it from the get-go?
Anyway the code stuff is not yet finished either, I'm just putting it up as a PR so we can discuss better.
> Action timer API

- plugins/autolabor/CMakeLists.txt
- plugins/autolabor/autolabor.cpp
sorry missed this one in #2451
> make autolabor less chatty

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- library/lua/utils.lua
if they are functions instead of booleans, run them to get a dynamic boolean value.
> [gui.View] give visible and active attributes the ability to have dynamic values

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
> update overlay dev guide with troubleshooting tips and dev workflows

- docs/changelog.txt
- docs/plugins/workflow.rst
- plugins/workflow.cpp
since old saves are no longer compatible, and the old bug cannot affect future saves.
> remove obsolete fix-job-postings command

- docs/dev/Compile.rst
for doing windows dev until the Linux version is out
> Add docs for building a cross-compiling linux env

- docs/changelog.txt
- docs/dev/Dev-intro.rst
> add arch diagrams to the dev guide

- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
matches DF's style and behavior in both graphics and non-graphics modes.
> skin our scrollbars to look and hover like DF's

- dfhack-config/scripts/README.md
- docs/Core.rst
- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
- library/Core.cpp
and update lots of docs referring to the script paths
Fixes #2502
> add dfhack-config/scripts to default script paths

- library/Core.cpp
- library/PlugLoad-windows.cpp
- library/modules/Burrows.cpp
- library/modules/Gui.cpp
- library/modules/Items.cpp
more fields have disapperated
@RosaryMala If you have work for this already prepped, we can merge yours and I can revert this one.
> prep for Quietust's structure updates

- docs/plugins/autobutcher.rst
- plugins/CMakeLists.txt
- plugins/autobutcher.cpp
just need a little adjustment to how it identifies zoos
> update autobutcher to work with v50

- library/include/DataIdentity.h
Cherry-pick of https://github.com/DFHack/dfhack/pull/2532 minus Ruby
Required by https://github.com/DFHack/df-structures/pull/502
Core still compiles locally with this change
> [v50] Add read-only container_identity for std::map

- .gitignore
- LICENSE.rst
- docs/dev/Contributing.rst
- docs/dev/Dev-intro.rst
- docs/dev/Documentation.rst
- docs/dev/Memory-research.rst
- docs/dev/building/Compile.rst
- docs/dev/building/Dependencies.rst
- docs/dev/building/Options.rst
- docs/dev/building/index.rst
- docs/dev/index.rst
This is a stab at organizing the information we throw at new devs into new files.
edit: the commits are not staying
> [WIP] Build docs

- .gitignore
- LICENSE.rst
- docs/dev/Contributing.rst
- docs/dev/Dev-intro.rst
- docs/dev/Documentation.rst
- docs/dev/Memory-research.rst
- docs/dev/building/Compile.rst
- docs/dev/building/Dependencies.rst
- docs/dev/building/Options.rst
- docs/dev/building/index.rst
- docs/dev/index.rst
This is built on top of #2517 .
> Update the Windows build documentation for VS 2022

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
and use the option to render `On` in green for ToggleHotkeyLabel
> allow color options for CycleHotkeyLabel

- library/Core.cpp
- library/modules/Persistence.cpp
> fix persistence

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
for directly setting the option by value or by index
> add CycleHotkeyLabel:setOption()

- library/lua/gui.lua
- library/modules/Gui.cpp
just implemented for the main view sheet, but it's enough to get started with
> get rudimentary getAny(Unit|Item|Building) working

- data/dfhack-config/init/examples/README.md
- data/dfhack-config/init/examples/onMapLoad_dreamfort.init
- docs/guides/examples-guide.rst
addresses https://github.com/DFHack/dfhack/pull/2554#discussion_r1062904076
> fix example init file and related doc

- library/modules/Screen.cpp
> fix a crash in Screen when read or paint tile indices are negative

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Screen.h
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- library/modules/Screen.cpp
also allow tiles to have an associated width in Label rendering
> support foreground and background writing from pens

- docs/dev/Lua API.rst
- library/lua/gui/dwarfmode.lua
- library/lua/gui/widgets.lua
- modify the "movement key" check so that it also picks up drag and zoom
- modify renderMapOverlay so that it renders pens, not raw characters
> pull the useful bits out of guidm.MenuOverlay and make them available

- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
this will be required by the updated `gui/quickfort`
> give more control over the resizing dimensions of ResizingPanels

- plugins/remotefortressreader/building_reader.cpp
This is the corresponding PR to fix fortressreader for this structures update https://github.com/DFHack/df-structures/pull/520
> Update fortress reader for structures change

- docs/Quickstart.rst
- docs/changelog.txt
- index.rst
for reading online or via `dfhack-quickstart-guide` (DFHack/scripts#529)
> add quickstart help

- library/lua/gui/widgets.lua
> keep windows on the screen when the DF window is resized

- docs/changelog.txt
- docs/plugins/orders.rst
- plugins/orders.cpp
> restore orders library functionality

- docs/about/Removed.rst
> tombstone create-items

- docs/changelog.txt
- plugins/tailor.cpp
also improved debugging messages
> tailor: add support for using undyed cloth

- data/orders/basic.json
- data/orders/furnace.json
Bags now have their own item type, they're no longer mixed in with boxes
> Update orders related to bags for v50.x

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/Core.cpp
- library/lua/helpdb.lua
this greatly speeds up the launch time of `gui/launcher`
> move helpdb from autorefresh to explicit refresh

- library/Core.cpp
- library/lua/script-manager.lua
so they display nicely in gui/launcher
> don't use tabs in enable output

- docs/Quickstart.rst
- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- plugins/lua/hotkeys.lua
#2666
focus string passthrough isn't done yet, but click to unfocus is, and that's a big chunk of the work
> Implement new ZScreen semantics

- plugins/channel-safely/channel-groups.cpp
> fix build errors with channel-safely

- docs/about/Removed.rst
As per: https://github.com/DFHack/scripts/pull/562#issuecomment-1405838879
> Add show-unit-syndromes to removed scripts

- build/build-win64-from-linux.sh
I think this affects basically nobody but me since everyone else seems to run docker rootless.
> cross-compile-script: Fix permissions in ccache dir for sudo users

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
- plugins/tiletypes.cpp
for fixing dirt roads for #2614
> Expose tiletype setting from the tiletypes plugin to lua

- docs/changelog.txt
- library/lua/gui.lua
- library/lua/gui/widgets.lua
> only mark the border corner as resizable if the window is resizable

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
> make initial pause configurable for DFHack windows

- docs/changelog.txt
- plugins/nestboxes.cpp
convert top level structure to the now-common pattern of persisting state and running periodically
> [nestboxes] update and simplify; persist state

- docs/changelog.txt
- plugins/lua/seedwatch.lua
> [seedwatch] fix parameter parsing when setting targets

- library/lua/gui/widgets.lua
this seems to fix this "issue" i filed here: https://github.com/DFHack/dfhack/issues/2777
here's how it looks
https://i.imgur.com/aFnq80M.mp4
if you tried to do this before merging this pr (using the texture provided in #2777), you'll see that the textures dont act like in the video.
(i hope i am doing this pr correctly ;_;)
> wrong scrollbar sprites mapping fix (issue #2777)

- plugins/automelt.cpp
- plugins/lua/automelt.lua
related to #2796 but does not fix yet
> [automelt] clean up code and protect against NULLs and invalid stockpiles

- plugins/autochop.cpp
- plugins/autoslab.cpp
- plugins/examples/persistent_per_save_example.cpp
- plugins/nestboxes.cpp
- plugins/seedwatch.cpp
updated:
- autochop
- autoslab
- nestboxes
- seedwatch
> update auto plugin example, use new best practices

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/autolabor.lua
- plugins/lua/orders.lua
- plugins/lua/overlay.lua
and migrate existing widgets to use them
> support focus paths for overlay widgets

- data/init/dfhack.keybindings.init
- docs/changelog.txt
- plugins/autodump.cpp
and reinstate autodump-destroy-item
> set up some keybindings that are ready to go

- docs/dev/Lua API.rst
- library/include/modules/Gui.h
- library/modules/Gui.cpp
- plugins/confirm.cpp
and clean up focus string matching logic
> implement some Gui module hotkey guards

- docs/changelog.txt
- library/Core.cpp
Include manual saves when detecting when to write persisted data
> Detect manual save when persisting data

- docs/changelog.txt
- plugins/confirm.cpp
Load confirm config from dfhack-config/confirm.json. Sister scripts PR: https://github.com/DFHack/scripts/pull/617
Closes #2815
> Persist confirm config

- plugins/autolabor/autolabor.cpp
> Fix for Autolabor spamming issue #2864

- docs/changelog.txt
- docs/plugins/tailor.rst
- plugins/lua/tailor.lua
- plugins/tailor.cpp
this adds a test for an unmapped clothing size which will at least stop the making of toad-sized clothing -see #2916. a diagnostic is issued when this happens as it is a bug
> tailor: try to squash toad clothing bug

- docs/about/Removed.rst
Needs: https://github.com/DFHack/scripts/pull/618
> tombstone combine-drinks and combine-plants

- docs/changelog.txt
- plugins/dig-now.cpp
This is a work in progress for dealing with some of the reported issues of dig-now.
PR opened for the artifacts in order to test the changes.
Testing:
- buffered designations implementation resolves #2720
- scans jobs for supported designations
- looks for valid dig-now positions in the supported jobs
- cancels valid & supported jobs
- buffers the designation info
- should resolve #2471
> dig-now bug fixing

- docs/changelog.txt
- plugins/autobutcher.cpp
Fixes #2881
Unless someone has a better idea?
> [autobutcher] log to console instead of announcements

- docs/changelog.txt
- plugins/dig-now.cpp
reverts #2908
(this is a manual revert since related files have changed since the PR and it can no longer do it automatically)
reopens #2720 and #2471
> revert recent changes to dig-now due to lockups

- library/Core.cpp
- library/include/MiscUtils.h
since we use an ostringstream, there are other types that can be joined by this method
note the existing specialized method still remains since I could not get things to link otherwise.
> [MiscUtils] add templated version of join_strings

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
for dynamic resolution of displayed tiles
> [Label] allow token.tile to be a function

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
> pipe dfhack.job.attachJobItem through to Lua

- plugins/lua/buildingplan.lua
#2883 
- allow constructions to be placed even if some tiles are invalid
> [buildingplan] next steps

- docs/plugins/buildingplan.rst
- docs/plugins/overlay.rst
- library/LuaTools.cpp
- library/include/LuaTools.h
- library/include/modules/Materials.h
- library/modules/Materials.cpp
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/defaultitemfilters.cpp
- plugins/buildingplan/itemfilter.cpp
- plugins/buildingplan/itemfilter.h
- plugins/buildingplan/plannedbuilding.cpp
- plugins/lua/buildingplan.lua
#2883 
- init building materials to "ordinary" max quality
> [buildingplan] v1 features code complete

- docs/changelog.txt
- plugins/dig-now.cpp
Reverts #2944 so we can revisit in #2980
> Revert "revert recent changes to dig-now due to lockups"

- .github/workflows/build.yml
since ubuntu-18.04 is apparently becoming verboten
> update all build envs to ubuntu-22.04

- .github/workflows/steam.yml
Fixes #2428
first test
secrets have been added to the dfhack repo
> add steam deploy workflow

- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/buildingplan_cycle.cpp
also prep for the UI refresh and return the heat safety rating along with the material counts
> [buildingplan] filter displayed materials if building heat safety is set

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/buildingplan/defaultitemfilters.cpp
- plugins/buildingplan/defaultitemfilters.h
- plugins/buildingplan/plannedbuilding.cpp
- plugins/buildingplan/plannedbuilding.h
- plugins/lua/buildingplan/filterselection.lua
- plugins/lua/buildingplan/planneroverlay.lua
this actually adds an entirely new "specials" filter system that can be extended later for other types
> [buildingplan] filter by whether a slab is engraved

- docs/changelog.txt
- docs/plugins/buildingplan.rst
- plugins/lua/buildingplan/itemselection.lua
> [buildingplan] rename Build button to Confirm and update docs

- plugins/lua/buildingplan/planneroverlay.lua
> [buildingplan] allow inputs to pass through when minimized

- docs/changelog.txt
- docs/plugins/orders.rst
- plugins/lua/orders.lua
> add minimize button to orders overlay panel

- docs/changelog.txt
- plugins/tailor.cpp
properly track materials required for already-queued jobs
fixes #3056
> tailor: fix material overrun issue

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
no more building 100+ tile bridges. it'll crash the game anyway.
fixes #3060
> [buildingplan] respect max building size

- docs/changelog.txt
- library/modules/Buildings.cpp
> mark tiles with magma or deep water as "not free"

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/buildingplan/plannedbuilding.cpp
- plugins/lua/buildingplan/planneroverlay.lua
that is, ignore the global and building-specific filters
Fixes #3061
> [buildingplan] allow player to choose any item when choosing items manually

- plugins/lua/tailor.lua
- plugins/tailor.cpp
enable with "tailor debugging on" disable with "tailor debugging off"
this setting is not persisted
> tailor: add inventory sanity check debug mode

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
> support showing a different tile on hover for Labels

- depends/lua/src/ldo.c
to protect against malware attacks
Fixes #3070
> remove lua's ability to load binary chunks

- docs/changelog.txt
- docs/plugins/confirm.rst
- plugins/lua/confirm.lua
> [confirm] add check for removing burrows via the repaint menu

- plugins/buildingplan/buildingplan.cpp
> fix items not being filtered correctly in item selection screen

- docs/changelog.txt
- docs/guides/modding-guide.rst
- library/Core.cpp
- library/LuaApi.cpp
- library/lua/script-manager.lua
> give active mods a chance to reattach their hooks

- plugins/prospector.cpp
this is arguably a better approach for dealing with the change in elevation display in v50
> prospector redux

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
> [buildingplan] hide planner overlay during the tutorial

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/lua/buildingplan/filterselection.lua
> [buildingplan] add ability to filter by cloth and silk

- library/modules/MapCache.cpp
- library/modules/Maps.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
the other half of DFHack/df-structures#591
> adjust to tree root changes

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
> [buildingplan] don't reset planner panel minimized state

- data/init/dfhack.keybindings.init
- data/init/dfhack.tools.init
- docs/changelog.txt
> add alias and keybinding for toggling the keyboard cursor

- docs/about/Authors.rst
from scanning the git commit logs in dfhack, scripts. and structures
Fixes #3237
> update new authors from 01 Feb 2023 - 15 Apr 2023

- docs/changelog.txt
- library/Core.cpp
- library/lua/dfhack.lua
> infrastructure for hiding the terminal console on startup

- docs/changelog.txt
- plugins/lua/autolabor.lua
> add a warning when DT appears to be running

- data/dfhack-config/buildingplan.json
- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
and minimized state is now persisted across reloads
Fixes #3276
> planner panel is minimized by default

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/lua/buildingplan/filterselection.lua
fixes https://github.com/DFHack/dfhack/issues/3251#issuecomment-1518139164
> [buildingplan] allow filtering by yarn

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
> [buidlingplan] fixed size limit calculations for rollers

- data/init/dfhack.tools.init
- docs/changelog.txt
> add "version" alias to run the help

- docs/changelog.txt
- plugins/dig-now.cpp
> [dig-now] fix smoothing job detection

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
> add ZScreenModal class for modal dialogs

- .github/workflows/steam.yml
- package/windows/CMakeLists.txt
improve cmake handling for downloading the sdk
set up GHA to cache the SDK download
> steam build workflow improvements

- docs/changelog.txt
- plugins/lua/autolabor.lua
Also fixes missing frame
Fixes #3365
> [autolabor] fix warning appearing on inappropriate screens

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
- plugins/overlay.cpp
> [overlay] rename overlay.reload to overlay.rescan

- docs/changelog.txt
- library/RemoteClient.cpp
- library/RemoteServer.cpp
> [RemoteServer] fix crash on malformed json

- plugins/autolabor/autolabor.cpp
adapt to DFHack/df-structures#599
> [autolabor] adjust usage to game structure reunification

- data/init/dfhack.keybindings.init
- docs/changelog.txt
depends on DFHack/scripts#705
#3316
> add keybinding for gui/autodump

- docs/changelog.txt
- plugins/blueprint.cpp
- plugins/lua/blueprint.lua
- plugins/lua/stockpiles.lua
> [blueprint] support recording stockpiles in blueprints

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
also fix an out-of-date default value in the docs
> allow dragging by frame edge for non-resizable windows

- docs/dev/Lua API.rst
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
now restricted to civzones since buildings can no longer have owners
> reinstated Buildings.setOwner

- docs/changelog.txt
- library/modules/DFSteam.cpp
Fixes #3452
edit: fix has been independently verified.
> only initialize steam if launched from steam

- plugins/lua/overlay.lua
> extend the title version widget to show longer version strings

- docs/about/Removed.rst
> Retire gui/automelt

- data/blueprints/aquifer_tap.csv
- data/blueprints/dreamfort.csv
- data/blueprints/pump_stack.csv
- docs/changelog.txt
more detailed walkthroughs, updated pump_stack so there is a boulder-clearing step (they can otherwise get in the way of building the pumps)
> [blueprint library] update pump_stack and aquifer_tap

- plugins/faststart.cpp
> re-enable faststart now that the DF race condition has been fixed

- docs/changelog.txt
- library/modules/Gui.cpp
- plugins/lua/orders.lua
needed a little more fine-grained focus stringing in the Gui module
> [orders] don't display overlay on subscreens

- docs/changelog.txt
- plugins/dig-now.cpp
> [dig-now] handle obsidian

- docs/guides/quickfort-library-guide.rst
> [blueprint library guide] fix internal link to screenhot header

- library/modules/Gui.cpp
> [Gui] differentiate trade request screen from other diplomacy screens

- CMakeLists.txt
microsoft released 17.6 in may
appears to work with our current codebase as well as the prior versions, should be safe to use
> include vs17.6 in acceptable version range

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/lua/gui/widgets.lua
- library/modules/Gui.cpp
- library/modules/Items.cpp
- plugins/logistics.cpp
just little bits needed for other trade screen work
> widget and focus string enhancements

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
adjust prices according to race WAR affinity
depends on #3481 for c++-17-isms
> fix item prices and algorithm

- docs/changelog.txt
- plugins/3dveins.cpp
- plugins/CMakeLists.txt
3dveins mostly works for 50x. it has trouble with the new HFS gem-studded columns and will occasionally delete some of the gems in them, but typically not all that many of them, and it's my opinion that the impact of this is at most minimal.
in order for this to work, however, i had to make the inability to place an inclusion not a fatal error, and so that's the one change
> reenable 3dveins

- library/Core.cpp
- library/include/MiscUtils.h
- library/modules/Graphic.cpp
- library/modules/Materials.cpp
- plugins/autofarm.cpp
- plugins/tailor.cpp
> replace `dts:make_unique` with `std::make_unique`

- docs/changelog.txt
- docs/plugins/misery.rst
- plugins/misery.cpp
> [misery] realign the docs to the actual implementation

- .github/workflows/steam.yml
since v2 apparently no longer works
> update steam-deploy to v3

- CMakeLists.txt
- plugins/remotefortressreader/CMakeLists.txt
> remove unneeded linkage to SDL

- docs/guides/modding-guide.rst
- library/lua/script-manager.lua
> infrastructure for mod-added file libraries

- docs/changelog.txt
- plugins/logistics.cpp
- plugins/lua/logistics.lua
> [logistics] don't crash

- plugins/devel/check-structures-sanity/dispatch.cpp
Seems to catch a number of true positives and no false positives on Linux now
> check-structures-sanity: update detection for GCC C++11 std::string

- library/CMakeLists.txt
- library/DataIdentity.cpp
- library/DataStaticsFields.cpp
- library/include/DataDefs.h
- library/include/DataIdentity.h
- library/include/DataStaticsFields.inc
- library/modules/Screen.cpp
Requires https://github.com/DFHack/df-structures/pull/622
Needed to fix enabler on Linux (#3427)
> DataIdentity support for new types (std::mutex, std::condition_variable)

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- .github/workflows/github-release.yml
- .github/workflows/lint.yml
- .github/workflows/steam-deploy.yml
- .github/workflows/test.yml
specifically, the `test` and `lint` jobs. this will allow us to build, lint, and test from scripts and structures repos
> make jobs reusable for other repos

- ci/test.lua
- library/lua/gui/widgets.lua
- library/lua/helpdb.lua
- test/core.lua
- test/encoding.lua
- test/gui.lua
- test/library/argparse.lua
- test/library/gui.lua
- test/library/gui/dialogs.lua
- test/library/gui/widgets.EditField.lua
- test/library/gui/widgets.Label.lua
- test/library/gui/widgets.Scrollbar.lua
- test/library/gui/widgets.lua
- test/library/helpdb.lua
- test/library/misc.lua
- test/library/print.lua
- test/library/string.lua
- test/library/test_util/expect_unit.lua
- test/library/test_util/mock.lua
- test/library/utils.lua
- test/structures/find.lua
- test/structures/misc.lua
- test/structures/other_vectors.lua
- test/structures/primitive_refs.lua
- test/structures/ref_target.lua
- test/structures/types_meta.lua
- test/structures/unions.lua
- test/test.lua
> re-enable unit tests

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/steam-deploy.yml
- .github/workflows/test.yml
> make the workflows repository agnostic

- docs/changelog.txt
- docs/sphinx_extensions/dfhack/changelog.py
and mark unused headers as deprecated
> add changelog template for new versions

- .github/workflows/test.yml
- ci/run-tests.py
> do a test run with blank init scripts

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/include/modules/Items.h
- library/modules/Items.cpp
the identity of the selling party doesn't actually affect the value!
#3643
> remove caravan_buying param from getValue call

- library/lua/gui/widgets.lua
no changelog since obviously nobody has tried this before
> [widgets.Panel] correctly fire on_resize_end events

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
so they are easy to work with in subclasses
> add functions to Panel in addition to attributes

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/MiscUtils.cpp
- library/include/MiscUtils.h
- library/lua/memscan.lua
Intended to be used by global and vtable scans
> Memory scan helpers

- docs/changelog.txt
- docs/sphinx_extensions/dfhack/changelog.py
> add New Tools as a valid changelog header

- docs/changelog.txt
- plugins/lua/zone.lua
> [caravan] unit assignment screens for cages, restraints, and pits/ponds

- docs/changelog.txt
- library/LuaApi.cpp
- library/modules/Screen.cpp
- test/library/gui.lua
new tile properties weren't all being detected, and none of them were making it back to lua
> [Screen] detect extended tile properties and communicate them back to lua

- docs/changelog.txt
- library/modules/Gui.cpp
where it's not useful and is just in the way
> [orders] prevent overlay from appearing on the new workorder page

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- plugins/lua/zone.lua
> add small animal support to animal assignment screens

- library/modules/Gui.cpp
Are these worth making enums for?
Fixes #3675
> higher granularity for unit viewsheet focus strings

- docs/changelog.txt
- plugins/lua/zone.lua
not sure why I didn't think of this earlier.. all the data is right there
> [zone] offer sort by race on animal assignment screen

- ci/test.lua
initial_prep takes longer than our timeout for initial load
> fix tests sometimes timing out in ci

- ci/test.lua
ref: https://github.com/DFHack/dfhack/pull/3689#discussion_r1300535669
> [test] limit wait for title screen in wall clock time

- docs/changelog.txt
- library/modules/Items.cpp
> add in value for units contained in cages

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- data/blueprints/dreamfort.csv
and allow the cache to expand past the persisted max size during the build
Fixes #3514 just because I needed an innocuous change to test the rebuild speed
> zero ccache stats between runs

- docs/plugins/logistics.rst
- docs/plugins/stockpiles.rst
> [stockpiles] document stockpiles/logistics overlay

- library/Core.cpp
> clarify error message about the terminal

- docs/changelog.txt
- library/modules/Items.cpp
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/lua/buildingplan/planneroverlay.lua
Notably, it's perfectly fine to build a dyer's shop with a water bucket as long as it doesn't have milk or lye in it.
Fixes #3725
> [buildingplan] handle empty and lye_milk_free flags

- library/modules/Gui.cpp
in support of DFHack/scripts#799
> [Gui] add focus string details for orders context

- docs/changelog.txt
- plugins/createitem.cpp
nothing special here; just adding the new BAG enum value as a valid target
Fixes #3733
> [createitem] support creating items inside of bags

- docs/plugins/strangemood.rst
Updated example to accurately reflect arguments. Compliant with getopt-style parameter syntax.
> Update strangemood.rst example section

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
needed for new squad sort panel changes
> [overlay] allow widgets to bump their version and reset their saved settings

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort.lua
adds a "ratings" overlay that shows the values used for sorting for the currently visible units
many of the sort metrics had to be turned into 2-3 digit "ratings" by guessing at some thresholds for coloring the "good", "medium", and "bad" values. @Halifay - I was hoping you'd have some thoughts on the numbers I chose
> [sort] squad screen v2

- docs/Installing.rst
- docs/changelog.txt
so https://github.com/DFHack/dfhack.org/pull/3 can link to it
> add instructions for downloading dev builds

- docs/about/Authors.rst
- docs/changelog.txt
- package/linux/dfhack
that is needed for Steam overlay and game streaming to work
fixes https://github.com/DFHack/dfhack/issues/3768
> linux: preserve existing LD_PRELOAD content

- docs/changelog.txt
- plugins/lua/sort.lua
Removed redundant uppercase in mental stability formula. Reworked thresholds for combat skill effectiveness formulas to have a higher 100 cap (more descriptive about very strong warriors).
> Combat ratings polishing

- library/modules/Gui.cpp
in preparation for the `startdwarf` overlay for #3789
> add detailed focus strings for setupdwarfgame

- docs/changelog.txt
- library/modules/Translation.cpp
- plugins/autoslab.cpp
> protect against bad values in TranslateName

- library/lua/gui.lua
Meant to include this with ##3841
> restore mouse state after sending input to parent

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
set to 0 for an immediate burst of high frequency calls
in support of #3849
> [overlay] support dynamic onupdate frequency adjustments

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- library/lua/utils.lua
- plugins/lua/buildingplan/itemselection.lua
> refactor text search routine out into utils fn

- docs/changelog.txt
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
jobs, work details, interrogations, and convictions
> [sort] add support for more info screens

- docs/changelog.txt
- plugins/lua/sort.lua
since the help is especially useful in figuring out when and why to use the various sorts.
> [sort] add help button to squad panel

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Units.cpp
> [zone] label war and hunt trained animals in readable names

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
- plugins/lua/sort/locationselector.lua
- plugins/lua/sort/sortoverlay.lua
and refactor existing code for better architecture and code sharing
> [sort] add support for location selector screen

- docs/changelog.txt
- docs/plugins/sort.rst
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
- plugins/lua/sort/sortoverlay.lua
- plugins/lua/sort/world.lua
depends on https://github.com/DFHack/df-structures/pull/670
> [sort] support searching for world artifacts

- docs/plugins/sort.rst
- plugins/lua/sort/locationselector.lua
e.g. "wealth" or "lies"
suggested on reddit: https://www.reddit.com/r/dwarffortress/comments/176gtrc/comment/k4q16cj/?utm_source=share&utm_medium=web2x&context=3
> [sort] support searching for spheres on the religion selector

- docs/changelog.txt
- docs/plugins/sort.rst
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
search by name, profession, or (novice or greater) skill
> [sort] search support for candidates screen

- plugins/lua/sort.lua
- plugins/lua/sort/unitselector.lua
> [sort] better panel alignment on small screen sizes

- docs/changelog.txt
- library/modules/Units.cpp
e.g. "troglodyte baby" instead of ""
> [zone] use generic baby/child names when race doesn't have something specific

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort.lua
- plugins/lua/sort/slab.lua
- plugins/lua/sort/sortoverlay.lua
can filter for units that need a slab to prevent rising as a ghost
> [sort] add search and filter for slab engraving list

- docs/changelog.txt
- plugins/buildingplan/buildingplan_cycle.cpp
- plugins/lua/buildingplan/planneroverlay.lua
Fixes https://github.com/DFHack/dfhack/issues/3693
> [buildingplan] filter cages by whether they are occupied

- docs/changelog.txt
- plugins/lua/sort.lua
Fixes https://github.com/DFHack/dfhack/issues/3786
> [sort] don't count mercenaries as appointed officials

- library/lua/gui.lua
so they should swallow all input
ref: https://github.com/DFHack/dfhack/pull/3841
> [gui] framed screen subclasses are modal

- docs/changelog.txt
- library/modules/Translation.cpp
> Revert "use df's translate_name function if available"

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/lua/buildingplan/planneroverlay.lua
Fixes https://github.com/DFHack/dfhack/issues/3469
> [buildingplan] show how many items you need to make when planning

- data/blueprints/dreamfort.csv
- add note about possibly delaying pasturing initial animals
- add display furniture to guildhall level rooms
- add wheelbarrows to caged unit stockpile
Fixes https://github.com/DFHack/dfhack/issues/3788
> [dreamfort] minor updates

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/plugins/buildingplan.rst
- library/lua/gui/widgets.lua
- plugins/lua/buildingplan/planneroverlay.lua
- plugins/lua/orders.lua
- plugins/lua/sort.lua
- plugins/lua/stockpiles.lua
and use them across the overlays that need them
> add standard HelpButton and ConfigureButton classes

- docs/changelog.txt
- plugins/tailor.cpp
Fixes https://github.com/DFHack/dfhack/issues/3598
> [tailor] reuse existing orders if possible

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Maps.h
- library/modules/Maps.cpp
- plugins/buildingplan/buildingplan_cycle.cpp
and expose to Lua
and use where useful
> [Maps] add api for getting the walkability group of a tile

- docs/plugins/burrow.rst
- plugins/burrow.cpp
- plugins/lua/burrow.lua
and fix flood fill skipping ramp tops
> [burrow] finish implementing CLI

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui.lua
for the gui/design dimensions tooltip
> add FRAME_THIN

- data/init/dfhack.tools.init
- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/plugins/burrow.rst
- library/modules/EventManager.cpp
- plugins/burrow.cpp
- plugins/lua/burrow.lua
also fix bad state tracking in EventManager for the JobStarted event
> [burrow] reintroduce autogrow

- docs/about/Removed.rst
- library/modules/Gui.cpp
and add a focus string for linking levers in preparation for a *new* mechanism-related tool
> Tombstone gui/mechanisms

- data/blueprints/dreamfort.csv
- docs/guides/quickfort-user-guide.rst
- plugins/burrow.cpp
- plugins/lua/autochop.lua
> [quickfort] docs and dreamfort

- docs/changelog.txt
- docs/plugins/buildingplan.rst
- plugins/buildingplan/buildingplan.cpp
- plugins/lua/buildingplan.lua
- plugins/lua/buildingplan/itemselection.lua
- plugins/lua/buildingplan/mechanisms.lua
- plugins/lua/buildingplan/planneroverlay.lua
adds an overlay that extends the link lever panel. it offers a selection dialog for manual choices and heat safety filters for autoselection
> [buildingplan] allow choosing of mechanisms when linking levers

- docs/changelog.txt
- plugins/lua/sort/locationselector.lua
Fixes https://github.com/DFHack/dfhack/issues/3951
> [sort] filter out non-denominational temples if one is established

- docs/changelog.txt
- plugins/lua/sort/info.lua
Fixes https://github.com/DFHack/dfhack/issues/3957
> [sort] support search and filter for work animal assignment

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort/info.lua
on work animal assignment page
this might be useful on all unit lists, but let's just add it here for now
> [sort] filter units by squad or burrow

- docs/changelog.txt
- library/modules/Burrows.cpp
interact with the new `inactive_burrows` vector
> [Burrows] handle inactive burrows when assigning/clearing units

- docs/changelog.txt
- docs/plugins/sort.rst
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
https://github.com/DFHack/dfhack/assets/977482/8d971bd0-c304-41a7-a5d8-5dd75aa3b60b
> [sort] show how many work animals a unit has when assigning

- docs/changelog.txt
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
- plugins/lua/sort/sortoverlay.lua
- plugins/lua/sort/unitselector.lua
https://github.com/DFHack/dfhack/assets/977482/8d6b9ecd-1ec5-4f14-9118-f51a901c4727
Fixes https://github.com/DFHack/dfhack/issues/3956
> [sort] military and burrow membership filters for burrow assignment

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
> implement `Buildings::completebuild` function export from DF

- plugins/lua/sort/unitselector.lua
Fixes https://github.com/DFHack/dfhack/issues/4011
> [sort] don't leak widgets into unrelated screens

- plugins/burrow.cpp
Fixes https://github.com/DFHack/dfhack/issues/3979
> [burrow] allow 3d flood fill in hidden tiles

- .github/release_template.md
- docs/Installing.rst
to help avoid issues with antivirus
> add guidance for installing on windows

- plugins/burrow.cpp
to behave better on the surface and in open spaces
Fixes https://github.com/DFHack/dfhack/issues/3992
Fixes https://github.com/DFHack/dfhack/issues/3993
Fixes https://github.com/DFHack/dfhack/issues/3995
> [burrow] refine flood fill algorithm

- plugins/burrow.cpp
hopefully.
changes:
- don't flood across non-pathable mushroom caps
- don't flood across non-pathable tree branches
- don't flood an extra tile beyond ramp tops
> [burrow] final tweaking of flood fill logic

- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Buildings.h
- library/modules/Buildings.cpp
and remove unneeded params
ref: https://github.com/DFHack/dfhack/issues/2614
> [Buildings] document native completeBuild function

- docs/changelog.txt
- plugins/lua/sort/info.lua
- plugins/lua/sort/sortoverlay.lua
Fixes https://github.com/DFHack/dfhack/issues/3981
> [sort] prevent keys from bleeding through to the vanilla handler and prevent double free

- docs/changelog.txt
- plugins/lua/sort/info.lua
Fixes https://github.com/DFHack/dfhack/issues/4029
> [sort] search associated building in tasks tab

- docs/changelog.txt
- library/modules/Gui.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/diplomacy.lua
- plugins/lua/sort/sortoverlay.lua
Searches for unit name/profession like usual, but also searches the item preferences the unit has
https://github.com/DFHack/dfhack/assets/977482/6a75b4a9-7bca-4917-b8c2-ab9cc145caff
Fixes https://github.com/DFHack/dfhack/issues/4051
> search and sort for elevate to barony page

- docs/about/Authors.rst
Updates ``markdown`` script to work with the Steam version
> Add glotov4 to the list of authors

- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/modules/Gui.cpp
this is the coordinated change to dfhack/df-structures#678
> rename `report_init` to `announcementst` (coordinated change)

- plugins/lua/sort/diplomacy.lua
- plugins/lua/sort/info.lua
for elevate to barony and pet ownership overlays
> [sort] prevent the overlay from being moved out of position when the screen size changes

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Units.cpp
so, for example, you can see whether the animal is +trained+ or semi-wild when assigning to a pasture
> [Units] add "agitated" and trained levels to getReadableName

- library/modules/Buildings.cpp
this is the coordinated change for DFHack/df-structures#682
> change `unitst::owned_buildings` to `vector<building_civzonest*>`

- data/init/dfhack.tools.init
add faststart to default services; remove cruft
> update tools init file

- docs/dev/overlay-dev-guide.rst
- plugins/lua/autolabor.lua
- plugins/lua/buildingplan/inspectoroverlay.lua
- plugins/lua/buildingplan/mechanisms.lua
- plugins/lua/buildingplan/planneroverlay.lua
- plugins/lua/burrow.lua
- plugins/lua/dig.lua
- plugins/lua/hotkeys.lua
- plugins/lua/orders.lua
- plugins/lua/overlay.lua
- plugins/lua/sort.lua
- plugins/lua/sort/diplomacy.lua
- plugins/lua/sort/info.lua
- plugins/lua/sort/locationselector.lua
- plugins/lua/sort/places.lua
- plugins/lua/sort/slab.lua
- plugins/lua/sort/unitselector.lua
- plugins/lua/sort/world.lua
- plugins/lua/stockpiles.lua
- plugins/lua/stocks.lua
- plugins/lua/zone.lua
and update/document the addition to the overlay API
> Add overlay descriptions to all plugins

- docs/changelog.txt
- library/lua/helpdb.lua
Fixes https://github.com/DFHack/dfhack/issues/4109
> treat doc sources as utf-8

- docs/changelog.txt
- plugins/lua/misery.lua
Fixes https://github.com/DFHack/dfhack/issues/4088
> [misery] fix handing of misery factor setting

- docs/changelog.txt
- plugins/work-now.cpp
Fixes https://github.com/DFHack/dfhack/issues/4111
> [work-now] save enabled status with the fort

- docs/changelog.txt
- library/lua/argparse.lua
- plugins/lua/autochop.lua
Fixes https://github.com/DFHack/dfhack/issues/4070
> [autochop] better error output on malformed command

- docs/changelog.txt
- docs/plugins/reveal.rst
- plugins/reveal.cpp
Fixes https://github.com/DFHack/dfhack/issues/4073
> [reveal] don't reveal triggers

- docs/Installing.rst
- docs/changelog.txt
Fixes https://github.com/DFHack/dfhack/issues/4124
> [installing] add installation instructions for wineskin on mac

- docs/plugins/zone.rst
- plugins/lua/zone.lua
Fixes https://github.com/DFHack/dfhack/issues/3766
> [zone] add location retire overlay

- library/lua/gui/dialogs.lua
just for messages and confirmation for now
> add ZScreen-based dialogs

- library/modules/Gui.cpp
needed for site finder confirm prompt
> [Gui] add focus strings for choose_start_site screen

- docs/changelog.txt
- plugins/lua/zone.lua
Fixes: https://github.com/DFHack/dfhack/issues/4143
> [zone] add filter for juveniles to animal assignment dialog

- docs/changelog.txt
- library/lua/gui.lua
- plugins/lua/buildingplan/itemselection.lua
blink the PAUSE FORCED badge for 1 second at a period of 100ms when the game is force paused but the player tries to unpause anyway.
https://github.com/DFHack/dfhack/assets/977482/2162af34-21ad-4b68-8865-eaa33f2c6164
> briefly flash the PAUSE FORCED badge when tested

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort.lua
aligned labels
add toggle all filters hotkey
rename "Weak mental fortitude" to "Dislikes combat"
update docs
addresses part of https://github.com/DFHack/dfhack/issues/4150
> [sort] update layout of squad assignment panel

- library/modules/Job.cpp
> canceling DestroyBuilding jobs no longer crashes

- docs/changelog.txt
- docs/plugins/burrow.rst
- plugins/lua/burrow.lua
add an explicit flood fill enablement toggle
Fixes: https://github.com/DFHack/dfhack/issues/4154
> [burrow] prevent accidental flood fills

- docs/dev/Lua API.rst
- library/lua/dfhack.lua
- library/modules/Persistence.cpp
- library/modules/Units.cpp
- library/modules/World.cpp
- plugins/lua/dwarfvet.lua
- plugins/lua/sort/locationselector.lua
- plugins/lua/sort/places.lua
instead of world.world_data.active_site[0], which is not the current loaded site when the site has been reclaimed
> use plotinfo to find the loaded site id

- docs/changelog.txt
- plugins/getplants.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4171
> [getplants] protect against invalid basic materials

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Units.cpp
Fixes gui/teleport not identifying agitated wildlife as hostile
> [Units] agitated wildlife is dangerous

- docs/plugins/reveal.rst
https://github.com/DFHack/dfhack/issues/4185
> [reveal] add more explanatory text to reveal docs

- docs/changelog.txt
- plugins/buildingplan/buildingplan.cpp
- plugins/buildingplan/buildingplan.h
- plugins/lua/buildingplan/filterselection.lua
- plugins/lua/buildingplan/planneroverlay.lua
and fix count of required materials when some tiles are invalid
Fixes: https://github.com/DFHack/dfhack/issues/4194
Fixes: https://github.com/DFHack/dfhack/issues/3734
Fixes: https://github.com/DFHack/dfhack/issues/3175
> [buildingplan] implement no-constructions-on-constructions option

- docs/changelog.txt
- plugins/buildingplan/buildingplan_cycle.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4197
> [buildingplan] don't use items in wheelbarrows

- plugins/seedwatch.cpp
to make input less pedantic about capitalization
> [seedwatch] try capitalizing id if verbatim text not found

- data/orders/basic.json
- docs/changelog.txt
less food more booze
balance determined by dreamfort testing
> tweak library orders

- docs/changelog.txt
- plugins/design.cpp
We were neglecting to set the ch, fg, bg, etc... to the cur_pen, so it worked fine in graphics but not in ascii. Plainly painting the pen made by get_pen() solves the issue.
Fixes: #4195
> UI fixes for gui/design

- docs/changelog.txt
https://github.com/DFHack/stonesense/issues/101
> changelog entry and ref update for stonesense fix

- docs/changelog.txt
- docs/dev/Dev-intro.rst
- docs/dev/Lua API.rst
and image content
image links helpfully generated by https://www.labnol.org/embed/google/drive/
> update dev guide and image links

- docs/changelog.txt
- docs/plugins/reveal.rst
- plugins/reveal.cpp
automatically reset state on world unload
simplify state logic, especially around pause management
remove nopause
> [reveal] clean up behavior

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/logistics.cpp
for use by https://github.com/DFHack/scripts/pull/961
> move trainer assignment logic into core

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Gui.h
- library/lua/gui.lua
- library/modules/Gui.cpp
> [Gui] implement missing getAny functions

- docs/changelog.txt
- plugins/lua/zone.lua
Continuation of https://github.com/DFHack/scripts/pull/961
This will resolve https://github.com/DFHack/dfhack/issues/4043
Integration of script into zone.lua
> Add Animal Options To Valid Animal Viewsheet

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> make the DFHack ref owner agnostic, not name agnostic

- .github/workflows/build.yml
test against a corresponding structures branch
> when merging/pushing to a non-develop branch

- .github/workflows/build-linux.yml
- .github/workflows/build-windows.yml
- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
This PR also tests whether the branch name linking still works for PRs against non-develop branches
> use default structures ref too

- docs/changelog.txt
- plugins/lua/buildingplan/planneroverlay.lua
Fixes: https://github.com/DFHack/dfhack/issues/4032
> [buildingplan] show abbreviated filter info in planner overlay

- plugins/lua/stockpiles.lua
from Discord: https://discord.com/channels/793331351645323264/807444467140788254/1203771359164108851
> [stockpiles] give better error message when a stockpile is not selected

- docs/changelog.txt
- docs/plugins/cleanowned.rst
- plugins/cleanowned.cpp
Fixes: https://github.com/DFHack/dfhack/issues/3817
Kept changes as small as possible while adding option
Changes
- Update Docs relating to change
- Show correct output for when dumping & confiscating or only confiscating
If need me to change anything just let me know.
> Add a "nodump" Option to cleanowned

- docs/changelog.txt
- docs/plugins/regrass.rst
- plugins/regrass.cpp
but don't change any other behavior
it will take more work to grow grass in biomes/map tiles where there was no grass before
also clean up code
Fixes https://github.com/DFHack/dfhack/issues/1821
> [regrass] also regrow cavern moss

- plugins/lua/tweak.lua
- plugins/tweak/CMakeLists.txt
- plugins/tweak/tweak.cpp
to support control panel integration
> [tweak] support status lookup from lua

- docs/about/Removed.rst
ref: https://github.com/DFHack/scripts/pull/984
> tombstone removed scripts

- docs/about/Removed.rst
and update scripts ref to make sure everything builds ok
> tombstone removed tools

- docs/changelog.txt
- plugins/lua/zone.lua
Fixes: https://github.com/DFHack/dfhack/issues/4181
> [zone] add distance display and sort by distance option

- docs/changelog.txt
- plugins/lua/zone.lua
same space to pause/unpause behavior as gui/launcher
> [zone] show number of assigned creatures; toggle pause with space

- plugins/preserve-tombs.cpp
coordinated with https://github.com/DFHack/df-structures/pull/724
> [preserve-tombs] adjust to new buildings_other vector types

- docs/changelog.txt
- plugins/autonestbox.cpp
also reduce the frequency of nags to once per season and clean up the algorithm
> [autonestbox] respect egg layers' choice of nestbox (if it is in a nestbox zone)

- docs/changelog.txt
- plugins/lua/stocks.lua
Fixes: https://github.com/DFHack/dfhack/issues/4316
> [stocks] add remove empties option for stocks screen

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
to match existing dynamic capabilities for token-level pens
> make top-level pens dynamic for labels

- plugins/misery.cpp
ref: https://github.com/DFHack/df-structures/pull/721
> adjust to structures change

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
As discussed on Discord: https://discord.com/channels/793331351645323264/807444467140788254/1213887307602468874
> [overlay dev guide] update examples and troubleshooting steps

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/helpdb.lua
enables matching all tag filters in gui/launcher
> [helpdb] when matching lists of filters, match all, not any

- docs/changelog.txt
- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
to assist in wildlife domestication programs
Fixes: https://github.com/DFHack/dfhack/issues/4205
> [autobutcher] prefer slaughtering non-domesticated creatures

- docs/Introduction.rst
- docs/Quickstart.rst
- docs/changelog.txt
include instructions for downloading the rendered docs for offline reading (now that we've removed the HTML docs from the distributable)
> Update intro and quick start guide

- docs/changelog.txt
- docs/plugins/sort.rst
- plugins/lua/sort.lua
- plugins/lua/sort/info.lua
- plugins/sort.cpp
> [sort] rewrite and reinstate work animal assignment filter

- docs/changelog.txt
- docs/plugins/cleaners.rst
- plugins/cleaners.cpp
Fixes https://github.com/DFHack/dfhack/issues/4332
> [clean] protect farm plots when cleaning mud

- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- plugins/lua/orders.lua
- plugins/lua/sort.lua
- plugins/lua/stockpiles.lua
so it goes in a common place by default
also use this default position in existing clients
> [widgets.HelpButton] give HelpButton a default position

- docs/changelog.txt
- docs/plugins/logistics.rst
- library/modules/Units.cpp
- plugins/logistics.cpp
- plugins/lua/logistics.lua
will automatically assign trainers to partially trained (but not yet domesticated) livestock
> [logistics] new feature: autoretrain

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
> handle plants in matinfo.decode

- docs/changelog.txt
- docs/plugins/tweak.rst
- plugins/tweak/tweak.cpp
so we don't spam the console on fort load
> [tweak] add quiet option

- library/modules/Gui.cpp
we commented it out for v50 and never got around to updating it
> [Gui] reinstate functionality for getAnyPlant

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
and classify them as "great danger"
> [Units] add check for forgotten beasts

- docs/changelog.txt
- docs/plugins/orders.rst
- plugins/lua/orders.lua
> [orders] implement skill level restriction overlay

- data/blueprints/dreamfort.csv
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- plugins/lua/orders.lua
ref: https://github.com/DFHack/scripts/pull/1038
> document and use quickfort profile setting capabilities

- docs/changelog.txt
- docs/plugins/dwarfvet.rst
- plugins/lua/dwarfvet.lua
Fixes https://github.com/DFHack/dfhack/issues/3919
Fixes https://github.com/DFHack/dfhack/issues/1681
Fixes https://github.com/DFHack/dfhack/issues/1371
> [dwarfvet] unassign animals for treatment; reassign them later

- library/LuaApi.cpp
- library/include/modules/Items.h
- library/modules/Items.cpp
- plugins/createitem.cpp
depends on https://github.com/DFHack/scripts/pull/1044
> use new building item mode enum

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/autochop.cpp
- plugins/autoclothing.cpp
- plugins/misery.cpp
- plugins/seedwatch.cpp
- plugins/strangemood.cpp
- plugins/tailor.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4367
Fixes: https://github.com/DFHack/dfhack/issues/664
Fixes: https://github.com/DFHack/dfhack/issues/2761
> add resident-related functions

- plugins/lua/orders.lua
Fixes https://github.com/DFHack/dfhack/issues/4375
> [orders] single click button to toggle labor

- docs/changelog.txt
- plugins/lua/buildingplan/filterselection.lua
and fix hide_unavailable persistence code
Fixes: https://github.com/DFHack/dfhack/issues/4385
> [buildingplan] sort by quantity by default

- docs/changelog.txt
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/autoclothing.cpp
- plugins/fastdwarf.cpp
- plugins/misery.cpp
- plugins/reveal.cpp
- plugins/tailor.cpp
I would have preferred to return the range so it can be used in caller-controlled for loops, but the return type of a range must be auto, and that won't help in a header file
unless we implement the function there, but that would require us to include df/world.h, which would slow down rebuilds when structures change
> use ranges where we can

- package/launchdf.cpp
reports here:
- https://steamcommunity.com/app/2346660/eventcomments/4294818016874744693/
- https://discord.com/channels/102738113478021120/173888543419006976/1221155913583562884
> [launchdf] temporarily increase launcher verbosity to debug startup error

- docs/changelog.txt
- package/launchdf.cpp
Thank you https://unix.stackexchange.com/questions/427115/listen-for-exit-of-process-given-pid
> use tail instead of inotify for detecting DF process exit

- data/blueprints/aquifer_tap.csv
- data/blueprints/pump_stack.csv
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- plugins/dig.cpp
use damp dig in the aquifer_tap blueprint
use warm and damp dig in the pump stack blueprint
add API in dig for adding individual warm and damp dig tiles
> [quickfort] document warm and damp markers in quickfort blueprints

- plugins/dig.cpp
so all the layers can be seen together on warm+damp+designated+selected+visible wall edge tiles
also add new warmdamp overlay rendering options for `gui/aquifer` and `gui/reveal`
> [dig] handle additional compositing layers for warmdamp

- data/init/dfhack.tools.init
- docs/about/Removed.rst
- docs/plugins/aquifer.rst
> tombstone drain aquifer

- library/modules/Gui.cpp
https://github.com/DFHack/df-structures/pull/714
> Replace hostile_combat with SPARRING_EVENT

- CMakeLists.txt
> Revert "Add DOWNLOAD_SDL2 CMake variable (and default to true)"

- docs/builtins/keybinding.rst
- docs/changelog.txt
- library/Core.cpp
Fixes https://github.com/DFHack/dfhack/issues/4404
> [keybindings] support mouse buttons 4 though 15 for keybindings

- docs/changelog.txt
- plugins/blueprint.cpp
- plugins/dig.cpp
also blueprint/warm/damp markers
Depends on https://github.com/DFHack/df-structures/pull/742
ref: https://github.com/DFHack/dfhack/issues/3510
Fixes: https://github.com/DFHack/dfhack/issues/1363
> [blueprint] record designations and dig/smooth jobs

- LICENSE.rst
As discussed over email with Tanya@Kitfox
> record permission we have from Bay 12 to distribute derived graphic assets

- docs/changelog.txt
- library/modules/Units.cpp
Fixes https://github.com/DFHack/dfhack/issues/4471
> fix isResident detection

- docs/changelog.txt
- docs/plugins/autoclothing.rst
- docs/plugins/tailor.rst
- plugins/autoclothing.cpp
- plugins/tailor.cpp
since this is a constant source of confusion for people
> [autoclothing] add comparison between autoclothing and tailor to the docs

- library/modules/Items.cpp
leak is too small to mention in the changelog, tho
> clean up createItem code and fix memory leak

- docs/guides/quickfort-user-guide.rst
Fixes https://github.com/DFHack/dfhack/issues/4489
> [quickfort] document container shorthand syntax

- docs/dev/Lua API.rst
> Add information on whole property for bitfields

- docs/changelog.txt
- library/lua/gui.lua
- test/library/gui.lua
when DF is started in ascii and is switched to graphcis
Fixes https://github.com/DFHack/dfhack/issues/3444
> fix bad background texture

- docs/api/Maps.rst
> Fix dead link in Maps.rst

- docs/changelog.txt
- plugins/lua/zone.lua
forgot to populate the field for small pets when I did units and vermin
> [zone] fix distance calculation for small pets

- docs/changelog.txt
- docs/plugins/dig.rst
- plugins/dig.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4514
> [dig] show warm/damp/aquifer status for tiles visible from below

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/World.h
- library/modules/Gui.cpp
- library/modules/World.cpp
and make getSelectedUnit return the adventurer if no other unit is selected (and game is in adventure mode)
> add API for getting adventurer unit

- docs/plugins/lair.rst
- plugins/lair.cpp
Fixes https://github.com/DFHack/dfhack/issues/4532
> [lair] clean up code and update docs to prevent confusion

- docs/changelog.txt
- docs/plugins/stockpiles.rst
- plugins/lua/stockpiles.lua
- plugins/stockpiles/stockpiles.cpp
as discussed on [Discord](https://discord.com/channels/793331351645323264/807443277132595211/1235659785102168145)
> [stockpiles] import/export support for route stop settings

- library/LuaApi.cpp
- library/include/Core.h
- library/lua/repeat-util.lua
- library/lua/script-manager.lua
add add them to the perf report
> instrument lua repeat timers

- .gitmodules
- CMakeLists.txt
- depends/CMakeLists.txt
- library/CMakeLists.txt
- library/Hooks.cpp
Fixes https://github.com/DFHack/dfhack/issues/4469
> add dfhooks chainloader

- docs/changelog.txt
- plugins/reveal.cpp
persistent xray vision
Fixes: https://github.com/DFHack/dfhack/issues/4541
> update reveal for adventure mode

- docs/Installing.rst
Fixes: https://github.com/DFHack/dfhack/issues/3032
> document commandline for running under wine

- docs/changelog.txt
- plugins/prospector.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4563
> [prospector] output large numbers in regular, non-scientific notation

- plugins/hotkeys.cpp
- plugins/lua/hotkeys.lua
in custom positions that make sense for that viewscreen
> show DFHack logo on more viewscreens

- data/init/dfhack.keybindings.init
- docs/changelog.txt
- plugins/lua/hotkeys.lua
Fixes: https://github.com/DFHack/dfhack/issues/4569
> add dfhack logo and unretire-anyone keybinding to adventure setup screen

- docs/changelog.txt
- docs/plugins/tweak.rst
- library/modules/Items.cpp
- plugins/tweak/tweak.cpp
- plugins/tweak/tweaks/named-codices.h
Fixes: https://github.com/DFHack/dfhack/issues/4584
> [tweak] new tweak for displaying titles for codices

- plugins/autobutcher.cpp
- plugins/autochop.cpp
- plugins/autoclothing.cpp
- plugins/autofarm.cpp
- plugins/autolabor/autolabor.cpp
- plugins/autonestbox.cpp
- plugins/autoslab.cpp
- plugins/buildingplan/buildingplan.cpp
- plugins/burrow.cpp
- plugins/dwarfvet.cpp
- plugins/logistics.cpp
- plugins/misery.cpp
- plugins/nestboxes.cpp
- plugins/orders.cpp
- plugins/pet-uncapper.cpp
- plugins/preserve-tombs.cpp
- plugins/seedwatch.cpp
- plugins/spectate/spectate.cpp
- plugins/suspendmanager.cpp
- plugins/tailor.cpp
- plugins/work-now.cpp
so we don't spam detection of a site when we don't need to
> check for fortress mode instead of a loaded site

- library/CMakeLists.txt
also sorted because this will happen again
> add missing includes to `library/CMakeList.txt`

- docs/changelog.txt
- plugins/blueprint.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4590
> [blueprint] capture track carving designations

- library/modules/Job.cpp
- plugins/blueprint.cpp
- plugins/dig-now.cpp
- plugins/dig.cpp
depends on https://github.com/DFHack/df-structures/pull/754
> use newly structured job spec flags

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
for use in `gui/design`, but other tools will likely benefit too (if we start making more icons)
Fixes https://github.com/DFHack/dfhack/pull/3441
> add widgets.ButtonGroup

- plugins/3dveins.cpp
- plugins/prospector.cpp
ref: https://github.com/DFHack/df-structures/pull/762
> [3dveins, prospector] update field names

- library/modules/Buildings.cpp
- plugins/blueprint.cpp
- plugins/stockpiles/StockpileSerializer.cpp
ref: https://github.com/DFHack/df-structures/pull/763
> update to canonicalized structures

- docs/changelog.txt
- library/lua/dfhack.lua
- library/lua/gui/widgets.lua
ref: https://github.com/DFHack/scripts/pull/1128 and discord discussion https://discord.com/channels/793331351645323264/807444467140788254/1243412499169017968
> [widgets.FilteredList] don't restrict whitespace entry in filter strings

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
- library/lua/script-manager.lua
> [script-manager] add functions for retrieving mod-related paths

- library/modules/Translation.cpp
- library/modules/Units.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/strangemood.cpp
ref: https://github.com/DFHack/df-structures/pull/764
Units module update deferred to https://github.com/DFHack/dfhack/issues/4641
> update to structures changes

- docs/about/Removed.rst
pairs with https://github.com/DFHack/scripts/pull/1134
> tombstone max-wave

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Maps.h
- library/modules/Maps.cpp
- plugins/aquifer.cpp
Adds the following functions:
- `Maps::isTileAquifer`
- `Maps::isTileHeavyAquifer`
- `Maps::setTileAquifer`
- `Maps::removeTileAquifer`
- `dfhack.maps.removeTileAquifer`
- `dfhack.maps.removeTileAquifer`
- `dfhack.maps.removeTileAquifer`
- `dfhack.maps.removeTileAquifer`
Changes `aquifer.cpp` to use these new functions.
> Add aquifer functions to the Maps module

- docs/about/Removed.rst
pairs well with https://github.com/DFHack/scripts/pull/1133
> tombstone removed devel scripts

- docs/changelog.txt
- plugins/seedwatch.cpp
> `seedwatch`: exclude unplantable tree seeds

- docs/changelog.txt
- plugins/lua/seedwatch.lua
> `seedwatch`: display `-` instead of `0` for unwatched seeds

- library/lua/gui/dwarfmode.lua
> Fix dwarfmode getCenter

- docs/dev/Lua API.rst
- library/LuaApi.cpp
oops, that was kinda the whole point now wasn't it
> export `makeown` to Lua

- docs/changelog.txt
- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
> `autobutcher`: do not butcher pregnant animals

- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
- library/lua/dfhack/buildings.lua
- library/lua/utils.lua
- library/modules/Units.cpp
- plugins/add-spatter.cpp
- plugins/autochop.cpp
- plugins/devel/dumpmats.cpp
- plugins/embark-assistant/survey.cpp
- plugins/eventful.cpp
- plugins/getplants.cpp
- plugins/plants.cpp
- plugins/prospector.cpp
- plugins/stockpiles/StockpileSerializer.cpp
- plugins/strangemood.cpp
- plugins/tailor.cpp
ref: https://github.com/DFHack/df-structures/pull/772
> update to canonicalized field names

- docs/dev/Lua API.rst
- library/modules/Burrows.cpp
- library/modules/Kitchen.cpp
- library/modules/Military.cpp
- library/modules/Units.cpp
- plugins/autolabor/labormanager.cpp
- plugins/orders.cpp
ref: https://github.com/DFHack/df-structures/pull/777
> adapt to structures updates

- docs/about/Authors.rst
for my contributions to adv-rumors.lua, bodyswap.lua and ongoing
> Add-myself-to-authors.rst

- docs/changelog.txt
- library/lua/dfhack.lua
since changing the values directly can result in inconsistent state
ref: https://github.com/DFHack/dfhack/pull/4674/files/2064670a6bd27d705a2adc7e97836fa6eb44a918#r1626983607
> make settings vars private

- library/lua/dfhack.lua
depends on https://github.com/DFHack/scripts/pull/1153
> poke gui/launcher when mortal mode is toggled

- library/lua/dfhack.lua
> Revert "poke gui/launcher when mortal mode is toggled"

- plugins/lua/buildingplan/unlink_mechanisms.lua
Fixes: https://github.com/DFHack/dfhack/issues/4620
> [buildingplan] use common comfirm dialog for mechanism unlinking/freeing and reword messages

- library/lua/tile-material.lua
- library/modules/Constructions.cpp
- library/modules/EventManager.cpp
- library/modules/MapCache.cpp
- plugins/autoclothing.cpp
- plugins/autoslab.cpp
- plugins/blueprint.cpp
- plugins/dig-now.cpp
- plugins/embark-assistant/survey.cpp
- plugins/infiniteSky.cpp
- plugins/lua/sort.lua
- plugins/lua/sort/locationselector.lua
- plugins/lua/sort/places.lua
- plugins/lua/stockflow.lua
- plugins/orders.cpp
- plugins/prospector.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/reveal.cpp
- plugins/tailor.cpp
- plugins/tubefill.cpp
- test/library/utils.lua
- test/plugins/orders.lua
ref: https://github.com/DFHack/df-structures/pull/780
> adapt to canonicalized structures

- library/LuaTypes.cpp
- library/include/DataDefs.h
- library/include/DataFuncs.h
- library/include/DataIdentity.h
> prevent lua from calling C++ functions that return nonprimitive types

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/MiscUtils.cpp
- library/include/MiscUtils.h
and safen up the local object allocation
> make number formatting configurable

- docs/changelog.txt
- plugins/nestboxes.cpp
it's cheap and important. run it every 7 ticks
> [nestboxes] increase the scanning frequency for fertile eggs

- docs/about/Removed.rst
ref: https://github.com/DFHack/scripts/pull/1178
> tombstone adv-rumors

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/MiscUtils.cpp
- library/include/MiscUtils.h
Fixes https://github.com/DFHack/dfhack/issues/4706
> add SI suffix number formatting

- docs/changelog.txt
- docs/plugins/autonestbox.rst
- plugins/autonestbox.cpp
ref: https://discord.com/channels/793331351645323264/1017471248567124049/1251340825510543360
> [autonestbox] don't assign juveniles to nestboxes

- data/blueprints/aquifer_tap.csv
- data/blueprints/dreamfort.csv
- docs/changelog.txt
- docs/guides/quickfort-user-guide.rst
as per Erendir's excellent suggestions: https://discord.com/channels/793331351645323264/1017471248567124049/1251236946693586954
> Many Dreamfort updates 

- docs/guides/quickfort-user-guide.rst
- plugins/logistics.cpp
- plugins/lua/logistics.lua
and fix some logistics issues along the way
ref: https://github.com/DFHack/scripts/pull/1186
> [quickfort] document logistics features

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Items.cpp
to make the method more likely to succeed to remove the item
also hide it afterwards so it is removed from the UI until it is garbage collected
> [Items::remove] also cancel jobs and hide items from ui

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/dev/overlay-dev-guide.rst
- library/lua/gui.lua
- library/lua/gui/widgets.lua
- plugins/lua/autolabor.lua
- plugins/lua/buildingplan/unlink_mechanisms.lua
- plugins/lua/dig.lua
- plugins/lua/hotkeys.lua
- plugins/lua/orders.lua
- plugins/lua/overlay.lua
- plugins/lua/sort/info.lua
- plugins/lua/suspendmanager.lua
- plugins/overlay.cpp
> make overlays behave well with custom max interface width

- docs/plugins/pathable.rst
- plugins/pathable.cpp
Fixes: https://github.com/DFHack/dfhack/issues/3230
> [pathable] add trade depot accessibility detection and highlight

- plugins/tiletypes.cpp
this was done in other parts of tiletypes, but not in the code path called by gui/tiletypes
> [tiletypes] reindex pathfinding after altering the map

- plugins/tiletypes.cpp
Move `reindex_pathfinding` to the `postWrite` section of `paintTile` and `paintArea`
> Fix reindex_pathfinding

- library/modules/Gui.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
ref: https://github.com/DFHack/df-structures/commit/227cf34cd584d885715ae2cd52e5eb5583b50e28
> update names for beta18

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/DFSDL.h
- library/modules/DFSDL.cpp
in support of https://github.com/DFHack/scripts/pull/1208
> support retrieving multiline text from the system clipboard

- library/LuaApi.cpp
- library/include/Core.h
- library/lua/gui.lua
- library/lua/script-manager.lua
and include them in the perf report
> [gui] instrument ZScreen with perf counters

- docs/changelog.txt
- plugins/lua/zone.lua
fix issue reported on [discord](https://discord.com/channels/793331351645323264/873659717174587403/1256236968602374145)
> [zone] move button to not conflict with aquarium toggle

- docs/changelog.txt
- docs/dev/data-identity.rst
- docs/dev/index.rst
WIP
[myk]: available in rendered form here: https://dfhack--4691.org.readthedocs.build/en/4691/docs/dev/data-identity.html
> (WIP) documenation of type identities 

- docs/dev/Lua API.rst
- library/lua/dfhack.lua
- test/library/string.lua
in service of `gui/journal`: https://github.com/DFHack/scripts/pull/1208
> [string:wrap] add option to preserve original newlines in output

- library/lua/dfhack.lua
- test/library/string.lua
as per https://github.com/DFHack/scripts/pull/1208#issuecomment-2199292756
> [string] correctly represent trailing spaces and newlines

- docs/changelog.txt
- plugins/lua/zone.lua
fixes issue brought up on Discord: 
https://discord.com/channels/329272032778780672/580417881385467914/1257483759452950673
https://discord.com/channels/793331351645323264/807444467140788254/1257485884110934076
> [zone] include caged non-animals and units already assigned to a civzone

- docs/changelog.txt
- library/modules/DFSDL.cpp
- test/modules/dfsdl.lua
as found by @wiktor-obrebski
also add some proper unit tests
> fix handling of multiline clipboard text on Windows

- library/include/modules/Job.h
- library/modules/EventManager.cpp
Experimental changes. Though parts have been rewritten, it should be logically equivalent. There may be some DRY issues -- that was intentional as this is a very hot function. 
Assuming I understood correctly, tweaks inspired by ideas from @ab9rf and @chdoc
Of course it is always better handled with hooks, if provided.
> improve job completion handling performance

- docs/changelog.txt
- plugins/lua/zone.lua
e.g. named dragons
as seen on [reddit](https://new.reddit.com/r/dwarffortress/comments/1e506g0/captured_and_tamed_a_dragon_now_it_wont_attack/)
> [zone] fix overlay alignment when animal has portrait

- docs/changelog.txt
- package/linux/dfhack
and document env var for adding to preload list
> remove leftover preload of DFHack lib

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
in service of changes to `list-waves`
> support histfigs for some Units module methods

- docs/changelog.txt
- plugins/pathable.cpp
original Reddit report here: https://www.reddit.com/r/dwarffortress/comments/1e7s78e/comment/le5hatk/?utm_source=share&utm_medium=web2x&context=3
discord discussion here: https://discord.com/channels/793331351645323264/807444467140788254/1264501241913016382
doc updates here: https://github.com/DFHack/scripts/commit/20cae7701e0475bfb2673d8360f46caa36841741
> [pathable] highlight wagon-accessible edge tiles

- docs/changelog.txt
- docs/dev/Lua API.rst
- docs/plugins/plant.rst
- library/LuaApi.cpp
- library/include/modules/Maps.h
- library/include/modules/Units.h
- library/modules/Items.cpp
- library/modules/Maps.cpp
- library/modules/Units.cpp
- plugins/forceequip.cpp
- plugins/plant.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/zone.cpp
Set out to improve `getUnitsInBox` to use `cuboid`, got distracted by issues in `Units.cpp`. Meaningful changes are listed in each commit.
> Units module overhaul; cuboid class changes

- docs/changelog.txt
- library/VTableInterpose.cpp
ref: https://github.com/DFHack/dfhack/pull/4702
Fixes: https://github.com/DFHack/dfhack/issues/4794
> [VTableInterpose] fix crash when reloading savegames with add-spatter enabled

- data/init/dfhack.keybindings.init
- docs/changelog.txt
> [gui/journal] add dwarfmode hotkey

- plugins/work-now.cpp
should have no behavior change; just cleanup
> [work-now] use Job API for setting global flags

- plugins/autobutcher.cpp
- plugins/autochop.cpp
- plugins/autoclothing.cpp
- plugins/autofarm.cpp
- plugins/autonestbox.cpp
- plugins/autoslab.cpp
- plugins/buildingplan/buildingplan.cpp
- plugins/dig.cpp
- plugins/dwarfvet.cpp
- plugins/examples/persistent_per_save_example.cpp
- plugins/infiniteSky.cpp
- plugins/logistics.cpp
- plugins/misery.cpp
- plugins/nestboxes.cpp
- plugins/preserve-tombs.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/seedwatch.cpp
- plugins/stockflow.cpp
- plugins/suspendmanager.cpp
- plugins/tailor.cpp
- plugins/workflow.cpp
plugin_onupdate is only called when the plugin is enabled
> remove unnecessary is_enabled check

- docs/changelog.txt
- library/modules/Buildings.cpp
this prevents a hang in our integration tests
it is unclear whether this issue affects normal tool usage by players
> don't treat unsorted vectors as sorted

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/LuaApi.cpp
- library/include/modules/Units.h
- library/modules/Units.cpp
- plugins/lua/sort/info.lua
- plugins/lua/zone.lua
add and use isWildlife and isAgitated property checks
> [Units] don't assume all undead are dangerous

- docs/changelog.txt
- library/modules/Gui.cpp
was not differentiating Default from Details properly
> fix focus string for work details panel

- data/init/dfhack.tools.init
- docs/about/Removed.rst
- docs/changelog.txt
ref: https://github.com/DFHack/scripts/pull/1271
> tombstone family affairs and add alias

- library/include/modules/Persistence.h
- plugins/preserve-rooms.cpp
and also don't do processing that has been configured to be disabled
> persist-rooms: implement state persistence and loading

- library/modules/EventManager.cpp
- plugins/lua/preserve-rooms.lua
- plugins/preserve-rooms.cpp
and output encoding fixes
ref: https://github.com/DFHack/dfhack/issues/4881
> preserve-rooms: fix logic around restoring zone ownership

- plugins/lua/preserve-rooms.lua
- plugins/preserve-rooms.cpp
ref: https://github.com/DFHack/dfhack/issues/4881
> [preserve-rooms] combine roles that are in promotion chains

- plugins/lua/preserve-rooms.lua
and move panel up a few notches to get it more out of the way
ref: https://github.com/DFHack/dfhack/issues/4881
> [preserve-rooms] make panel disappear when vanilla tooltips are up

- data/blueprints/dreamfort.csv
- docs/guides/quickfort-user-guide.rst
- plugins/lua/preserve-rooms.lua
- plugins/preserve-rooms.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4881
> [preserve-rooms] add API for setting role associations; update dreamfort

- docs/changelog.txt
- plugins/pathable.cpp
or otherwise starts with a pathability group of 0 in its center tile
Fixes: https://github.com/DFHack/dfhack/issues/4903
> [pathable] fix hang when a wagon depot is under water

- docs/changelog.txt
- plugins/pathable.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4904
> [pathable] fix wagon pathability calculation for stairs and doors

- depends/CMakeLists.txt
- depends/lua/CMakeLists.txt
so we don't conflict with other similarly named lua libs
> rename lua lib from lua to lua53

- docs/changelog.txt
- library/Core.cpp
Fixes: https://github.com/DFHack/dfhack/issues/4861
> [Core] also save state on retire

- docs/dev/overlay-dev-guide.rst
- docs/plugins/overlay.rst
- plugins/lua/overlay.lua
Allow to pass CLI arguments  to `overlay_trigger` function.
> Pass CLI arguments  to `overlay_trigger` function

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- test/library/gui/widgets.EditField.lua
Fixes: https://github.com/DFHack/dfhack/issues/4083
Fixes: https://github.com/DFHack/dfhack/issues/3188
> [widgets.EditField] use new text navigation keys

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets.lua
- test/library/gui/widgets.EditField.lua
> Revert "[widgets.EditField] use new text navigation keys"

- docs/dev/Lua API.rst
ref: https://github.com/DFHack/dfhack/pull/4879
> update docs for dfhack.items.createItem

- docs/changelog.txt
- docs/guides/modding-guide.rst
also a heavy editing pass for overall prose and clarity of code examples
Fixes: https://github.com/DFHack/dfhack/issues/4929
> [modding-guide] add examples for persistent storage

- docs/changelog.txt
- library/modules/Units.cpp
- plugins/autobutcher.cpp
undo some incorrect cleanup from #4810
> [Units] fix regression in Units::isGay()

- docs/plugins/dwarfvet.rst
thanks for the suggestion, [Agnieszka](https://discord.com/channels/793331351645323264/807444467140788254/1289657362717610115)!
> [dwarfvet] document that animals need empty floor space

- data/blueprints/aquifer_tap.csv
- docs/changelog.txt
Thank you for the feedback, [Erendir](https://discord.com/channels/793331351645323264/1017471248567124049/1289681541710086165)
> [aquifer_tap] rewrite help, increase dig priority, blueprint stairs

- docs/changelog.txt
- docs/guides/quickfort-library-guide.rst
Fixes https://github.com/DFHack/dfhack/issues/4765
> [Dreamfort] add link to youtube tutorial playlist

- docs/dev/Lua API.rst
- library/include/modules/Translation.h
- library/modules/Items.cpp
- library/modules/Units.cpp
- plugins/autoslab.cpp
- plugins/cleanowned.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
- plugins/showmood.cpp
- plugins/strangemood.cpp
- plugins/tailor.cpp
and change all usages to keep current behavior
> [Translation] default inEnglish to false to match Lua API

- docs/about/Removed.rst
ref: https://github.com/DFHack/scripts/pull/1319
> tombstone modtools/force

- plugins/lua/preserve-rooms.lua
ref: https://github.com/DFHack/df-structures/pull/808
> migrate main_hover_instruction identifiers to new names

- library/include/DataDefs.h
- plugins/buildingplan/itemfilter.cpp
- plugins/buildingplan/itemfilter.h
- plugins/pathable.cpp
- plugins/plant.cpp
- plugins/regrass.cpp
- plugins/stockpiles/OrganicMatLookup.h
- plugins/xlsxreader.cpp
more discoveries consequent to exploring modularization
i got past the plugin dependency issue and was able to make a successful build with BitArray.h restructured as a module. still more work to be done, but this is now potentially feasible
> add several more shadowed header dependencies

- .github/workflows/build-windows.yml
- .github/workflows/generate-symbols.yml
- .github/workflows/watch-df-steam.yml
will need to be merged to be tested
This will allow us to autodetect the full DF version when generating symbols for DF beta versions
> draft code for autodetecting Steam DF version

- plugins/preserve-rooms.cpp
see discord discussion: https://discord.com/channels/793331351645323264/807444467140788254/1314763431148126263
> [preserve-rooms] add check for null in zones vec to test player issue

- plugins/preserve-rooms.cpp
this is slower than #5086 but will catch more errors
> better safety check for preserve-rooms

- .gitattributes
ref: https://github.com/DFHack/scripts/pull/381
> set the union merge strategy for the changelog

- docs/changelog.txt
- docs/plugins/strangemood.rst
- plugins/strangemood.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5111
> [strangemood] add CLI support for stone carving/cutting

- plugins/liquids.cpp
- plugins/tiletypes.cpp
> don't auto-suspend the core for lineedit commands

- depends/CMakeLists.txt
plus patches
Fixes: https://github.com/DFHack/dfhack/issues/5062
> update libzip to current upstream

- .github/workflows/build-linux.yml
- CMakeLists.txt
should be the last of the CMake deprecation warnings
> update libexpat to 2.6.4

- plugins/cursecheck.cpp
> [cursecheck] clean up compiler fix

- library/include/modules/Screen.h
- library/modules/Screen.cpp
Replace seven essentially identical functions with a template and seven instantiations of that template. Don't Repeat Yourself
> clean up moisture in `Screen.cpp`

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/lua/gui/widgets/filtered_list.lua
in service of the upcoming `gui/rename` interface
> [widgets.FilteredList] allow search_key to be dynamic

- docs/dev/Lua API.rst
- docs/guides/modding-guide.rst
> Revert temp changes to docs once pygments is fixed

- docs/changelog.txt
- docs/plugins/orders.rst
- library/modules/Gui.cpp
- plugins/lua/orders.lua
Fixes: https://github.com/DFHack/dfhack/issues/5025
> [orders] allow right click to cancel instead of exiting on work orders pages

- library/lua/gui/widgets/text_area/text_area_content.lua
Fix TextArea custom pens handling.
> Fix TextArea custom pens handling

- ci/download-df.sh
revert this when DF versions are all in sync again
> special case version 51.03 so ci works

- library/lua/json.lua
- library/lua/json/internal.lua
reading an empty json file will now return an empty table instead of nil, making an empty file functionally identical to a missing file.
> Update json lib and change return for empty input

- docs/changelog.txt
- library/lua/gui/widgets/text_area/text_area_content.lua
> [EditField] fix multiline paste in one_line_mode fields

- docs/changelog.txt
- library/Core.cpp
- library/include/Core.h
in service of the upcoming changes to `spectate`
> add Core API for getting unpaused ms

- docs/changelog.txt
- plugins/lua/sort/unitselector.lua
- plugins/lua/zone.lua
Fixes: https://github.com/DFHack/dfhack/issues/5226
> change hotkeys that conflict with EditField's ctrl-a

- docs/about/Authors.rst
Added a `devel/export-map` script via:
- https://github.com/DFHack/scripts/pull/1329
> Update Authors List

- docs/plugins/spectate.rst
- plugins/spectate.cpp
> [spectate] implement cinematic camera

- docs/changelog.txt
- docs/plugins/autobutcher.rst
- plugins/autobutcher.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5243
> [autobutcher] protect chained units

- library/Console-windows.cpp
#5280 wasn't quite right, this finishes the job
> really fix windows console

- data/init/dfhack.keybindings.init
- docs/changelog.txt
- plugins/lua/spectate.lua
- plugins/spectate.cpp
and add global hotkey for gui/sitemap (Ctrl-G)
> [spectate] add API for gui/sitemap

- plugins/lua/spectate.lua
Also produce user-friendly error messages in more cases
> spectate.lua: prevent users from destroying their config

- plugins/lua/spectate.lua
fixed the hitbox of the follow panel overlay, as it was still the old `enable/disabled` hitbox
> Fix spectate.lua

- docs/changelog.txt
- docs/dev/overlay-dev-guide.rst
- plugins/lua/overlay.lua
> [overlay] add enable/disable hooks for widgets

- docs/dev/Lua API.rst
Fix documentation to use correct enums.
> Fix outdated enum names in Lua API.rst

- docs/guides/quickfort-user-guide.rst
Fixes: https://github.com/DFHack/dfhack/issues/5276
> [quickfort user guide] fix dead link

- library/VersionInfoFactory.cpp
Fixes: https://github.com/DFHack/dfhack/issues/5251
> check for null in fprintf

- data/blueprints/aquifer_tap.csv
- docs/changelog.txt
see supporting data here: https://discord.com/channels/793331351645323264/873014631315148840/1347804533543145482
> [aquifer_tap] redesign for better fill rate

- plugins/army-controller-sanity.cpp
this detects a potential error condition that could cause corruption if it occurs
> add another test to army controller sanity plugin

- plugins/lua/sort/places.lua
ref: https://github.com/DFHack/dfhack/pull/5413
> use new assigned_unit API for 51.11

- docs/changelog.txt
- docs/dev/Lua API.rst
- library/modules/Units.cpp
- plugins/lua/sort/sortoverlay.lua
so players see (and can search by) unit english names in DFHack interfaces
> add translated english name to getReadableName output

- docs/changelog.txt
- library/Core.cpp
- library/include/Core.h
as discussed in #5438 and on discord
> Remove unused `RegisterData` API from Core

- docs/changelog.txt
- library/include/modules/Maps.h
- library/modules/Maps.cpp
for use by the upcoming is_disjoint check in `blueprint`
> [Maps] add option for forCoord to iterate in row-major order

- library/LuaApi.cpp
ref: https://github.com/DFHack/dfhack/pull/5422
> canonicalize slashes in output of dfhack.filesystem.listdir

- docs/changelog.txt
- plugins/blueprint.cpp
- plugins/logistics.cpp
- plugins/lua/blueprint.lua
Everything but detailed item type config (which will require integration with the `stockpiles` plugin)
> [blueprint] record stockpile properties

- docs/plugins/plant.rst
Indicate that `regrass` is the proper tool for working with grasses.
> `plant.rst`: Link to `regrass` tool

- library/modules/Burrows.cpp
- plugins/remotefortressreader/remotefortressreader.cpp
Hello world. The title says it all.
> Removes unused declarations to fix warnings (i.e. errors)

- docs/about/Removed.rst
merged into bodyswap via https://github.com/DFHack/scripts/pull/1164
> Tombstone linger💀
